project: 
  type: book
  output-dir: docs
  resources: [chapter_downloads, data, img]

format:
  html:
    df-print: paged
    css: custom.css
#  pdf: default
#  epub: default
  
book: 
  title: "Introduction to Statistics: an integrated textbook and workbook using R"
  author: "Sean Raleigh, Westminster University<br>(Salt Lake City, UT)"
  date: today
  output-file: intro_stats
  search: true
  license: "MIT"
  version: 2.1
  repo-url: https://github.com/VectorPosse/intro_stats
  repo-actions: [edit, issue]
  issue-url: https://github.com/VectorPosse/intro_stats/issues
  chapters: 
    - index.qmd
    - 01-intro_to_r.qmd
    - 02-using_quarto-web.qmd
    - 03-categorical_data-web.qmd
    - 04-numerical_data-web.qmd
    - 05-manipulating_data-web.qmd
    - 06-correlation-web.qmd
    - 07-regression-web.qmd
    - 08-intro_to_randomization_1-web.qmd
    - 09-intro_to_randomization_2-web.qmd
    - 10-hypothesis_testing_with_randomization_1-web.qmd
    - 11-hypothesis_testing_with_randomization_2-web.qmd
    - 12-confidence_intervals-web.qmd
    - 13-normal_models-web.qmd
    - 14-sampling_distribution_models-web.qmd
    - 15-inference_for_one_proportion-web.qmd
    - 16-inference_for_two_proportions-web.qmd
    - 17-chi_square_goodness_of_fit-web.qmd
    # - 18-chi_square_test_for_independence-web.qmd
    # - 19-inference_for_one_mean-web.qmd
    # - 20-inference_for_paired_data-web.qmd
    # - 21-inference_for_two_independent_means-web.qmd
    # - 22-anova-web.qmd
  appendices:
    - Rubric.qmd
    - Concordance.qmd