---
title: "Concordance between OpenIntro textbook and R modules"
output: html_notebook
---

The following table shows the concordance between sections of the [OpenIntro](https://www.openintro.org/stat/textbook.php?stat_book=isrs) textbook and the R modules.

The first module `1. Intro to R` should be distributed to students as an HTML file (the `.nb.html` file not the `.Rmd` file). Every subsequent module after the first should be given to students as an R Notebook file (`.Rmd`).

Note that the `Intro_to_simulation` modules do not quite correspond to the book. I think it is easier to introduce simulation with coin flips rather than permutation tests. When formal hypothesis tests are introduced in 2.3 with a permutation test and then 2.4 with a test for one proportion, the `Hypothesis_testing_with_simulation` modules do respect that ordering.

<!--html_preserve-->
<table class="table table-striped">
    <thead>
        <tr>
            <th>Section</th>
            <th>Filename:</th>
            <th>Topics covered:</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>N/A</td>
            <td><code>01_Intro_to_R.nb.html</code></td>
            <td>Intro to R, practice at the command prompt, loading packages,                   getting help, understanding data files and accessing variables,                 creating new projects in RStudio Server, uploading files.</td>
        </tr>
        <tr>
            <td>N/A</td>
            <td><code>02_Using_R_Markdown.Rmd</code></td>
            <td>R Markdown philosophy and R Notebooks, R Markdown syntax, R code                 chunks, inline R code, exporting files.</td>
        </tr>
        <tr>
            <td>1.6</td>
            <td><code>03_Numerical_data.Rmd</code></td>
            <td>Mean, variance, and sd; median and IQR; five-number summary,                    histograms, scatterplots.</td>
        </tr>
        <tr>
            <td>1.7</td> 
            <td><code>04_Categorical_data.Rmd</code></td>
            <td>Tables (frequency, relative frequency, contingency), bar graphs                 (simple, side-by-side, stacked), boxplots, grouped                              histograms.</td>
        </tr>
        <tr>
            <td>N/A</td>
            <td><code>05_Manipulating_data.Rmd</code></td>
            <td>Importing CSV data, `dplyr` verbs (`select`, `filter`,                          `arrange`, `mutate`, `summarise` with `group_by`).</td>
        </tr>
        <tr>
            <td>2.1, 2.2</td>
            <td><code>06_Intro_to_simulation_1.Rmd</code></td>
            <td>Coin flips (the binomial distribution in disguise) and sampling                 variability.</td>
        </tr>
        <tr>
            <td>2.1, 2.2</td>
            <td><code>07_Intro_to_simulation_2.Rmd</code></td>
            <td>Permutation tests and sampling distribution models.</td>
        </tr>
        <tr>
            <td>N/A</td>
            <td><code>Rubric_for_inference.Rmd</code><br/>
                <code>Rubric_for_inference.nb.html</code></td>
            <td>Reference guide with outline for conducting hypothesis tests and                 confidence intervals.</td>
        </tr>
        <tr>
            <td>2.3</td>
            <td><code>08_Hypothesis_testing_with_simulation_1.Rmd</code></td>
            <td>Hypothesis testing framework for a two-proportion test as a                     permutation test.
        </tr>
        <tr>
            <td>2.4</td>
            <td><code>09_Hypothesis_testing_with_simulation_2.Rmd</code></td>
            <td>Hypothesis testing framework for a one-proportion test using a                  simulated binomial distribution.</td>
        </tr>
        <tr>
            <td>2.5, 2.6</td>
            <td><code>10_Normal_models.Rmd</code></td>
            <td>Central limit theorem, normal distributions, percentiles, z                     scores, QQ plots.</td>
        </tr>
        <tr>
            <td>2.7</td>
            <td><code>11_Sampling_distribution_models.Rmd</code></td>
            <td>The normal model as a sampling distribution model.</td>
        </tr>
        <tr>
            <td>2.8</td>
            <td><code>12_Confidence_intervals.Rmd</code></td>
            <td>Confidence intervals.</td>
        </tr>
        <tr>
            <td>3.1</td>
            <td><code>13_Inference_for_one_proportion.Rmd</code></td>
            <td>Inference for a single proportion, both the one-proportion z                    test and the one-proportion confidence interval.</td>
        </tr>
        <tr>
            <td>3.2</td>
            <td><code>14_Inference_for_two_proportions.Rmd</code></td>
            <td>Inference for two proportions, both the two-proportion z test                   and the two-proportion confidence interval. (Pooling is an                      optional appendix.)</td>
        </tr>
        <tr>
            <td>3.3</td>
            <td><code>15_Chi_square_goodness_of_fit_test.Rmd</code></td>
            <td>Chi-square distribution, chi-square goodness-of-fit test.</td>
        </tr>
        <tr>
            <td>3.4</td>
            <td><code>16_Chi_square_test_for_indepdendence.Rmd</code></td>
            <td>Chi-square test for independence.</td>
        </tr>
        <tr>
            <td>4.1</td>
            <td><code>17_Inference_for_one_mean.Rmd</code></td>
            <td>Student t distribution, one-sample t test.</td>
        </tr>
        <tr>
            <td>4.2</td>
            <td><code>18_Inference_for_paired_data.Rmd</code></td>
            <td>Paired t-test.</td>
        </tr>
        <tr>
            <td>4.3</td>
            <td><code>19_Inference_for_two_independent_means.Rmd</code></td>
            <td>Two-sample t-test.</td>
        </tr>
        <tr>
            <td>4.4</td> 
            <td><code>20_ANOVA.Rmd</code></td>
            <td>One-way ANOVA and Tukey HSD post-hoc test.</td>
        </tr>
        <tr>
            <td>5.1</td>
            <td><code>21_Correlation.Rmd</code></td>
            <td>Correlation.</td>
        </tr>
        <tr>
            <td>5.2, 5.3, 5.4</td>
            <td><code>22_Regression.Rmd</code></td>
            <td>Simple linear regression, interpretation of slope/intercept,                    $R^2$.</td>
        </tr>
    </tbody>
</table>
<!--/html_preserve-->
