<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Statistics: an integrated textbook and workbook using R - 7&nbsp; Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-intro_to_randomization_1-web.html" rel="next">
<link href="./06-correlation-web.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-regression-web.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics: an integrated textbook and workbook using R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/VectorPosse/intro_stats" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro_to_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-using_r_markdown-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Using R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-categorical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-numerical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulating_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulating data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-correlation-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regression-web.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-intro_to_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-intro_to_randomization_2-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-hypothesis_testing_with_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesis_testing_with_randomization_2-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-confidence_intervals-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-normal_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Normal models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-sampling_distribution_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Sampling distribution models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-inference_for_one_proportion-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Inference for one proportion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-inference_for_two_proportions-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for two proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-chi_square_goodness_of_fit-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chi-square goodness-of-fit test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-chi_square_test_for_independence-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Chi-square test for independence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-inference_for_one_mean-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for one mean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-inference_for_paired_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for paired data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inference_for_two_independent_means-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for two independent means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-anova-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rubric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rubric for inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Concordance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Concordance with <em>Introduction to Modern Statistics</em> (IMS)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#functions-introduced-in-this-chapter" id="toc-functions-introduced-in-this-chapter" class="nav-link active" data-scroll-target="#functions-introduced-in-this-chapter">Functions introduced in this chapter</a></li>
  <li><a href="#regression-intro" id="toc-regression-intro" class="nav-link" data-scroll-target="#regression-intro"><span class="header-section-number">7.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#install-new-packages" id="toc-install-new-packages" class="nav-link" data-scroll-target="#install-new-packages"><span class="header-section-number">7.1.1</span> Install new packages</a></li>
  <li><a href="#regression-download" id="toc-regression-download" class="nav-link" data-scroll-target="#regression-download"><span class="header-section-number">7.1.2</span> Download the R notebook file</a></li>
  <li><a href="#regression-restart" id="toc-regression-restart" class="nav-link" data-scroll-target="#regression-restart"><span class="header-section-number">7.1.3</span> Restart R and run all chunks</a></li>
  <li><a href="#regression-load" id="toc-regression-load" class="nav-link" data-scroll-target="#regression-load"><span class="header-section-number">7.1.4</span> Load packages</a></li>
  </ul></li>
  <li><a href="#regression-regression" id="toc-regression-regression" class="nav-link" data-scroll-target="#regression-regression"><span class="header-section-number">7.2</span> Regression</a></li>
  <li><a href="#regression-models" id="toc-regression-models" class="nav-link" data-scroll-target="#regression-models"><span class="header-section-number">7.3</span> Models</a></li>
  <li><a href="#regression-conditions" id="toc-regression-conditions" class="nav-link" data-scroll-target="#regression-conditions"><span class="header-section-number">7.4</span> Checking conditions</a></li>
  <li><a href="#regression-calculating" id="toc-regression-calculating" class="nav-link" data-scroll-target="#regression-calculating"><span class="header-section-number">7.5</span> Calculating the regression line</a></li>
  <li><a href="#regression-interpreting" id="toc-regression-interpreting" class="nav-link" data-scroll-target="#regression-interpreting"><span class="header-section-number">7.6</span> Interpreting the coefficients</a></li>
  <li><a href="#regression-rescaling" id="toc-regression-rescaling" class="nav-link" data-scroll-target="#regression-rescaling"><span class="header-section-number">7.7</span> Rescaling to make interpretations more meaningful</a></li>
  <li><a href="#regression-tidy" id="toc-regression-tidy" class="nav-link" data-scroll-target="#regression-tidy"><span class="header-section-number">7.8</span> The <code>tidy</code> command</a></li>
  <li><a href="#regression-residuals" id="toc-regression-residuals" class="nav-link" data-scroll-target="#regression-residuals"><span class="header-section-number">7.9</span> Residuals</a></li>
  <li><a href="#regression-r2" id="toc-regression-r2" class="nav-link" data-scroll-target="#regression-r2"><span class="header-section-number">7.10</span> <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#regression-multiple" id="toc-regression-multiple" class="nav-link" data-scroll-target="#regression-multiple"><span class="header-section-number">7.11</span> Multiple predictors</a></li>
  <li><a href="#regression-your-turn" id="toc-regression-your-turn" class="nav-link" data-scroll-target="#regression-your-turn"><span class="header-section-number">7.12</span> Your turn</a></li>
  <li><a href="#regression-conclusion" id="toc-regression-conclusion" class="nav-link" data-scroll-target="#regression-conclusion"><span class="header-section-number">7.13</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#regression-prep" id="toc-regression-prep" class="nav-link" data-scroll-target="#regression-prep"><span class="header-section-number">7.13.1</span> Preparing and submitting your assignment</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/VectorPosse/intro_stats/edit/main/07-regression-web.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/VectorPosse/intro_stats/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="regression" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<!-- Please don't mess with the next few lines! -->
<style>h5{font-size:2em;color:#0000FF}h6{font-size:1.5em;color:#0000FF}div.answer{margin-left:5%;border:1px solid #0000FF;border-left-width:10px;padding:25px} div.summary{background-color:rgba(30,144,255,0.1);border:3px double #0000FF;padding:25px}</style>
<p style="color:#ffffff">
2.0
</p>
<!-- Please don't mess with the previous few lines! -->
<section id="functions-introduced-in-this-chapter" class="level3 unnumbered summary">
<h3 class="unnumbered anchored" data-anchor-id="functions-introduced-in-this-chapter">Functions introduced in this chapter</h3>
<p><code>geom_smooth</code>, <code>lm</code>, <code>tidy</code>, <code>augment</code>, <code>glance</code></p>
</section>
<section id="regression-intro" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="regression-intro"><span class="header-section-number">7.1</span> Introduction</h2>
<p>In this chapter we will learn how to run a regression analysis. Regression provides a model for the linear relationship between two numerical variables.</p>
<section id="install-new-packages" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="install-new-packages"><span class="header-section-number">7.1.1</span> Install new packages</h3>
<p>If you are using RStudio Workbench, you do not need to install any packages. (Any packages you need should already be installed by the server administrators.)</p>
<p>If you are using R and RStudio on your own machine instead of accessing RStudio Workbench through a browser, you’ll need to type the following command at the Console:</p>
<pre><code>install.packages("broom")</code></pre>
</section>
<section id="regression-download" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="regression-download"><span class="header-section-number">7.1.2</span> Download the R notebook file</h3>
<p>Check the upper-right corner in RStudio to make sure you’re in your <code>intro_stats</code> project. Then click on the following link to download this chapter as an R notebook file (<code>.Rmd</code>).</p>
<p><a href="https://vectorposse.github.io/intro_stats/chapter_downloads/07-regression.Rmd" download="">https://vectorposse.github.io/intro_stats/chapter_downloads/07-regression.Rmd</a></p>
<p>Once the file is downloaded, move it to your project folder in RStudio and open it there.</p>
</section>
<section id="regression-restart" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="regression-restart"><span class="header-section-number">7.1.3</span> Restart R and run all chunks</h3>
<p>In RStudio, select “Restart R and Run All Chunks” from the “Run” menu.</p>
</section>
<section id="regression-load" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="regression-load"><span class="header-section-number">7.1.4</span> Load packages</h3>
<p>We load the <code>tidyverse</code> package. The <code>faraway</code> package will give access to the Chicago redlining data introduced in the previous chapter and the <code>palmerpenguins</code> package gives us the <code>penguins</code> data. Finally, the <code>broom</code> package will provide tools for cleaning up the output of the regression analysis we perform.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'faraway' was built under R version 4.3.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'palmerpenguins' was built under R version 4.3.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="regression-regression" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="regression-regression"><span class="header-section-number">7.2</span> Regression</h2>
<p>When we have a linear relationship between two numerical variables, we learned in the last chapter that we can compute the correlation coefficient. One serious limitation of the correlation coefficient is that it is only a single number, and therefore, it doesn’t provide a whole lot of information about the nature of the linear relationship itself. It only gives clues as to the strength and direction of the association.</p>
<p>It will be helpful to model this linear relationship with an actual straight line. Such a line is called a <em>regression line</em>. It is also known as a <em>best-fit line</em> or <em>least-squares line</em> for reasons that we will get to later in the chapter.</p>
<p>The mathematics involved in figuring out what this line should be is more complicated than we cover in this book. Fortunately, R will do all the complicated calculations for us and we’ll focus on understanding what they mean.</p>
<p>Recall the <code>chredlin</code> data set from the last chapter investigating the practice of redlining in Chicago in the 1970s. Let’s review the scatterplot of <code>involact</code>, the number of FAIR policies per 100 housing units, against <code>race</code>, the racial composition of each ZIP code as a percentage of minority residents. (Recall that each row of the data represents an entire ZIP code.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chredlin, <span class="fu">aes</span>(<span class="at">y =</span> involact, <span class="at">x =</span> race)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="exercise-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h5>
<p>Does the Chicago redlining data come from an observational study or an experiment? How do you know?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>If certain conditions are met, we can graph a regression line; just add a <code>geom_smooth</code> layer to the scatterplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chredlin, <span class="fu">aes</span>(<span class="at">y =</span> involact, <span class="at">x =</span> race)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <code>method = lm</code> argument is telling <code>ggplot</code> to use a “linear model”. The <code>se = FALSE</code> argument tells <code>ggplot</code> to draw just the line and nothing else. (What else might it try to draw? You are encouraged to go back to the code above and take out <code>se = FALSE</code> to see for yourself. However, we are not yet in a position to be able to explain the gray band that appears. We will return to this mystery in a future chapter.)</p>
<p>Of all possible lines, the blue line comes the closest to each point in the scatterplot. If we wiggled the line a little bit, it might get closer to a few points, but the net effect would be to make it further from other points. This is the mathematically optimal line of best fit.</p>
</section>
</section>
<section id="regression-models" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="regression-models"><span class="header-section-number">7.3</span> Models</h2>
<p>We used the word “model” when referring to the regression line above. What does that word mean in this context?</p>
<p>A model is something that represents something else, often on a smaller scale or in simplified form. A model is often an idealized form of something that may be quite messy or complex in reality. In statistics, a model is a representation of the way data is generated. For example, we may believe that as minority representation increases in a neighborhood, that neighborhood is more likely to be subject to racially discriminatory practices. We may even posit that the relationship is linear; i.e., for every percentage point increase in racial minorities, we expect some kind of proportional increase in racial discrimination, as measured in this case by FAIR policies. We say that this is our hypothesis about the <em>data-generating process</em>: we suspect that the data we see results from a sociological process that uses the minority representation of a neighborhood to generate data about FAIR policies.</p>
<p>The assumption of a linear relationship between these two quantities is just that—an assumption. It is not necessarily “true”, whatever “true” might mean in this kind of question. It is a convenient device that makes a simplifying assumption in order to allow us to do something meaningful in a statistical analysis. If such a model—despite its simplifying caricature—helps us make meaningful predictions to study something important like racial discrimination, then the model is useful.</p>
<p>The first thing we acknowledge when working with a model is that the model does not generate the data in a rigid, deterministic way. If you look at the scatterplot above, even assuming the blue line represents a “correct” data-generating process, the data points don’t fall on the blue line. The blue line gives us only a sense of where the data might be, but there is additional space between the line and the points. These spaces are often referred to as <em>errors</em>. In statistics, the word “error” does not mean the same thing as “mistake”. Error is just the difference between an idealized model prediction and the real location of data. In the context of linear regression, we will use the term <em>residual</em> instead. After the model is done making a prediction, the residuals are “left over” to account for the different between the model and the actual data.</p>
<p>The most important thing to remember about models is that they aren’t real. They are idealizations and simplifications. The degree to which we can trust models, then, comes down to certain assumptions we make about the data-generating process. These assumptions cannot be completely verified—after all, we will never know the exact data-generating process. But there are certain <em>conditions</em> we can check to know if the assumptions we make are reasonable.</p>
<section id="exercise-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h5>
<p>Do an internet search for the phrase “statistical model” and/or “statistical modeling”. Read at least two or three sources. List below one important aspect of statistical modeling you find in your search that wasn’t mentioned in the paragraphs above. (Some of the sources you find may be a little technical. You should, for now, skip over the technical explanations. Try to find several sources that address the issue in non-technical ways. The additional information you mention below should be something non-technical that you understand.)</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
</section>
</section>
<section id="regression-conditions" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="regression-conditions"><span class="header-section-number">7.4</span> Checking conditions</h2>
<p>We need to be careful here. Although we graphed the blue regression line above, we have not checked any conditions. Therefore, it is inappropriate to fit a regression line at this point. Once the line is seen, it cannot easily be “unseen”, and it’s crucial that you don’t trick your eyes into believing there is a linear relationship before checking the conditions that justify that belief.</p>
<p>The regression line we saw above makes no sense unless we know that regression is appropriate. The conditions for running a regression analysis include all the conditions you checked for a correlation analysis in the last chapter:</p>
<ol type="1">
<li>The two variables must be numerical.</li>
<li>There is a somewhat linear relationship between the variables, as shown in a scatterplot.</li>
<li>There are no serious outliers.</li>
</ol>
<section id="exercise-3" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h5>
<p>Check these three conditions for the regression between <code>involact</code> and <code>race</code> (using the scatterplot above for conditions (2) and (3).)</p>
<div class="answer">
<ol type="1">
<li></li>
<li></li>
<li></li>
</ol>
</div>
<hr>
<p>However, there is an additional condition to check to ensure that our regression model is appropriate. It concerns the residuals, but as we haven’t computed anything yet, we have nothing to analyze. We’ll return to this condition later.</p>
</section>
</section>
<section id="regression-calculating" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="regression-calculating"><span class="header-section-number">7.5</span> Calculating the regression line</h2>
<p>What is the equation of the regression line? In your algebra class you learned that a line takes the form <span class="math inline">\(y = mx + b\)</span> where <span class="math inline">\(m\)</span> is the slope and <span class="math inline">\(b\)</span> is the y-intercept. Statisticians write the equation in a slightly different form:</p>
<p><span class="math display">\[
\hat{y} = b_{0} + b_{1} x
\]</span></p>
<p>The intercept is <span class="math inline">\(b_{0}\)</span> and the slope is <span class="math inline">\(b_{1}\)</span>. We use <span class="math inline">\(\hat{y}\)</span> (pronounced “y hat”) instead of <span class="math inline">\(y\)</span> because when we plug in values of <span class="math inline">\(x\)</span>, we do not get back the exact values of <span class="math inline">\(y\)</span> from the data. The line, after all, does not actually pass through most (if any) actual data points. Instead, this equation gives us “predicted” values of <span class="math inline">\(y\)</span> that lie on the regression line. These predicted <span class="math inline">\(y\)</span> values are called <span class="math inline">\(\hat{y}\)</span>.</p>
<p>To run a regression analysis and calculate the values of the intercept and slope, we use the <code>lm</code> command in R. (Again, <code>lm</code> stands for “linear model”.) This command requires us to specify a “formula” that tells R the relationship we want to model. It uses special syntax in a very specific order:</p>
<ul>
<li>The response variable,</li>
<li>a “tilde” ~ (this key is usually in the upper-left corner of your keyboard, above the backtick),</li>
<li>the predictor variable.</li>
</ul>
<p>After a comma, we then specify the data set in which those variables live using <code>data =</code>. Here’s the whole command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(involact <span class="sc">~</span> race, <span class="at">data =</span> chredlin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = involact ~ race, data = chredlin)

Coefficients:
(Intercept)         race  
    0.12922      0.01388  </code></pre>
</div>
</div>
<p><strong>The response variable always goes before the tilde and the predictor variable always goes after.</strong></p>
<p>Let’s store that result for future use. The convention we’ll use in this book is to name things using the variables involved. For example,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>involact_race_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(involact <span class="sc">~</span> race, <span class="at">data =</span> chredlin)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>involact_race_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = involact ~ race, data = chredlin)

Coefficients:
(Intercept)         race  
    0.12922      0.01388  </code></pre>
</div>
</div>
<p>The variable <code>involact_race_lm</code> now contains all the information we need about the linear regression model.</p>
</section>
<section id="regression-interpreting" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="regression-interpreting"><span class="header-section-number">7.6</span> Interpreting the coefficients</h2>
<p>Look at the output of the <code>lm</code> command above.</p>
<p>The intercept is 0.12922 and the slope is 0.01388. The number 0.12922 is labeled with <code>(Intercept)</code>, so that’s pretty obvious. But how do we know the number 0.01388 corresponds to the slope? Process of elimination, I suppose. But there’s another good reason too. The equation of the regression line can be written</p>
<p><span class="math display">\[
\hat{y} = 0.12922 + 0.01388 x
\]</span></p>
<p>When we report the equation of the regression line, we typically use words instead of <span class="math inline">\(\hat{y}\)</span> and <span class="math inline">\(x\)</span> to make the equation more interpretable in the context of the problem. For example, for this data, we would write the equation as</p>
<p><span class="math display">\[
\widehat{involact} = 0.12922 + 0.01388 race
\]</span></p>
<p>The slope is the <em>coefficient</em> of <code>race</code>, or the number attached to <code>race</code>. (The intercept is not attached to anything; it’s just a constant term out front there.)</p>
<p>The slope <span class="math inline">\(b_{1}\)</span> is always interpretable. This model predicts that one unit of increase in the x-direction corresponds to a change of 0.01388 units in the y-direction. Let’s phrase it this way:</p>
<blockquote class="blockquote">
<p>The model predicts that an increase of one percentage point in the composition of racial minorities corresponds to an increase of 0.01388 new FAIR policies per 100 housing units.</p>
</blockquote>
<p>The intercept <span class="math inline">\(b_{0}\)</span> is a different story. There is always a literal interpretation:</p>
<blockquote class="blockquote">
<p>The model predicts that a ZIP code with 0% racial minorites will generate 0.12922 new FAIR policies.</p>
</blockquote>
<p>In some cases (rarely), that interpretation might make sense. In most cases, though, it is physically impossible for the predictor variable to take a value of 0, or the value 0 is way outside the range of the data. Whenever we use a model to make a prediction outside of reasonable values, we call that <em>extrapolation</em>.</p>
<p>For the Chicago data, we likely don’t have a case of extrapolation. While it is not literally true that any ZIP code has 0% racial minorities, we can see in the scatterplot that there are values very close to zero.</p>
<section id="exercise-4" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h5>
<p>Use the <code>arrange</code> command from <code>dplyr</code> to sort the <code>chredlin</code> data frame by race (using the default ascending order). What is the value of <code>race</code> for the three ZIP codes with the smallest percentage of minority residents?</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to sort by race</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Please write up your answer here.</p>
</div>
<hr>
<p>Again, even though there are no ZIP codes with 0% racial minorities, there are a bunch that are close to zero, so the literal interpretation of the intercept is also likely a sensible one in this case.</p>
</section>
<section id="exercise-5" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-5">Exercise 5</h5>
<p>Let’s think through something else the intercept might be telling us in this case. The presumption is that FAIR policies are obtained mostly by folks who can’t get insurance policies in other ways. Some of that is driven by racial discrimination, but maybe not all of it. What does the intercept have to say about the number of FAIR policies that are obtained <em>not</em> due to denial of coverage from racial discrimination?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="regression-rescaling" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="regression-rescaling"><span class="header-section-number">7.7</span> Rescaling to make interpretations more meaningful</h2>
<p>Let’s revisit the interpretation of the slope:</p>
<blockquote class="blockquote">
<p>The model predicts that an increase of one percentage point in the composition of racial minorities corresponds to an increase of 0.01388 new FAIR policies per 100 housing units.</p>
</blockquote>
<p>This is a perfectly correct statement, but one percentage point change is not very much. It’s hard to think about comparing two neighborhoods that differ by only one percent. This scale also makes the predicted change in the response variable hard to interpret. How many policies is 0.01388 per 100 housing units?</p>
<p>One way to make these kinds of statements more interpretable is to change the scale. What if we increase 10 percentage points instead of only 1 percentage point? In other words, what if we move 10 times as far along the x-axis. The response variable will also have to move 10 times as far. This is the new statement:</p>
<blockquote class="blockquote">
<p>The model predicts that an increase of 10 percentage points in the composition of racial minorities corresponds to an increase of 0.1388 new FAIR policies per 100 housing units.</p>
</blockquote>
<p>In this case, the decimal 0.1388 is maybe still not completely clear, but at least an increase of 10 percentage points is a meaningful difference between neighborhoods.</p>
<section id="exercise-6" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-6">Exercise 6</h5>
<p>Since the last number is a <em>per capita</em> type measure, we can also rescale it. If the model predicts an increase in 0.1388 new FAIR policies per 100 households (corresponding to 10 percentage points increase in racial minorities), how many FAIR policies would that be in 1000 households?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="regression-tidy" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="regression-tidy"><span class="header-section-number">7.8</span> The <code>tidy</code> command</h2>
<p>Recall the output of the <code>lm</code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>involact_race_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = involact ~ race, data = chredlin)

Coefficients:
(Intercept)         race  
    0.12922      0.01388  </code></pre>
</div>
</div>
<p>(We did not have to run <code>lm</code> again. We had this output stored in the variable <code>involact_race_lm</code>.)</p>
<p>That summary is fine, but what if we needed to reference the slope and intercept using inline code? Or what if we wanted to grab those numbers and use them in further calculations?</p>
<p>The problem is that the results of <code>lm</code> just print the output in an unstructured way. If we want structured input, we can use the <code>tidy</code> command from the <code>broom</code> package. This will take the results of <code>lm</code> and organize the output into a tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(involact_race_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic      p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)   0.129    0.0966       1.34 0.188       
2 race          0.0139   0.00203      6.84 0.0000000178</code></pre>
</div>
</div>
<p>Let’s store that tibble so we can refer to it in the future.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>involact_race_tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(involact_race_lm)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>involact_race_tidy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic      p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)   0.129    0.0966       1.34 0.188       
2 race          0.0139   0.00203      6.84 0.0000000178</code></pre>
</div>
</div>
<p>The intercept is stored in the <code>estimate</code> column, in the first row. The slope is stored in the same column, but in the second row. (There is a lot more information here to the right of the <code>estimate</code> column, but we will not know what these numbers mean until later in the course.)</p>
<p>We can grab the <code>estimate</code> column with the dollar sign as we’ve seen before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>involact_race_tidy<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.12921803 0.01388235</code></pre>
</div>
</div>
<p>This is a “vector” of two values, the intercept and the slope, respectively.</p>
<p>What if we want only one value at a time? We can grab individual elements of a vector using square brackets as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>involact_race_tidy<span class="sc">$</span>estimate[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.129218</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>involact_race_tidy<span class="sc">$</span>estimate[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01388235</code></pre>
</div>
</div>
<p>Here is the interpretation of the slope again, but this time, we’ll use inline code:</p>
<blockquote class="blockquote">
<p>The model predicts that an increase of 1 percentage points in the composition of racial minorities corresponds to an increase of 0.0138824 new FAIR policies per 100 housing units.</p>
</blockquote>
<p>Click somewhere inside the backticks on the line above and hit Ctrl-Enter or Cmd-Enter (PC or Mac respectively). You should see the number 0.01388235 pop up. If you Preview the HTML version of the document, you will also see the number there (not the code).</p>
<p>What if we want to apply re-scaling to make this number more interpretable? The stuff inside the inline code chunk is just R code, so we can do any kind of calculation with it we want.</p>
<blockquote class="blockquote">
<p>The model predicts that an increase of 10 percentage points in the composition of racial minorities corresponds to an increase of 0.1388235 new FAIR policies per 100 housing units.</p>
</blockquote>
<p>Now the number will be 0.1388235, ten times as large.</p>
<section id="exercise-7" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-7">Exercise 7</h5>
<p>Copy and paste the interpretation of the intercept from earlier, but replace the number 0.12922 with an inline code chunk that grabs that number from the <code>estimate</code> column of the <code>involact_race_tidy</code> tibble. (Remember that the intercept is the <em>first</em> element of that vector, not the second element like the slope.)</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="regression-residuals" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="regression-residuals"><span class="header-section-number">7.9</span> Residuals</h2>
<p>Earlier, we promised to revisit the topic of residuals. Residuals are measured as the vertical distances from each data point to the regression line. We can see that visually below. (Don’t worry about the complexity of the <code>ggplot</code> code used to create this picture. You will not need to create a plot like this on your own, so just focus on the graph that is created below.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chredlin, <span class="fu">aes</span>(<span class="at">y =</span> involact, <span class="at">x =</span> race)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_segment</span>(<span class="at">x =</span> <span class="fl">35.1</span>, <span class="at">xend  =</span> <span class="fl">35.1</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="fl">0.6164886</span>, <span class="at">yend =</span> <span class="fl">0.6164886</span> <span class="sc">+</span> <span class="fl">0.38351139</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_segment</span>(<span class="at">x =</span> <span class="fl">66.1</span>, <span class="at">xend =</span> <span class="fl">66.1</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="fl">1.0468415</span>, <span class="at">yend =</span> <span class="fl">1.0468415</span> <span class="sc">-</span> <span class="fl">0.64684154</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graph above shows the regression line and two of the residuals as red line segments. (There is a residual for all 47 ZIP codes; only two are shown in this graph.) The one on the left corresponds to ZIP code with 35% racial minority. The regression line predicts that, if the model were true, such a ZIP code would have a value of <code>involact</code> of about 0.6. But the actual data for that ZIP code has an <code>involact</code> value of 1. The residual is the difference, about 0.4. In other words, the true data point is 0.4 units higher than the model prediction. This represents a <em>positive</em> residual; the actual data is 0.4 units <em>above</em> the line. Data points that lie below the regression line have <em>negative</em> residuals.</p>
<section id="exercise-8" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-8">Exercise 8</h5>
<p>Look at the residual on the right. This corresponds to a ZIP code with about 66% racial minorities. First, estimate the value of <code>involact</code> that the model predicts for this ZIP code. (This is the y-value of the point on the regression line.) Next, report the actual <code>involact</code> value for this ZIP code. Finally, subtract these two numbers to get an approximate value for the residual. Should this residual be a positive number or a negative number?</p>
<p>You can just estimate with your eyeballs for now. You don’t need to be super precise.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>More formally, let’s call the residual <span class="math inline">\(e\)</span>. This is standard notation, as “e” stands for “error”. Again, though, it’s not an error in the sense of a mistake. It’s an error in the sense that the model is not perfectly accurate, so it doesn’t predict the data points exactly. The degree to which the prediction misses is the “error” or “residual”. It is given by the following formula:</p>
<p><span class="math display">\[
e = y - \hat{y}
\]</span></p>
</section>
<section id="exercise-9" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-9">Exercise 9</h5>
<p>There are two symbols on the right-hand side of the equation above, <span class="math inline">\(y\)</span> and <span class="math inline">\(\hat{y}\)</span>. Which one is the actual data value and which one is the predicted value (the one on the line)?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>The residuals are used to determine the regression line. The correct regression line will be the one that results in the smallest residuals overall. How do we measure the overall set of residuals? We can’t just calculate the average residual. Because the regression line should go through the middle of the data, the positive residuals will cancel out the negative residuals and the mean residual will just be zero. That’s not very useful.</p>
<p>Instead, what we do is <em>square</em> the residuals. That makes all of them positive. Then we add together all the squared residuals and that sum is the thing we try to minimize. Well, we don’t do that manually because it’s hard, so we let the computer do that for us. Because the regression line minimizes the sum of the squared residuals, the regression line is often called the <em>least-squares</em> line.</p>
<p>Recall earlier when we mentioned that there was one additional condition to check in order for linear regression to make sense. This condition is that <strong>there should not be any kind of pattern in the residuals</strong>.</p>
<p>We know that some of the points are going to lie above the line (positive residuals) and some of the points will lie below the line (negative residuals). What we need is for the spread of the residuals to be pretty balanced across the length of the regression line and for the residuals not to form any kind of curved pattern.</p>
<p>To check this condition, we’ll need to calculate the residuals first. To do so, we introduce a new function from the <code>broom</code> package. Whereas <code>tidy</code> serves up information about the intercept and the slope of the regression line, <code>augment</code> gives us extra information for each data point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>involact_race_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(involact_race_lm)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>involact_race_aug</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 47 × 9
   .rownames involact  race .fitted .resid   .hat .sigma .cooksd .std.resid
   &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1 60626          0    10     0.268 -0.268 0.0341  0.452 0.00651     -0.608
 2 60640          0.1  22.2   0.437 -0.337 0.0246  0.451 0.00731     -0.761
 3 60613          1.2  19.6   0.401  0.799 0.0261  0.437 0.0436       1.80 
 4 60657          0.5  17.3   0.369  0.131 0.0277  0.453 0.00124      0.295
 5 60614          0.7  24.5   0.469  0.231 0.0235  0.453 0.00326      0.520
 6 60610          0.3  54     0.879 -0.579 0.0287  0.445 0.0253      -1.31 
 7 60611          0     4.9   0.197 -0.197 0.0398  0.453 0.00417     -0.448
 8 60625          0     7.1   0.228 -0.228 0.0372  0.453 0.00517     -0.517
 9 60618          0.4   5.3   0.203  0.197 0.0393  0.453 0.00411      0.448
10 60647          1.1  21.5   0.428  0.672 0.0250  0.442 0.0295       1.52 
# ℹ 37 more rows</code></pre>
</div>
</div>
<p>The first three columns consist of the row names (the ZIP codes) followed by the actual data values we started with for <code>involact</code> and <code>race</code>. But now we’ve “augmented” the original data with some new stuff too. (We won’t learn about anything past the fifth column in this course, though.)</p>
<p>The fourth column—called <code>.fitted</code>—is <span class="math inline">\(\hat{y}\)</span>, or the point on the line that corresponds to the given <span class="math inline">\(x\)</span> value. Let’s check and make sure this is working as advertised.</p>
<p>The regression equation from above is</p>
<p><span class="math display">\[
\widehat{involact} = 0.12922 + 0.01388 race
\]</span></p>
<p>Take, for example, the first row in the tibble above, the one corresponding to ZIP code 60626. The value of <code>race</code> is 10.0. Plug that value into the equation above:</p>
<p><span class="math display">\[
\widehat{involact} = 0.12922 + 0.01388(10.0) = 0.268
\]</span></p>
<p>The model predicts that a ZIP code with 10% racial minorities will have about 0.268 new FAIR policies per 100 housing units. The corresponding number in the <code>.fitted</code> column is 0.2680416, so that’s correct.</p>
<p>Now skip over to the fifth column of the <code>augment</code> output, the one that says <code>.resid</code>. If this is the residual <span class="math inline">\(e\)</span>, then it should be <span class="math inline">\(y - \hat{y}\)</span>. Since <span class="math inline">\(y\)</span> is the actual value of <code>involact</code> and <span class="math inline">\(\hat{y}\)</span> is the value predicted by the model, we should get for the first row of output</p>
<p><span class="math display">\[
e = y - \hat{y} = 0.0 - 0.268 = -0.268
\]</span></p>
<p>Yup, it works!</p>
<p>To check for patterns in the residuals, we’ll create a <em>residual plot</em>. A residual plot graphs the residuals above each value along the x-axis. (In the command below, we also add a blue horizontal reference line so that it is clear which points have positive or negative residuals.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(involact_race_aug, <span class="fu">aes</span>(<span class="at">y =</span> .resid, <span class="at">x =</span> race)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pay close attention to the <code>ggplot</code> code. Notice that the tibble in the first slot is <em>not</em> <code>chredlin</code> as it was before. The residuals we need to plot are not stored in the raw <code>chredlin</code> data. We had to calculate the residuals using the <code>augment</code> command, and those residuals are then stored in a different place that we named <code>involact_race_aug</code>. In the latter tibble, the residuals themselves are stored in a variable called <code>.resid</code>. (Don’t forget the dot in <code>.resid</code>.)</p>
<p>We are looking for systematic patterns in the residuals. A good residual plot should look like the most boring plot you’ve ever seen.</p>
<p>For the most part, the residual plot above looks pretty good. The one exception is the clustering near the left edge of the graph.</p>
</section>
<section id="exercise-10" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-10">Exercise 10</h5>
<p>Refer back and forth between the original scatterplot created earlier (with the regression line) and the residual plot above. Can you explain why there is a line of data points with negative residuals along the left edge of the residual plot?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>Residual patterns that are problematic often involve curved data (where the dots follow a curve around the horizontal reference line instead of spreading evenly around it) and <em>heteroscedasticity</em>, which is a fanning out pattern from left to right.</p>
<p>Other than the weird cluster of points at the left, the rest of the residual plot looks pretty good. Ignoring those ZIP codes with 0 FAIR policies, the rest of the residuals stretch, on average, about the same height above and below the line across the whole width of the plot. There is only one slightly large residual at about the 40% mark, but it’s not extreme, and it doesn’t look like a severe outlier in the original scatterplot.</p>
<p>What does a bad residual plot look like? The code below will run an ill-advised regression analysis on <code>fire</code>, the number of fires (per 100 housing units), against <code>age</code>, the percent of housing units built before 1939. The residual plot appears below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>fire_age_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(fire <span class="sc">~</span> age, <span class="at">data =</span> chredlin)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>fire_age_aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(fire_age_lm)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fire_age_aug, <span class="fu">aes</span>(<span class="at">y =</span> .resid, <span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exercise-11" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-11">Exercise 11</h5>
<p>Using the vocabulary established above, explain why the residual plot above is bad.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>Of course, we should never even get as far as running a regression analysis and making a residual plot if we perform exploratory data analysis as we’re supposed to.</p>
</section>
<section id="exercise-12a" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-12a">Exercise 12(a)</h5>
<p>If you were truly interested in investigating an association between the fire risk and the age of buildings in a ZIP code, the first thing you would do is create a scatterplot. Go ahead and do that below. Use <code>fire</code> as the response variable and <code>age</code> as the predictor.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to create a scatterplot of fire against age</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-12b" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-12b">Exercise 12(b)</h5>
<p>From the scatterplot above, explain why you wouldn’t even get as far as running a regression analysis. (Think of the conditions.)</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>To review, the conditions for a regression analysis are as follows (including the newest fourth condition):</p>
<ol type="1">
<li>The two variables must be numerical.</li>
<li>There is a somewhat linear relationship between the variables, as shown in a scatterplot.</li>
<li>There are no serious outliers.</li>
<li><strong>There is no pattern in the residuals.</strong></li>
</ol>
</section>
</section>
<section id="regression-r2" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="regression-r2"><span class="header-section-number">7.10</span> <span class="math inline">\(R^2\)</span></h2>
<p>We’ve seen that the correlation coefficient r is of limited utility. In addition to being only a single statistic to summarize a linear association, the number doesn’t have any kind of intrinsic meaning. It can only be judged by how close it is to 0 or 1 (or -1) in conjunction with a scatterplot to give you a sense of the strength of the correlation. <strong>In particular, some people try to interpret r as some kind of percentage, but it’s not.</strong></p>
<p>On the other hand, when we square the correlation coefficient, we <em>do</em> get an interpretable number. For some reason, instead of writing <span class="math inline">\(r^2\)</span>, statisticians write <span class="math inline">\(R^2\)</span>, with a capital R. (I can’t find the historical reason why this is so.) In any event, <span class="math inline">\(R^2\)</span> can be interpreted as a percentage! It represents the percent of variation in the y variable that can be explained by variation in the x variable.</p>
<p>Here we introduce the last of the <code>broom</code> functions: <code>glance</code>. Whereas <code>tidy</code> reports the intercept and slope, and <code>augment</code> reports values associated to each data point separately, the <code>glance</code> function gathers up summaries for the entire model. (Do not confuse <code>glance</code> with <code>glimpse</code>. The latter is a nicer version of <code>str</code> that just summarizes the variables in a tibble.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>involact_race_glance <span class="ot">&lt;-</span> <span class="fu">glance</span>(involact_race_lm)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>involact_race_glance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic      p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.509         0.499 0.449      46.7 0.0000000178     1  -28.0  62.0  67.6
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>A more advanced statistics course might discuss the other model summaries present in the <code>glance</code> output. The <span class="math inline">\(R^{2}\)</span> value is stored in the <code>r.squared</code> (inexplicably, now written with a lowercase r). Its value is 0.51. We will word it this way:</p>
<blockquote class="blockquote">
<p>51% of the variability in FAIR policies can be accounted for by variability in racial composition.</p>
</blockquote>
<p>Another way to think about this is to imagine all the factors that might go into the number of FAIR policies obtained in a ZIP code. That number varies across ZIP codes, with some ZIP codes having essentially 0 FAIR policies per 100 housing units, and others having quite a bit more, up to 2 or more per 100 housing units. What accounts for this discrepancy among ZIP codes? Is it the varying racial composition of those neighborhoods? To some degree, yes. We have seen that more racially diverse neighborhoods, on average, require more FAIR policies. But is race the only factor? Probably not. Income, for example, might play a role. People in low income neighborhoods may not be able to acquire traditional insurance due to its cost or their poor credit, etc. That also accounts for some of the variability among ZIP codes. Are there likely even more factors? Most assuredly. In fact, if 51% of the variability in FAIR policies can be accounted for by variability in racial composition. then 49% must be accounted for by other variables. These other variables may or may not be collected in our data, and we will never be able to determine all the factors that go into varying FAIR policy numbers.</p>
<p><span class="math inline">\(R^2\)</span> is a measure of the fit of the model. High values of <span class="math inline">\(R^2\)</span> mean that the line predicts the data values closely, whereas lower values of <span class="math inline">\(R^2\)</span> mean that there is still a lot of variability left in the residuals (again, due to other factors that are not measured in the model).</p>
<section id="exercise-13" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-13">Exercise 13</h5>
<p>Calculate the correlation coefficient r between <code>involact</code> and <code>race</code> using the <code>cor</code> command. (You might have to look back at the last chapter to remember the syntax.) Store that value as r.</p>
<p>In a separate code chunk, square that value using the command <code>r^2</code>. Verify that the square of the correlation coefficient is the same as the <span class="math inline">\(R^2\)</span> value reported in the <code>glance</code> output above.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to calculate the correlation coefficient</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to square the correlation coefficient</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
</section>
<section id="regression-multiple" class="level2" data-number="7.11">
<h2 data-number="7.11" class="anchored" data-anchor-id="regression-multiple"><span class="header-section-number">7.11</span> Multiple predictors</h2>
<p>The discussion of <span class="math inline">\(R^2\)</span> above highlights the fact that a single predictor will rarely account for all or even most of the variability in a response variable. Is there a way to take other predictors into account?</p>
<p>The answer is yes, and the statistical technique involved is called multiple regression. Multiple regression is a deep subject, worthy of entire courses. Suffice it to say here that more advanced stats courses go into the ways in which multiple predictors can be included in a regression.</p>
<p>One easy thing we can do is incorporate a categorical variable into a graph and see if that categorical variable might play a role in the regression analysis. For example, there is a variance called <code>side</code> in <code>chredlin</code> that indicates whether the ZIP code is on the north side (n) or south side(s) of Chicago. As described in an earlier chapter, we can use color to distinguish between the ZIP codes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chredlin, <span class="fu">aes</span>(<span class="at">y =</span> involact, <span class="at">x =</span> race, <span class="at">color =</span> side)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="exercise-14" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-14">Exercise 14</h5>
<p>Do neighborhoods with higher percent racial minorities tend to be on the north or south side of Chicago?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>Does this affect the regression? We haven’t checked the conditions carefully for this new question, so we will exercise caution in coming to any definitive conclusions. But visually, there does appear to be a difference in the models generated for ZIP codes on the north versus south sides:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chredlin, <span class="fu">aes</span>(<span class="at">y =</span> involact, <span class="at">x =</span> race, <span class="at">color =</span> side)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="07-regression-web_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exercise-15" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-15">Exercise 15</h5>
<p>Although the slopes appear to be different, this is quite misleading. Focus on just the red dots. Which regression condition appears to be violated if we only consider the north side regression? How does that violation appear to affect the slope of the regression line?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="regression-your-turn" class="level2" data-number="7.12">
<h2 data-number="7.12" class="anchored" data-anchor-id="regression-your-turn"><span class="header-section-number">7.12</span> Your turn</h2>
<p>Let’s revisit the <code>penguins</code> data. Imagine that it was much easier to measure body mass than it was to measure flipper length. (I’m not a penguin expert, so I don’t know if that’s true, but it seems plausible. Weighing a penguin can be done without human contact, for example.) Can we accurately predict flipper length from body mass? (This means that <code>flipper_length_mm</code> should be the response variable on the y-axis and <code>body_mass_g</code> should be the predictor variable on the x-axis.)</p>
<section id="exercise-16a" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16a">Exercise 16(a)</h5>
<p>Create a scatterplot of the data. Do <em>not</em> include a regression line yet. (In other words, there should be no <code>geom_smooth</code> in this plot.)</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to create a scatterplot of the data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-16b" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16b">Exercise 16(b)</h5>
<p>Use the scatterplot above to check the first three conditions of regression.</p>
<div class="answer">
<ol type="1">
<li></li>
<li></li>
<li></li>
</ol>
</div>
</section>
<section id="exercise-16c" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16c">Exercise 16(c)</h5>
<p>As we’re reasonably satisfied that the first three conditions are met and regression is worth pursuing, run the <code>lm</code> command to perform the regression analysis. Assign the output to the name <code>fl_bm_lm</code>. Be sure to type the variable name <code>fl_bm_lm</code> on its own line so that the output is printed in this file.</p>
<p>Then use <code>tidy</code>, <code>augment</code>, and <code>glance</code> respectively on the output. Assign the output to the names <code>fl_bm_tidy</code>, <code>fl_bm_aug</code>, and <code>fl_bm_glance</code>. Again, in each code chunk, type the output variable name on its own line to ensure that it prints in this file.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to generate and print regression output with lm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to "tidy" and print the output from lm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to "augment" and print the output from lm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to "glance" at and print the output from lm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-16d" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16d">Exercise 16(d)</h5>
<p>Use the <code>augment</code> output from above to create a residual plot with a blue horizontal reference line.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to create a residual plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-16e" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16e">Exercise 16(e)</h5>
<p>Use the residual plot to check the fourth regression condition.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-16f" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16f">Exercise 16(f)</h5>
<p>With all the conditions met, plot the regression line on top of the scatterplot of the data. (Use <code>geom_smooth</code> with <code>method = lm</code> and <code>se = FALSE</code> as in the examples earlier.)</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to plot the regression line on the scatterplot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-16g" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16g">Exercise 16(g)</h5>
<p>Using the values of the intercept and slope from the <code>tidy</code> output, write the regression equation mathematically (enclosing your answer in double dollar signs as above), using contextually meaningful variable names.</p>
<div class="answer">
<p><span class="math display">\[
write-math-here
\]</span></p>
</div>
</section>
<section id="exercise-16h" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16h">Exercise 16(h)</h5>
<p>Interpret the slope in a full, contextually meaningful sentence.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-16i" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16i">Exercise 16(i)</h5>
<p>Give a literal interpretation of the intercept. Then comment on the appropriateness of that interpretation. (In other words, does the intercept make sense, or is it a case of extrapolation?)</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-16j" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16j">Exercise 16(j)</h5>
<p>Use the equation of the regression line to predict the flipper length of a penguin with body mass 4200 grams. Show your work. Then put that prediction into a full, contextually meaningful sentence.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-16k" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16k">Exercise 16(k)</h5>
<p>Using the value of <span class="math inline">\(R^2\)</span> from the <code>glance</code> output for the model of flipper length by body mass, write a full, contextually meaningful sentence interpreting that value.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-16l" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-16l">Exercise 16(l)</h5>
<p>Add <code>color = species</code> to the <code>aes</code> portion of the <code>ggplot</code> command to look at the regression lines for the three different species separately. Comment on the slopes of those three regression lines.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to plot regressions by species</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="regression-conclusion" class="level2" data-number="7.13">
<h2 data-number="7.13" class="anchored" data-anchor-id="regression-conclusion"><span class="header-section-number">7.13</span> Conclusion</h2>
<p>Going beyond mere correlation, a regression analysis allows us to specify a linear model in the form of an equation. Assuming the conditions are met, this allows us to say more about the association. For example, the slope predicts how the response changes when comparing two values of the predictor. In fact, we can use the regression line to make a prediction for any reasonable value of the predictor (being careful not to extrapolate). Because regression is only a model, these predictions will not be exactly correct. Real data comes with residuals, meaning deviations from the idealized predictions of the model. But if those residuals are relatively small then the <span class="math inline">\(R^2\)</span> value will be large and the model does a good job making reasonably accurate predictions.</p>
<section id="regression-prep" class="level3" data-number="7.13.1">
<h3 data-number="7.13.1" class="anchored" data-anchor-id="regression-prep"><span class="header-section-number">7.13.1</span> Preparing and submitting your assignment</h3>
<ol type="1">
<li>From the “Run” menu, select “Restart R and Run All Chunks”.</li>
<li>Deal with any code errors that crop up. Repeat steps 1–-2 until there are no more code errors.</li>
<li>Spell check your document by clicking the icon with “ABC” and a check mark.</li>
<li>Hit the “Preview” button one last time to generate the final draft of the <code>.nb.html</code> file.</li>
<li>Proofread the HTML file carefully. If there are errors, go back and fix them, then repeat steps 1–5 again.</li>
</ol>
<p>If you have completed this chapter as part of a statistics course, follow the directions you receive from your professor to submit your assignment.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-correlation-web.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-intro_to_randomization_1-web.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 1</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>