<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Statistics: an integrated textbook and workbook using R - 11&nbsp; Hypothesis testing with randomization, Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12-confidence_intervals-web.html" rel="next">
<link href="./10-hypothesis_testing_with_randomization_1-web.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-hypothesis_testing_with_randomization_2-web.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics: an integrated textbook and workbook using R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro_to_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-using_r_markdown-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Using R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-categorical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-numerical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulating_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulating data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-correlation-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regression-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-intro_to_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-intro_to_randomization_2-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-hypothesis_testing_with_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesis_testing_with_randomization_2-web.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-confidence_intervals-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-normal_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Normal models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-sampling_distribution_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Sampling distribution models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-inference_for_one_proportion-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Inference for one proportion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-inference_for_two_proportions-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for two proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-chi_square_goodness_of_fit-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chi-square goodness-of-fit test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-chi_square_test_for_independence-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Chi-square test for independence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-inference_for_one_mean-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for one mean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-inference_for_paired_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for paired data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inference_for_two_independent_means-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for two independent means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-anova-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rubric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rubric for inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Concordance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Concordance with <em>Introduction to Modern Statistics</em> (IMS)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#functions-introduced-in-this-chapter" id="toc-functions-introduced-in-this-chapter" class="nav-link active" data-scroll-target="#functions-introduced-in-this-chapter">Functions introduced in this chapter</a></li>
  <li><a href="#hypothesis2-intro" id="toc-hypothesis2-intro" class="nav-link" data-scroll-target="#hypothesis2-intro"><span class="header-section-number">11.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-install" id="toc-hypothesis2-install" class="nav-link" data-scroll-target="#hypothesis2-install"><span class="header-section-number">11.1.1</span> Install new packages</a></li>
  <li><a href="#hypothesis2-download" id="toc-hypothesis2-download" class="nav-link" data-scroll-target="#hypothesis2-download"><span class="header-section-number">11.1.2</span> Download the R notebook file</a></li>
  <li><a href="#hypothesis2-restart" id="toc-hypothesis2-restart" class="nav-link" data-scroll-target="#hypothesis2-restart"><span class="header-section-number">11.1.3</span> Restart R and run all chunks</a></li>
  </ul></li>
  <li><a href="#hypothesis2-load" id="toc-hypothesis2-load" class="nav-link" data-scroll-target="#hypothesis2-load"><span class="header-section-number">11.2</span> Load packages</a></li>
  <li><a href="#hypothesis2-question" id="toc-hypothesis2-question" class="nav-link" data-scroll-target="#hypothesis2-question"><span class="header-section-number">11.3</span> Our research question</a></li>
  <li><a href="#hypothesis2ex-eda" id="toc-hypothesis2ex-eda" class="nav-link" data-scroll-target="#hypothesis2ex-eda"><span class="header-section-number">11.4</span> Exploratory data analysis</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-ex-documentation" id="toc-hypothesis2-ex-documentation" class="nav-link" data-scroll-target="#hypothesis2-ex-documentation"><span class="header-section-number">11.4.1</span> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</a></li>
  <li><a href="#hypothesis2-ex-prepare" id="toc-hypothesis2-ex-prepare" class="nav-link" data-scroll-target="#hypothesis2-ex-prepare"><span class="header-section-number">11.4.2</span> Prepare the data for analysis.</a></li>
  <li><a href="#hypothesis2-ex-plots" id="toc-hypothesis2-ex-plots" class="nav-link" data-scroll-target="#hypothesis2-ex-plots"><span class="header-section-number">11.4.3</span> Make tables or plots to explore the data visually.</a></li>
  </ul></li>
  <li><a href="#hypothesis2-logic" id="toc-hypothesis2-logic" class="nav-link" data-scroll-target="#hypothesis2-logic"><span class="header-section-number">11.5</span> The logic of inference and randomization</a></li>
  <li><a href="#hypothesis2-ex-hypotheses" id="toc-hypothesis2-ex-hypotheses" class="nav-link" data-scroll-target="#hypothesis2-ex-hypotheses"><span class="header-section-number">11.6</span> Hypotheses</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-ex-sample-pop" id="toc-hypothesis2-ex-sample-pop" class="nav-link" data-scroll-target="#hypothesis2-ex-sample-pop"><span class="header-section-number">11.6.1</span> Identify the sample (or samples) and a reasonable population (or populations) of interest.</a></li>
  <li><a href="#hypothesis2-ex-express-words" id="toc-hypothesis2-ex-express-words" class="nav-link" data-scroll-target="#hypothesis2-ex-express-words"><span class="header-section-number">11.6.2</span> Express the null and alternative hypotheses as contextually meaningful full sentences.</a></li>
  <li><a href="#hypothesis2-ex-express-math" id="toc-hypothesis2-ex-express-math" class="nav-link" data-scroll-target="#hypothesis2-ex-express-math"><span class="header-section-number">11.6.3</span> Express the null and alternative hypotheses in symbols (when possible).</a></li>
  </ul></li>
  <li><a href="#hypothesis2-ex-model" id="toc-hypothesis2-ex-model" class="nav-link" data-scroll-target="#hypothesis2-ex-model"><span class="header-section-number">11.7</span> Model</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-ex-sampling-dist-model" id="toc-hypothesis2-ex-sampling-dist-model" class="nav-link" data-scroll-target="#hypothesis2-ex-sampling-dist-model"><span class="header-section-number">11.7.1</span> Identify the sampling distribution model.</a></li>
  <li><a href="#hypothesis2-ex-ht-conditions" id="toc-hypothesis2-ex-ht-conditions" class="nav-link" data-scroll-target="#hypothesis2-ex-ht-conditions"><span class="header-section-number">11.7.2</span> Check the relevant conditions to ensure that model assumptions are met.</a></li>
  </ul></li>
  <li><a href="#hypothesis2-ex-mechanics" id="toc-hypothesis2-ex-mechanics" class="nav-link" data-scroll-target="#hypothesis2-ex-mechanics"><span class="header-section-number">11.8</span> Mechanics</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-ex-compute-test-stat" id="toc-hypothesis2-ex-compute-test-stat" class="nav-link" data-scroll-target="#hypothesis2-ex-compute-test-stat"><span class="header-section-number">11.8.1</span> Compute the test statistic.</a></li>
  <li><a href="#hypothesis2-ex-report-test-stat" id="toc-hypothesis2-ex-report-test-stat" class="nav-link" data-scroll-target="#hypothesis2-ex-report-test-stat"><span class="header-section-number">11.8.2</span> Report the test statistic in context (when possible).</a></li>
  <li><a href="#hypothesis2-ex-plot-null" id="toc-hypothesis2-ex-plot-null" class="nav-link" data-scroll-target="#hypothesis2-ex-plot-null"><span class="header-section-number">11.8.3</span> Plot the null distribution.</a></li>
  <li><a href="#hypothesis2-ex-calculate-p" id="toc-hypothesis2-ex-calculate-p" class="nav-link" data-scroll-target="#hypothesis2-ex-calculate-p"><span class="header-section-number">11.8.4</span> Calculate the P-value.</a></li>
  <li><a href="#hypothesis2-ex-interpret-p" id="toc-hypothesis2-ex-interpret-p" class="nav-link" data-scroll-target="#hypothesis2-ex-interpret-p"><span class="header-section-number">11.8.5</span> Interpret the P-value as a probability given the null.</a></li>
  </ul></li>
  <li><a href="#hypothesis2-ex-ht-conclusion" id="toc-hypothesis2-ex-ht-conclusion" class="nav-link" data-scroll-target="#hypothesis2-ex-ht-conclusion"><span class="header-section-number">11.9</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-ex-stat-conclusion" id="toc-hypothesis2-ex-stat-conclusion" class="nav-link" data-scroll-target="#hypothesis2-ex-stat-conclusion"><span class="header-section-number">11.9.1</span> State the statistical conclusion.</a></li>
  <li><a href="#hypothesis2-ex-context-conclusion" id="toc-hypothesis2-ex-context-conclusion" class="nav-link" data-scroll-target="#hypothesis2-ex-context-conclusion"><span class="header-section-number">11.9.2</span> State (but do not overstate) a contextually meaningful conclusion.</a></li>
  <li><a href="#hypothesis2-ex-reservations" id="toc-hypothesis2-ex-reservations" class="nav-link" data-scroll-target="#hypothesis2-ex-reservations"><span class="header-section-number">11.9.3</span> Express reservations or uncertainty about the generalizability of the conclusion.</a></li>
  <li><a href="#hypothesis2-ex-errors" id="toc-hypothesis2-ex-errors" class="nav-link" data-scroll-target="#hypothesis2-ex-errors"><span class="header-section-number">11.9.4</span> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</a></li>
  </ul></li>
  <li><a href="#hypothesis2-your-turn" id="toc-hypothesis2-your-turn" class="nav-link" data-scroll-target="#hypothesis2-your-turn"><span class="header-section-number">11.10</span> Your turn</a></li>
  <li><a href="#hypothesis2-conclusion" id="toc-hypothesis2-conclusion" class="nav-link" data-scroll-target="#hypothesis2-conclusion"><span class="header-section-number">11.11</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#hypothesis2-prep" id="toc-hypothesis2-prep" class="nav-link" data-scroll-target="#hypothesis2-prep"><span class="header-section-number">11.11.1</span> Preparing and submitting your assignment</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="hypothesis2" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<!-- Please don't mess with the next few lines! -->
<style>h5{font-size:2em;color:#0000FF}h6{font-size:1.5em;color:#0000FF}div.answer{margin-left:5%;border:1px solid #0000FF;border-left-width:10px;padding:25px} div.summary{background-color:rgba(30,144,255,0.1);border:3px double #0000FF;padding:25px}</style>
<p style="color:#ffffff">
2.0
</p>
<!-- Please don't mess with the previous few lines! -->
<section id="functions-introduced-in-this-chapter" class="level3 unnumbered summary">
<h3 class="unnumbered anchored" data-anchor-id="functions-introduced-in-this-chapter">Functions introduced in this chapter</h3>
<p><code>factor</code></p>
</section>
<section id="hypothesis2-intro" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="hypothesis2-intro"><span class="header-section-number">11.1</span> Introduction</h2>
<p>Now that we have learned about hypothesis testing, we’ll explore a different example. Although the rubric for performing the hypothesis test will not change, the individual steps will be implemented in a different way due to the research question we’re asking and the type of data used to answer it.</p>
<section id="hypothesis2-install" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="hypothesis2-install"><span class="header-section-number">11.1.1</span> Install new packages</h3>
<p>If you are using RStudio Workbench, you do not need to install any packages. (Any packages you need should already be installed by the server administrators.)</p>
<p>If you are using R and RStudio on your own machine instead of accessing RStudio Workbench through a browser, you’ll need to type the following command at the Console:</p>
<pre><code>install.packages("MASS")</code></pre>
</section>
<section id="hypothesis2-download" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="hypothesis2-download"><span class="header-section-number">11.1.2</span> Download the R notebook file</h3>
<p>Check the upper-right corner in RStudio to make sure you’re in your <code>intro_stats</code> project. Then click on the following link to download this chapter as an R notebook file (<code>.Rmd</code>).</p>
<p><a href="https://vectorposse.github.io/intro_stats/chapter_downloads/11-hypothesis_testing_with_randomization_2.Rmd" download="">https://vectorposse.github.io/intro_stats/chapter_downloads/11-hypothesis_testing_with_randomization_2.Rmd</a></p>
<p>Once the file is downloaded, move it to your project folder in RStudio and open it there.</p>
</section>
<section id="hypothesis2-restart" class="level3" data-number="11.1.3">
<h3 data-number="11.1.3" class="anchored" data-anchor-id="hypothesis2-restart"><span class="header-section-number">11.1.3</span> Restart R and run all chunks</h3>
<p>In RStudio, select “Restart R and Run All Chunks” from the “Run” menu.</p>
</section>
</section>
<section id="hypothesis2-load" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="hypothesis2-load"><span class="header-section-number">11.2</span> Load packages</h2>
<p>In additional to <code>tidyverse</code> and <code>janitor</code>, we load the <code>MASS</code> package to access the <code>Melanoma</code> data on patients in Denmark with malignant melanoma, and the <code>infer</code> package for inference tools.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hypothesis2-question" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="hypothesis2-question"><span class="header-section-number">11.3</span> Our research question</h2>
<p>We know that certain types of cancer are more common among females or males. Is there a sex bias among patients with malignant melanoma?</p>
<p>Let’s jump into the “Exploratory data analysis” part of the rubric first.</p>
</section>
<section id="hypothesis2ex-eda" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="hypothesis2ex-eda"><span class="header-section-number">11.4</span> Exploratory data analysis</h2>
<section id="hypothesis2-ex-documentation" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="hypothesis2-ex-documentation"><span class="header-section-number">11.4.1</span> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</h3>
<p>You can look at the help file by typing <code>?Melanoma</code> at the Console. However, do not put that command here in a code chunk. The R Notebook has no way of displaying a help file when it’s processed. Be careful: there’s another data set called <code>melanoma</code> with a lower-case “m”. Make sure you are using an uppercase “M”.</p>
<p>There is a reference at the bottom of the help file.</p>
<section id="exercise-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h5>
<p>Using the reference in the help file, do an internet search to find the source of this data. How can you tell that this reference is not, in fact, a reference to a study of cancer patients in Denmark?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>From the exercise above, we can see that it will be very difficult, if not impossible, to discover anything useful about the true provenance of the data (unless you happen to have a copy of that textbook, which in theory provided another more primary source). We will not know, for example, how the data was collected and if the patients consented to having their data shared publicly. The data is suitably anonymized, though, so we don’t have any serious concerns about the privacy of the data. Having said that, if a condition is rare enough, a dedicated research can often “de-anonymize” data by cross-referencing information in the data to other kinds of public records. But melanoma is not particularly rare. At any rate, all we can do is assume that the textbook authors obtained the data from a source that used proper procedures for collecting and handling the data.</p>
<p>We print the data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Melanoma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    time status sex age year thickness ulcer
1     10      3   1  76 1972      6.76     1
2     30      3   1  56 1968      0.65     0
3     35      2   1  41 1977      1.34     0
4     99      3   0  71 1968      2.90     0
5    185      1   1  52 1965     12.08     1
6    204      1   1  28 1971      4.84     1
7    210      1   1  77 1972      5.16     1
8    232      3   0  60 1974      3.22     1
9    232      1   1  49 1968     12.88     1
10   279      1   0  68 1971      7.41     1
11   295      1   0  53 1969      4.19     1
12   355      3   0  64 1972      0.16     1
13   386      1   0  68 1965      3.87     1
14   426      1   1  63 1970      4.84     1
15   469      1   0  14 1969      2.42     1
16   493      3   1  72 1971     12.56     1
17   529      1   1  46 1971      5.80     1
18   621      1   1  72 1972      7.06     1
19   629      1   1  95 1968      5.48     1
20   659      1   1  54 1972      7.73     1
21   667      1   0  89 1968     13.85     1
22   718      1   1  25 1967      2.34     1
23   752      1   1  37 1973      4.19     1
24   779      1   1  43 1967      4.04     1
25   793      1   1  68 1970      4.84     1
26   817      1   0  67 1966      0.32     0
27   826      3   0  86 1965      8.54     1
28   833      1   0  56 1971      2.58     1
29   858      1   0  16 1967      3.56     0
30   869      1   0  42 1965      3.54     0
31   872      1   0  65 1968      0.97     0
32   967      1   1  52 1970      4.83     1
33   977      1   1  58 1967      1.62     1
34   982      1   0  60 1970      6.44     1
35  1041      1   1  68 1967     14.66     0
36  1055      1   0  75 1967      2.58     1
37  1062      1   1  19 1966      3.87     1
38  1075      1   1  66 1971      3.54     1
39  1156      1   0  56 1970      1.34     1
40  1228      1   1  46 1973      2.24     1
41  1252      1   0  58 1971      3.87     1
42  1271      1   0  74 1971      3.54     1
43  1312      1   0  65 1970     17.42     1
44  1427      3   1  64 1972      1.29     0
45  1435      1   1  27 1969      3.22     0
46  1499      2   1  73 1973      1.29     0
47  1506      1   1  56 1970      4.51     1
48  1508      2   1  63 1973      8.38     1
49  1510      2   0  69 1973      1.94     0
50  1512      2   0  77 1973      0.16     0
51  1516      1   1  80 1968      2.58     1
52  1525      3   0  76 1970      1.29     1
53  1542      2   0  65 1973      0.16     0
54  1548      1   0  61 1972      1.62     0
55  1557      2   0  26 1973      1.29     0
56  1560      1   0  57 1973      2.10     0
57  1563      2   0  45 1973      0.32     0
58  1584      1   1  31 1970      0.81     0
59  1605      2   0  36 1973      1.13     0
60  1621      1   0  46 1972      5.16     1
61  1627      2   0  43 1973      1.62     0
62  1634      2   0  68 1973      1.37     0
63  1641      2   1  57 1973      0.24     0
64  1641      2   0  57 1973      0.81     0
65  1648      2   0  55 1973      1.29     0
66  1652      2   0  58 1973      1.29     0
67  1654      2   1  20 1973      0.97     0
68  1654      2   0  67 1973      1.13     0
69  1667      1   0  44 1971      5.80     1
70  1678      2   0  59 1973      1.29     0
71  1685      2   0  32 1973      0.48     0
72  1690      1   1  83 1971      1.62     0
73  1710      2   0  55 1973      2.26     0
74  1710      2   1  15 1973      0.58     0
75  1726      1   0  58 1970      0.97     1
76  1745      2   0  47 1973      2.58     1
77  1762      2   0  54 1973      0.81     0
78  1779      2   1  55 1973      3.54     1
79  1787      2   1  38 1973      0.97     0
80  1787      2   0  41 1973      1.78     1
81  1793      2   0  56 1973      1.94     0
82  1804      2   0  48 1973      1.29     0
83  1812      2   1  44 1973      3.22     1
84  1836      2   0  70 1972      1.53     0
85  1839      2   0  40 1972      1.29     0
86  1839      2   1  53 1972      1.62     1
87  1854      2   0  65 1972      1.62     1
88  1856      2   1  54 1972      0.32     0
89  1860      3   1  71 1969      4.84     1
90  1864      2   0  49 1972      1.29     0
91  1899      2   0  55 1972      0.97     0
92  1914      2   0  69 1972      3.06     0
93  1919      2   1  83 1972      3.54     0
94  1920      2   1  60 1972      1.62     1
95  1927      2   1  40 1972      2.58     1
96  1933      1   0  77 1972      1.94     0
97  1942      2   0  35 1972      0.81     0
98  1955      2   0  46 1972      7.73     1
99  1956      2   0  34 1972      0.97     0
100 1958      2   0  69 1972     12.88     0
101 1963      2   0  60 1972      2.58     0
102 1970      2   1  84 1972      4.09     1
103 2005      2   0  66 1972      0.64     0
104 2007      2   1  56 1972      0.97     0
105 2011      2   0  75 1972      3.22     1
106 2024      2   0  36 1972      1.62     0
107 2028      2   1  52 1972      3.87     1
108 2038      2   0  58 1972      0.32     1
109 2056      2   0  39 1972      0.32     0
110 2059      2   1  68 1972      3.22     1
111 2061      1   1  71 1968      2.26     0
112 2062      1   0  52 1965      3.06     0
113 2075      2   1  55 1972      2.58     1
114 2085      3   0  66 1970      0.65     0
115 2102      2   1  35 1972      1.13     0
116 2103      1   1  44 1966      0.81     0
117 2104      2   0  72 1972      0.97     0
118 2108      1   0  58 1969      1.76     1
119 2112      2   0  54 1972      1.94     1
120 2150      2   0  33 1972      0.65     0
121 2156      2   0  45 1972      0.97     0
122 2165      2   1  62 1972      5.64     0
123 2209      2   0  72 1971      9.66     0
124 2227      2   0  51 1971      0.10     0
125 2227      2   1  77 1971      5.48     1
126 2256      1   0  43 1971      2.26     1
127 2264      2   0  65 1971      4.83     1
128 2339      2   0  63 1971      0.97     0
129 2361      2   1  60 1971      0.97     0
130 2387      2   0  50 1971      5.16     1
131 2388      1   1  40 1966      0.81     0
132 2403      2   0  67 1971      2.90     1
133 2426      2   0  69 1971      3.87     0
134 2426      2   0  74 1971      1.94     1
135 2431      2   0  49 1971      0.16     0
136 2460      2   0  47 1971      0.64     0
137 2467      1   0  42 1965      2.26     1
138 2492      2   0  54 1971      1.45     0
139 2493      2   1  72 1971      4.82     1
140 2521      2   0  45 1971      1.29     1
141 2542      2   1  67 1971      7.89     1
142 2559      2   0  48 1970      0.81     1
143 2565      1   1  34 1970      3.54     1
144 2570      2   0  44 1970      1.29     0
145 2660      2   0  31 1970      0.64     0
146 2666      2   0  42 1970      3.22     1
147 2676      2   0  24 1970      1.45     1
148 2738      2   0  58 1970      0.48     0
149 2782      1   1  78 1969      1.94     0
150 2787      2   1  62 1970      0.16     0
151 2984      2   1  70 1969      0.16     0
152 3032      2   0  35 1969      1.29     0
153 3040      2   0  61 1969      1.94     0
154 3042      1   0  54 1967      3.54     1
155 3067      2   0  29 1969      0.81     0
156 3079      2   1  64 1969      0.65     0
157 3101      2   1  47 1969      7.09     0
158 3144      2   1  62 1969      0.16     0
159 3152      2   0  32 1969      1.62     0
160 3154      3   1  49 1969      1.62     0
161 3180      2   0  25 1969      1.29     0
162 3182      3   1  49 1966      6.12     0
163 3185      2   0  64 1969      0.48     0
164 3199      2   0  36 1969      0.64     0
165 3228      2   0  58 1969      3.22     1
166 3229      2   0  37 1969      1.94     0
167 3278      2   1  54 1969      2.58     0
168 3297      2   0  61 1968      2.58     1
169 3328      2   1  31 1968      0.81     0
170 3330      2   1  61 1968      0.81     1
171 3338      1   0  60 1967      3.22     1
172 3383      2   0  43 1968      0.32     0
173 3384      2   0  68 1968      3.22     1
174 3385      2   0   4 1968      2.74     0
175 3388      2   1  60 1968      4.84     1
176 3402      2   1  50 1968      1.62     0
177 3441      2   0  20 1968      0.65     0
178 3458      3   0  54 1967      1.45     0
179 3459      2   0  29 1968      0.65     0
180 3459      2   1  56 1968      1.29     1
181 3476      2   0  60 1968      1.62     0
182 3523      2   0  46 1968      3.54     0
183 3667      2   0  42 1967      3.22     0
184 3695      2   0  34 1967      0.65     0
185 3695      2   0  56 1967      1.03     0
186 3776      2   1  12 1967      7.09     1
187 3776      2   0  21 1967      1.29     1
188 3830      2   1  46 1967      0.65     0
189 3856      2   0  49 1967      1.78     0
190 3872      2   0  35 1967     12.24     1
191 3909      2   1  42 1967      8.06     1
192 3968      2   0  47 1967      0.81     0
193 4001      2   0  69 1967      2.10     0
194 4103      2   0  52 1966      3.87     0
195 4119      2   1  52 1966      0.65     0
196 4124      2   0  30 1966      1.94     1
197 4207      2   1  22 1966      0.65     0
198 4310      2   1  55 1966      2.10     0
199 4390      2   0  26 1965      1.94     1
200 4479      2   0  19 1965      1.13     1
201 4492      2   1  29 1965      7.06     1
202 4668      2   0  40 1965      6.12     0
203 4688      2   0  42 1965      0.48     0
204 4926      2   0  50 1964      2.26     0
205 5565      2   0  41 1962      2.90     0</code></pre>
</div>
</div>
<p>Use <code>glimpse</code> to examine the structure of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Melanoma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 205
Columns: 7
$ time      &lt;int&gt; 10, 30, 35, 99, 185, 204, 210, 232, 232, 279, 295, 355, 386,…
$ status    &lt;int&gt; 3, 3, 2, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, …
$ sex       &lt;int&gt; 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, …
$ age       &lt;int&gt; 76, 56, 41, 71, 52, 28, 77, 60, 49, 68, 53, 64, 68, 63, 14, …
$ year      &lt;int&gt; 1972, 1968, 1977, 1968, 1965, 1971, 1972, 1974, 1968, 1971, …
$ thickness &lt;dbl&gt; 6.76, 0.65, 1.34, 2.90, 12.08, 4.84, 5.16, 3.22, 12.88, 7.41…
$ ulcer     &lt;int&gt; 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …</code></pre>
</div>
</div>
</section>
</section>
<section id="hypothesis2-ex-prepare" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="hypothesis2-ex-prepare"><span class="header-section-number">11.4.2</span> Prepare the data for analysis.</h3>
<p>It appears that <code>sex</code> is coded as an integer. You will recall that we need to convert it to a factor variable since it is categorical, not numerical.</p>
<section id="exercise-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h5>
<p>According to the help file, which number corresponds to which sex?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>We can convert a numerical variable a couple of different ways. In Chapter 3, we used the <code>as_factor</code> command. That command works fine, but it doesn’t give you a way to change the levels of the variable. In other words, if we used <code>as_factor</code> here, we would get a factor variable that still contained zeroes and ones.</p>
<p>Instead, we will use the <code>factor</code> command. It allows us to manually relabel the levels. The <code>levels</code> argument requires a vector (with <code>c</code>) of the current levels, and the <code>labels</code> argument requires a vector listing the new names you want to assign, as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>Melanoma <span class="ot">&lt;-</span> Melanoma <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex_fct =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>)))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Melanoma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 205
Columns: 8
$ time      &lt;int&gt; 10, 30, 35, 99, 185, 204, 210, 232, 232, 279, 295, 355, 386,…
$ status    &lt;int&gt; 3, 3, 2, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, …
$ sex       &lt;int&gt; 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, …
$ age       &lt;int&gt; 76, 56, 41, 71, 52, 28, 77, 60, 49, 68, 53, 64, 68, 63, 14, …
$ year      &lt;int&gt; 1972, 1968, 1977, 1968, 1965, 1971, 1972, 1974, 1968, 1971, …
$ thickness &lt;dbl&gt; 6.76, 0.65, 1.34, 2.90, 12.08, 4.84, 5.16, 3.22, 12.88, 7.41…
$ ulcer     &lt;int&gt; 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ sex_fct   &lt;fct&gt; male, male, male, female, male, male, male, female, male, fe…</code></pre>
</div>
</div>
<p>You should check to make sure the first few entries of <code>sex_fct</code> agree with the numbers in the <code>sex</code> variable according to the labels explained in the help file. (If not, it means that you put the <code>levels</code> in one order and the <code>labels</code> in a different order.)</p>
</section>
</section>
<section id="hypothesis2-ex-plots" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="hypothesis2-ex-plots"><span class="header-section-number">11.4.3</span> Make tables or plots to explore the data visually.</h3>
<p>We only have one categorical variable, so we only need a frequency table. Since we are concerned with proportions, we’ll also look at a relative frequency table which the <code>tabyl</code> command provides for free.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(Melanoma, sex_fct) <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sex_fct   n   percent
  female 126 0.6146341
    male  79 0.3853659
   Total 205 1.0000000</code></pre>
</div>
</div>
</section>
</section>
<section id="hypothesis2-logic" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="hypothesis2-logic"><span class="header-section-number">11.5</span> The logic of inference and randomization</h2>
<p>This is a good place to pause and remember why statistical inference is important. There are certainly more females than males in this data set. So why don’t we just show the table above, declare females are more likely to have malignant melanoma, and then go home?</p>
<p>Think back to coin flips. Even though there was a 50% chance of seeing heads, did that mean that exactly half of our flips came up heads? No.&nbsp;We have to acknowledge <em>sampling variability</em>: even if the truth were 50%, when w sample, we could accidentally get more or less than 50%, just by pure chance alone. Perhaps these 205 patients just happen to have more females than average.</p>
<p>The key, then, is to figure out if 61.5% is <em>significantly</em> larger than 50%, or if a number like 61.5% (or one even more extreme) could easily come about from random chance.</p>
<p>As we know from the last chapter, we can run a formal hypothesis test to find out. As we do so, make note of the things that are the same and the things that have changed from the last hypothesis tests you ran. For example, we are not comparing two groups anymore. We have one group of patients, and all we’re doing is measuring the percentage of this group that is female. It’s tempting to think that we’re comparing males and females, but that’s not the case. We are not using sex to divide our data into two groups for the purpose of exploring whether some other variable differs between men and women. We just have one sample. “Female” and “Male” are simply categories in a single categorical variable. Also, because we are only asking about one variable (<code>sex_fct</code>), the mathematical form of the hypotheses will look a little different.</p>
<p>Because this is no longer a question about two variables being independent or associated, the “permuting” idea we’ve been using no longer makes sense. So what does make sense?</p>
<p>It helps to start by figuring out what our null hypothesis is. Remember, our question of interest is whether there is a sex bias in malignant melanoma. In other words, are there more or fewer females than males with malignant melanoma? As this is our research question, it will be the alternative hypothesis. So what is the null? What is the “default” situation in which nothing interesting is going on? Well, there would be no sex bias. In other words, there would be the same number of females and males with malignant melanoma. Or another way of saying that—with respect to the “success” condition of being female that we discussed earlier—is that females comprise 50% of all patients with malignant melanoma.</p>
<p>Okay, given our philosophy about the null hypothesis, let’s take the skeptical position and assume that, indeed, 50% of all malignant melanoma patients in our population are female. Then let’s take a sample of 205 patients. We can’t get exactly 50% females from a sample of 205 (that would be 102.5 females!), so what numbers can we get?</p>
<p>Randomization will tell us. What kind of randomization? As we come across each patient in our sample, there is a 50% chance of them being female. So instead of sampling real patients, what if we just flipped a coin? A simulated coin flip will come up heads just as often as our patients will be female under the assumption of the null.</p>
<p>This brings us full circle, back to the first randomization idea we explored. We can simulate coin flips, graph our results, and calculate a P-value. More specifically, we’ll flip a coin 205 times to represent sampling 205 patients. Then we’ll repeat this procedure a bunch of times and establish a range of plausible percentages that can come about by chance from this procedure. Instead of doing coin flips with the <code>rflip</code> command as we did then, however, we’ll use our new favorite friend, the <code>infer</code> package.</p>
<p>Let’s dive back into the remaining steps of the formal hypothesis test.</p>
</section>
<section id="hypothesis2-ex-hypotheses" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="hypothesis2-ex-hypotheses"><span class="header-section-number">11.6</span> Hypotheses</h2>
<section id="hypothesis2-ex-sample-pop" class="level3" data-number="11.6.1">
<h3 data-number="11.6.1" class="anchored" data-anchor-id="hypothesis2-ex-sample-pop"><span class="header-section-number">11.6.1</span> Identify the sample (or samples) and a reasonable population (or populations) of interest.</h3>
<p>The sample consists of 205 patients from Denmark with malignant melanoma. Our population is presumably all patients with malignant melanoma, although in checking conditions below, we’ll take care to discuss whether patients in Denmark are representative of patients elsewhere.</p>
</section>
<section id="hypothesis2-ex-express-words" class="level3" data-number="11.6.2">
<h3 data-number="11.6.2" class="anchored" data-anchor-id="hypothesis2-ex-express-words"><span class="header-section-number">11.6.2</span> Express the null and alternative hypotheses as contextually meaningful full sentences.</h3>
<p><span class="math inline">\(H_{0}:\)</span> Half of malignant melanoma patients are female.</p>
<p><span class="math inline">\(H_{A}:\)</span> There is a sex bias among patients with malignant melanoma (meaning that females are either over-represented or under-represented).</p>
</section>
<section id="hypothesis2-ex-express-math" class="level3" data-number="11.6.3">
<h3 data-number="11.6.3" class="anchored" data-anchor-id="hypothesis2-ex-express-math"><span class="header-section-number">11.6.3</span> Express the null and alternative hypotheses in symbols (when possible).</h3>
<p><span class="math inline">\(H_{0}: p_{female} = 0.5\)</span></p>
<p><span class="math inline">\(H_{A}: p_{female} \neq 0.5\)</span></p>
</section>
</section>
<section id="hypothesis2-ex-model" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="hypothesis2-ex-model"><span class="header-section-number">11.7</span> Model</h2>
<section id="hypothesis2-ex-sampling-dist-model" class="level3" data-number="11.7.1">
<h3 data-number="11.7.1" class="anchored" data-anchor-id="hypothesis2-ex-sampling-dist-model"><span class="header-section-number">11.7.1</span> Identify the sampling distribution model.</h3>
<p>We will randomize to simulate the sampling distribution.</p>
</section>
<section id="hypothesis2-ex-ht-conditions" class="level3" data-number="11.7.2">
<h3 data-number="11.7.2" class="anchored" data-anchor-id="hypothesis2-ex-ht-conditions"><span class="header-section-number">11.7.2</span> Check the relevant conditions to ensure that model assumptions are met.</h3>
<ul>
<li>Random
<ul>
<li>As mentioned above, these 205 patients are not a random sample of all people with malignant melanoma. We don’t even have any evidence that they are a random sample of melanoma patients in Denmark. Without such evidence, we have to hope that these 205 patients are representative of all patients who have malignant melanoma. Unless there’s something special about Danes in terms of their genetics or diet or something like that, one could imagine that their physiology makes them just as susceptible to melanoma as anyone else. More specifically, though, our question is about females and males getting malignant melanoma. Perhaps there are more female sunbathers in Denmark than in other countries. That might make Danes unrepresentative in terms of the gender balance among melanoma patients. We should be cautious in interpreting any conclusion we might reach in light of these doubts.</li>
</ul></li>
<li>10%
<ul>
<li>Whether in Denmark or not, given that melanoma is a fairly common form of cancer, I assume 205 is less than 10% of all patients with malignant melanoma.</li>
</ul></li>
</ul>
</section>
</section>
<section id="hypothesis2-ex-mechanics" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="hypothesis2-ex-mechanics"><span class="header-section-number">11.8</span> Mechanics</h2>
<section id="hypothesis2-ex-compute-test-stat" class="level3" data-number="11.8.1">
<h3 data-number="11.8.1" class="anchored" data-anchor-id="hypothesis2-ex-compute-test-stat"><span class="header-section-number">11.8.1</span> Compute the test statistic.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>female_prop <span class="ot">&lt;-</span> Melanoma <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">observe</span>(<span class="at">response =</span> sex_fct, <span class="at">success =</span> <span class="st">"female"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">stat =</span> <span class="st">"prop"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>female_prop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: sex_fct (factor)
# A tibble: 1 × 1
   stat
  &lt;dbl&gt;
1 0.615</code></pre>
</div>
</div>
<p>Note: Pay close attention to the difference in the <code>observe</code> command above. Unlike in the last chapter, we don’t have any tildes. That’s because there are not two variables involved. There is only one variable, which <code>observe</code> needs to see as the “response” variable. (Don’t forget to use the factor version <code>sex_fct</code> and not <code>sex</code>!) We still have to specify a “success” condition. Since the hypotheses are about measuring females, we have to tell <code>observe</code> to calculate the proportion of females. Finally, the <code>stat</code> is no longer “diff in props” There are not two proportions with which to find a difference. There is just one proportion, hence, “prop”.</p>
</section>
<section id="hypothesis2-ex-report-test-stat" class="level3" data-number="11.8.2">
<h3 data-number="11.8.2" class="anchored" data-anchor-id="hypothesis2-ex-report-test-stat"><span class="header-section-number">11.8.2</span> Report the test statistic in context (when possible).</h3>
<p>The observed percentage of females with melanoma in our sample is 61.4634146%.</p>
<p>Note: As explained in the last chapter, we have to use <code>pull</code> to pull out the number from the <code>female_prop</code> tibble.</p>
</section>
<section id="hypothesis2-ex-plot-null" class="level3" data-number="11.8.3">
<h3 data-number="11.8.3" class="anchored" data-anchor-id="hypothesis2-ex-plot-null"><span class="header-section-number">11.8.3</span> Plot the null distribution.</h3>
<p>Since this is the first step for which we need the simulated values, it will be convenient to run the simulation here. We’ll need to set the seed as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>melanoma_test <span class="ot">&lt;-</span> Melanoma <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> sex_fct, <span class="at">success =</span> <span class="st">"female"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"point"</span>, <span class="at">p =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"draw"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"prop"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>melanoma_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: sex_fct (factor)
Null Hypothesis: point
# A tibble: 1,000 × 2
   replicate  stat
   &lt;fct&gt;     &lt;dbl&gt;
 1 1         0.444
 2 2         0.585
 3 3         0.551
 4 4         0.502
 5 5         0.561
 6 6         0.493
 7 7         0.527
 8 8         0.488
 9 9         0.512
10 10        0.454
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>This list of proportions is the sampling distribution. It represents possible sample proportions of females with melanoma <strong>under the assumption that the null is true</strong>. In other words, even if the “true” proportion of female melanoma patients were 0.5, these are all values that can result from random samples.</p>
<p>In the <code>hypothesize</code> command, we use “point” to tell <code>infer</code> that we want the null to be centered at the point 0.5. In the <code>generate</code> command, we need to specify the <code>type</code> as “draw” instead of “permute”. We are not shuffling any values here; we are “drawing” values from a probability distribution like coin flips. Everything else in the command is pretty self-explanatory.</p>
<p>The value of our test statistic, <code>female_prop</code>, is 0.6146341. It appears in the right tail:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>melanoma_test <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> female_prop, <span class="at">direction =</span> <span class="st">"two-sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="11-hypothesis_testing_with_randomization_2-web_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Although the line only appears on the right, keep in mind that we are conducting a two-sided test, so we are interested in values more extreme than the red line on the right, but also more extreme than a similarly placed line on the left.</p>
<section id="exercise-3" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h5>
<p>The red line sits at about 0.615. If you were to draw a red line on the above histogram that represented a value equally distant from 0.5, but on the left instead of the right, where would that line be? Do a little arithmetic to figure it out and show your work.</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="hypothesis2-ex-calculate-p" class="level3" data-number="11.8.4">
<h3 data-number="11.8.4" class="anchored" data-anchor-id="hypothesis2-ex-calculate-p"><span class="header-section-number">11.8.4</span> Calculate the P-value.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>melanoma_test <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> female_prop, <span class="at">direction =</span> <span class="st">"two-sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Please be cautious in reporting a p-value of 0. This result is an
approximation based on the number of `reps` chosen in the `generate()` step.
See `?get_p_value()` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>The P-value appears to be zero. Indeed, among the 1000 simulated values, we saw none that exceeded 0.615 and none that were less than 0.385. However, a true P-value can never be zero. If you did millions or billions of simulations (please don’t try!), surely there would be one or two with even more extreme values. In cases when the P-value is really, really tiny, it is traditional to report <span class="math inline">\(P &lt; 0.001\)</span>. It is <strong>incorrect</strong> to say <span class="math inline">\(P = 0\)</span>.</p>
</section>
<section id="hypothesis2-ex-interpret-p" class="level3" data-number="11.8.5">
<h3 data-number="11.8.5" class="anchored" data-anchor-id="hypothesis2-ex-interpret-p"><span class="header-section-number">11.8.5</span> Interpret the P-value as a probability given the null.</h3>
<p><span class="math inline">\(P &lt; 0.001\)</span>. If there were no sex bias in malignant melanoma patients, there would be less than a 0.1% chance of seeing a percentage of females at least as extreme as the one we saw in our data.</p>
<p>Note: Don’t forget to interpret the P-value in a contextually meaningful way. The P-value is the probability under the assumption of the null hypothesis of seeing data at least as extreme as the data we saw. In this context, that means that if we assume 50% of patients are female, it would be extremely rare to see more than 61.5% or less than 38.5% females in a sample of size 205.</p>
</section>
</section>
<section id="hypothesis2-ex-ht-conclusion" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="hypothesis2-ex-ht-conclusion"><span class="header-section-number">11.9</span> Conclusion</h2>
<section id="hypothesis2-ex-stat-conclusion" class="level3" data-number="11.9.1">
<h3 data-number="11.9.1" class="anchored" data-anchor-id="hypothesis2-ex-stat-conclusion"><span class="header-section-number">11.9.1</span> State the statistical conclusion.</h3>
<p>We reject the null hypothesis.</p>
</section>
<section id="hypothesis2-ex-context-conclusion" class="level3" data-number="11.9.2">
<h3 data-number="11.9.2" class="anchored" data-anchor-id="hypothesis2-ex-context-conclusion"><span class="header-section-number">11.9.2</span> State (but do not overstate) a contextually meaningful conclusion.</h3>
<p>There is sufficient evidence that there is a sex bias in patients who suffer from malignant melanoma.</p>
</section>
<section id="hypothesis2-ex-reservations" class="level3" data-number="11.9.3">
<h3 data-number="11.9.3" class="anchored" data-anchor-id="hypothesis2-ex-reservations"><span class="header-section-number">11.9.3</span> Express reservations or uncertainty about the generalizability of the conclusion.</h3>
<p>We have no idea how these patients were sampled. Are these all the patients in Denmark with malignant melanoma over a certain period of time? Were they part of a convenience sample? As a result of our uncertainly about the sampling process, we can’t be sure if the results generalize to a larger population, either in Denmark or especially outside of Denmark.</p>
<section id="exercise-4" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h5>
<p>Can you find on the internet any evidence that females do indeed suffer from malignant melanoma more often than males (not just in Denmark, but anywhere)?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="hypothesis2-ex-errors" class="level3" data-number="11.9.4">
<h3 data-number="11.9.4" class="anchored" data-anchor-id="hypothesis2-ex-errors"><span class="header-section-number">11.9.4</span> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</h3>
<p>As we rejected the null, we run the risk of making a Type I error. If we have made such an error, that would mean that patients with malignant melanoma are equally likely to be male or female, but that we got a sample with an unusual number of female patients.</p>
</section>
</section>
<section id="hypothesis2-your-turn" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="hypothesis2-your-turn"><span class="header-section-number">11.10</span> Your turn</h2>
<p>Determine if the percentage of patients in Denmark with malignant melanoma who also have an ulcerated tumor (measured with the <code>ulcer</code> variable) is significantly different from 50%.</p>
<p>As before, you have the outline of the rubric for inference below. Some of the steps will be the same or similar to steps in the example above. It is perfectly okay to copy and paste R code, making the necessary changes. It is <strong>not</strong> okay to copy and paste text. You need to put everything into your own words.</p>
<p>The template below is exactly the same as in the appendix (<a href="#appendix-rubric">Rubric for inference</a>) up to the part about confidence intervals which we haven’t learned yet.</p>
<section id="exploratory-data-analysis" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h5>
<section id="use-data-documentation-help-files-code-books-google-etc.-to-determine-as-much-as-possible-about-the-data-provenance-and-structure." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="use-data-documentation-help-files-code-books-google-etc.-to-determine-as-much-as-possible-about-the-data-provenance-and-structure.">Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to understand the data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="prepare-the-data-for-analysis.-not-always-necessary." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="prepare-the-data-for-analysis.-not-always-necessary.">Prepare the data for analysis. [Not always necessary.]</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to prepare the data for analysis.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="make-tables-or-plots-to-explore-the-data-visually." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="make-tables-or-plots-to-explore-the-data-visually.">Make tables or plots to explore the data visually.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to make tables or plots.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
</section>
<section id="hypotheses" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="hypotheses">Hypotheses</h5>
<section id="identify-the-sample-or-samples-and-a-reasonable-population-or-populations-of-interest." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="identify-the-sample-or-samples-and-a-reasonable-population-or-populations-of-interest.">Identify the sample (or samples) and a reasonable population (or populations) of interest.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="express-the-null-and-alternative-hypotheses-as-contextually-meaningful-full-sentences." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="express-the-null-and-alternative-hypotheses-as-contextually-meaningful-full-sentences.">Express the null and alternative hypotheses as contextually meaningful full sentences.</h6>
<div class="answer">
<p><span class="math inline">\(H_{0}:\)</span> Null hypothesis goes here.</p>
<p><span class="math inline">\(H_{A}:\)</span> Alternative hypothesis goes here.</p>
</div>
</section>
<section id="express-the-null-and-alternative-hypotheses-in-symbols-when-possible." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="express-the-null-and-alternative-hypotheses-in-symbols-when-possible.">Express the null and alternative hypotheses in symbols (when possible).</h6>
<div class="answer">
<p><span class="math inline">\(H_{0}: math\)</span></p>
<p><span class="math inline">\(H_{A}: math\)</span></p>
</div>
</section>
</section>
<section id="model" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="model">Model</h5>
<section id="identify-the-sampling-distribution-model." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="identify-the-sampling-distribution-model.">Identify the sampling distribution model.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.">Check the relevant conditions to ensure that model assumptions are met.</h6>
<div class="answer">
<p>Please write up your answer here. (Some conditions may require R code as well.)</p>
</div>
</section>
</section>
<section id="mechanics" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="mechanics">Mechanics</h5>
<section id="compute-the-test-statistic." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="compute-the-test-statistic.">Compute the test statistic.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to compute the test statistic.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="report-the-test-statistic-in-context-when-possible." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="report-the-test-statistic-in-context-when-possible.">Report the test statistic in context (when possible).</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="plot-the-null-distribution." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="plot-the-null-distribution.">Plot the null distribution.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to simulate the null distribution.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run 1000 simulations like in the earlier example.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to plot the null distribution.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="calculate-the-p-value." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="calculate-the-p-value.">Calculate the P-value.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to calculate the P-value.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="interpret-the-p-value-as-a-probability-given-the-null." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="interpret-the-p-value-as-a-probability-given-the-null.">Interpret the P-value as a probability given the null.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
<section id="conclusion" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="conclusion">Conclusion</h5>
<section id="state-the-statistical-conclusion." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="state-the-statistical-conclusion.">State the statistical conclusion.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="state-but-do-not-overstate-a-contextually-meaningful-conclusion." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="state-but-do-not-overstate-a-contextually-meaningful-conclusion.">State (but do not overstate) a contextually meaningful conclusion.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="express-reservations-or-uncertainty-about-the-generalizability-of-the-conclusion." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="express-reservations-or-uncertainty-about-the-generalizability-of-the-conclusion.">Express reservations or uncertainty about the generalizability of the conclusion.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="identify-the-possibility-of-either-a-type-i-or-type-ii-error-and-state-what-making-such-an-error-means-in-the-context-of-the-hypotheses." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="identify-the-possibility-of-either-a-type-i-or-type-ii-error-and-state-what-making-such-an-error-means-in-the-context-of-the-hypotheses.">Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
</section>
</section>
<section id="hypothesis2-conclusion" class="level2" data-number="11.11">
<h2 data-number="11.11" class="anchored" data-anchor-id="hypothesis2-conclusion"><span class="header-section-number">11.11</span> Conclusion</h2>
<p>Now you have seen two fully-worked examples of hypothesis tests using randomization, and you have created two more examples on your own. Hopefully, the logic of inference and the process of running a formal hypothesis test are starting to make sense.</p>
<p>Keep in mind that the outline of steps will not change. However, the way each step is carried out will vary from problem to problem. Not only does the context change (one example involved sex discrimination, the other melanoma patients), but the statistics you compute also change (one example compared proportions from two samples and the other only had one proportion from a single sample). Pay close attention to the research question and the data that will be used to answer that question. That will be the only information you have to help you know which hypothesis test applies.</p>
<section id="hypothesis2-prep" class="level3" data-number="11.11.1">
<h3 data-number="11.11.1" class="anchored" data-anchor-id="hypothesis2-prep"><span class="header-section-number">11.11.1</span> Preparing and submitting your assignment</h3>
<ol type="1">
<li>From the “Run” menu, select “Restart R and Run All Chunks”.</li>
<li>Deal with any code errors that crop up. Repeat steps 1–-2 until there are no more code errors.</li>
<li>Spell check your document by clicking the icon with “ABC” and a check mark.</li>
<li>Hit the “Preview” button one last time to generate the final draft of the <code>.nb.html</code> file.</li>
<li>Proofread the HTML file carefully. If there are errors, go back and fix them, then repeat steps 1–5 again.</li>
</ol>
<p>If you have completed this chapter as part of a statistics course, follow the directions you receive from your professor to submit your assignment.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10-hypothesis_testing_with_randomization_1-web.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 1</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12-confidence_intervals-web.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>