<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Statistics: an integrated textbook and workbook using R - 12&nbsp; Confidence intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-normal_models-web.html" rel="next">
<link href="./11-hypothesis_testing_with_randomization_2-web.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-confidence_intervals-web.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics: an integrated textbook and workbook using R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro_to_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-using_r_markdown-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Using R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-categorical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-numerical_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulating_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulating data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-correlation-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regression-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-intro_to_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-intro_to_randomization_2-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-hypothesis_testing_with_randomization_1-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesis_testing_with_randomization_2-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-confidence_intervals-web.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-normal_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Normal models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-sampling_distribution_models-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Sampling distribution models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-inference_for_one_proportion-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Inference for one proportion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-inference_for_two_proportions-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for two proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-chi_square_goodness_of_fit-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chi-square goodness-of-fit test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-chi_square_test_for_independence-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Chi-square test for independence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-inference_for_one_mean-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for one mean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-inference_for_paired_data-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for paired data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inference_for_two_independent_means-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for two independent means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-anova-web.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rubric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rubric for inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Concordance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Concordance with <em>Introduction to Modern Statistics</em> (IMS)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#functions-introduced-in-this-chapter" id="toc-functions-introduced-in-this-chapter" class="nav-link active" data-scroll-target="#functions-introduced-in-this-chapter">Functions introduced in this chapter</a></li>
  <li><a href="#ci-intro" id="toc-ci-intro" class="nav-link" data-scroll-target="#ci-intro"><span class="header-section-number">12.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#ci-install" id="toc-ci-install" class="nav-link" data-scroll-target="#ci-install"><span class="header-section-number">12.1.1</span> Install new packages</a></li>
  <li><a href="#ci-download" id="toc-ci-download" class="nav-link" data-scroll-target="#ci-download"><span class="header-section-number">12.1.2</span> Download the R notebook file</a></li>
  <li><a href="#ci-restart" id="toc-ci-restart" class="nav-link" data-scroll-target="#ci-restart"><span class="header-section-number">12.1.3</span> Restart R and run all chunks</a></li>
  </ul></li>
  <li><a href="#ci-load" id="toc-ci-load" class="nav-link" data-scroll-target="#ci-load"><span class="header-section-number">12.2</span> Load packages</a></li>
  <li><a href="#ci-boot" id="toc-ci-boot" class="nav-link" data-scroll-target="#ci-boot"><span class="header-section-number">12.3</span> Bootstrapping</a></li>
  <li><a href="#ci-computing-boot" id="toc-ci-computing-boot" class="nav-link" data-scroll-target="#ci-computing-boot"><span class="header-section-number">12.4</span> Computing a bootstrap sampling distribution</a></li>
  <li><a href="#ci-ci" id="toc-ci-ci" class="nav-link" data-scroll-target="#ci-ci"><span class="header-section-number">12.5</span> Confidence intervals</a></li>
  <li><a href="#ci-conditions" id="toc-ci-conditions" class="nav-link" data-scroll-target="#ci-conditions"><span class="header-section-number">12.6</span> Conditions</a></li>
  <li><a href="#ci-rubric" id="toc-ci-rubric" class="nav-link" data-scroll-target="#ci-rubric"><span class="header-section-number">12.7</span> Rubric for confidence intervals</a></li>
  <li><a href="#ci-ex" id="toc-ci-ex" class="nav-link" data-scroll-target="#ci-ex"><span class="header-section-number">12.8</span> Example</a>
  <ul class="collapse">
  <li><a href="#ci-ex-conditions" id="toc-ci-ex-conditions" class="nav-link" data-scroll-target="#ci-ex-conditions"><span class="header-section-number">12.8.1</span> Check the relevant conditions to ensure that model assumptions are met.</a></li>
  <li><a href="#ci-ex-calcaulte" id="toc-ci-ex-calcaulte" class="nav-link" data-scroll-target="#ci-ex-calcaulte"><span class="header-section-number">12.8.2</span> Calculate and graph the confidence interval.</a></li>
  <li><a href="#ci-ex-interpret" id="toc-ci-ex-interpret" class="nav-link" data-scroll-target="#ci-ex-interpret"><span class="header-section-number">12.8.3</span> State (but do not overstate) a contextually meaningful interpretation.</a></li>
  <li><a href="#ci-ex-ci-ht" id="toc-ci-ex-ci-ht" class="nav-link" data-scroll-target="#ci-ex-ci-ht"><span class="header-section-number">12.8.4</span> If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.</a></li>
  <li><a href="#ci-ex-effect" id="toc-ci-ex-effect" class="nav-link" data-scroll-target="#ci-ex-effect"><span class="header-section-number">12.8.5</span> When comparing two groups, comment on the effect size and the practical significance of the result.</a></li>
  </ul></li>
  <li><a href="#ci-your-turn" id="toc-ci-your-turn" class="nav-link" data-scroll-target="#ci-your-turn"><span class="header-section-number">12.9</span> Your turn</a></li>
  <li><a href="#ci-interpret" id="toc-ci-interpret" class="nav-link" data-scroll-target="#ci-interpret"><span class="header-section-number">12.10</span> Interpreting confidence intervals</a></li>
  <li><a href="#ci-conclusion" id="toc-ci-conclusion" class="nav-link" data-scroll-target="#ci-conclusion"><span class="header-section-number">12.11</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#ci-prep" id="toc-ci-prep" class="nav-link" data-scroll-target="#ci-prep"><span class="header-section-number">12.11.1</span> Preparing and submitting your assignment</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="ci" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<!-- Please don't mess with the next few lines! -->
<style>h5{font-size:2em;color:#0000FF}h6{font-size:1.5em;color:#0000FF}div.answer{margin-left:5%;border:1px solid #0000FF;border-left-width:10px;padding:25px} div.summary{background-color:rgba(30,144,255,0.1);border:3px double #0000FF;padding:25px}</style>
<p style="color:#ffffff">
2.0
</p>
<!-- Please don't mess with the previous few lines! -->
<section id="functions-introduced-in-this-chapter" class="level3 unnumbered summary">
<h3 class="unnumbered anchored" data-anchor-id="functions-introduced-in-this-chapter">Functions introduced in this chapter</h3>
<p><code>get_confidence_interval</code>, <code>shade_confidence_interval</code>, <code>fct_collapse</code></p>
</section>
<section id="ci-intro" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="ci-intro"><span class="header-section-number">12.1</span> Introduction</h2>
<p>Sampling variability means that we can never trust a single sample to identify a population parameter exactly. Instead of simply trusting a point estimate, we can look at the entire sampling distribution to create an interval of plausible values called a confidence interval. By making our intervals wide enough, we hope to have some chance of capturing the true population value. Like hypothesis tests, confidence intervals are a form of inference because they use a sample to deduce something about the population. Along the way, we will also learn about a new form of randomization called <em>bootstrapping</em>.</p>
<section id="ci-install" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="ci-install"><span class="header-section-number">12.1.1</span> Install new packages</h3>
<p>There are no new packages used in this chapter.</p>
</section>
<section id="ci-download" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="ci-download"><span class="header-section-number">12.1.2</span> Download the R notebook file</h3>
<p>Check the upper-right corner in RStudio to make sure you’re in your <code>intro_stats</code> project. Then click on the following link to download this chapter as an R notebook file (<code>.Rmd</code>).</p>
<p><a href="https://vectorposse.github.io/intro_stats/chapter_downloads/12-confidence_intervals.Rmd" download="">https://vectorposse.github.io/intro_stats/chapter_downloads/12-confidence_intervals.Rmd</a></p>
<p>Once the file is downloaded, move it to your project folder in RStudio and open it there.</p>
</section>
<section id="ci-restart" class="level3" data-number="12.1.3">
<h3 data-number="12.1.3" class="anchored" data-anchor-id="ci-restart"><span class="header-section-number">12.1.3</span> Restart R and run all chunks</h3>
<p>In RStudio, select “Restart R and Run All Chunks” from the “Run” menu.</p>
</section>
</section>
<section id="ci-load" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="ci-load"><span class="header-section-number">12.2</span> Load packages</h2>
<p>We load the standard <code>tidyverse</code>, <code>janitor</code>, and <code>infer</code> packages. We’ll also need the <code>openintro</code> package later in the chapter for the <code>hsb2</code> and the <code>smoking</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: airports
Loading required package: cherryblossom
Loading required package: usdata</code></pre>
</div>
</div>
</section>
<section id="ci-boot" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="ci-boot"><span class="header-section-number">12.3</span> Bootstrapping</h2>
<p>Imagine you obtain a random sample of 200 high school seniors from across the U.S. Suppose 32 of them attend private school. As a sample statistic, we have</p>
<p><span class="math display">\[
\hat{p} = 32/200 = 0.16
\]</span> In other words, 16% of the students in the sample attended private school.</p>
<p>If our sample is representative, we might guess that the true population parameter <span class="math inline">\(p\)</span> is also close to 0.16, but we’re not really sure:</p>
<p><span class="math display">\[
p \approx 0.16?
\]</span></p>
<p>And what about the sampling variability? A few chapters ago, we flipped coins. A “weighted” coin flipped 200 times can give us a “new” (fake) sample, and doing that a thousand times (or even more) can give us a lot of new samples to see what range of values is possible. But what would we use as the probability of heads for the weighted coin? It would be a bad idea to use 0.16 because that would assume that the population proportion agreed exactly with the one sample we happen to have. It worked in a hypothesis test because we had a value of <span class="math inline">\(p\)</span> we assumed was true in the guise of a null hypothesis. But in general, if I simply want to estimate a population parameter with a sample statistic, I have no such information to use. So coin flipping is out.</p>
<p>An alternative that is available to us is a procedure called <em>bootstrapping</em>. The idea sounds weird, but it’s pretty simple: instead of building fake samples, what if we tried to build a fake population? And then, what if we took repeated samples from it?</p>
<p>How would we build a fake population? Imagine making many, many copies of our sample until we had thousands or even millions of students. In fact, we can think of an infinite number of copies of our sample if we want. Sure, this fake population isn’t exactly like the real population of all high school seniors. But if our sample is representative, we might hope that lots of copies of our sample would approximate the population we care about.</p>
<p>Computationally, it’s a lot of work to copy our sample thousands or millions of times. And we certainly can’t work with an infinite number of copies. Fortunately, we can use a shortcut. It’s called <em>sampling with replacement</em>.</p>
<p>Normal sampling is usually <em>without replacement</em>, meaning that once we have sampled an individual, they are not eligible to be sampled again. We don’t want to survey Billy and then later in our study, survey Billy again.</p>
<p>In sampling <em>with</em> replacement, we put Billy back in the pool and make him eligible to be sampled again. This is the same thing as having access to an infinite population. Remember that our fake population is just many, many copies of our sample. So in that fake population, there are many, many Billy clones that could end up in our sample. So rather than cloning Billy many, many times, let’s just put Billy back in the group any time he’s sampled.</p>
<p>We need to see this in action. We have a random sample of 200 students obtained by the National Center of Education Statistics in their “High School and Beyond” survey. This is stored in the <code>hsb2</code> data set from the <code>openintro</code> package. Here are the school types for these students, stored in the variable <code>schtyp</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>hsb2<span class="sc">$</span>schtyp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] public  public  public  public  public  public  public  public  public 
 [10] public  public  public  public  public  public  public  public  private
 [19] public  public  public  public  public  public  public  public  public 
 [28] private private public  public  public  private public  private public 
 [37] private public  public  public  private private public  public  public 
 [46] public  public  public  private public  public  public  public  private
 [55] public  public  public  public  private public  private public  public 
 [64] public  private public  public  public  public  public  public  public 
 [73] public  public  public  public  public  public  public  public  public 
 [82] public  private public  public  public  public  public  public  public 
 [91] public  public  public  public  public  public  public  public  public 
[100] private public  public  public  public  public  public  public  public 
[109] private private public  public  public  public  private public  public 
[118] public  public  public  private public  public  public  public  public 
[127] public  public  public  public  public  public  public  public  public 
[136] public  private public  public  private public  public  public  public 
[145] public  private public  private public  public  public  public  public 
[154] public  public  public  public  public  public  public  public  public 
[163] private public  public  public  public  public  private public  public 
[172] public  public  public  public  public  public  public  public  public 
[181] public  private public  public  public  public  public  public  private
[190] public  public  private private public  private private public  private
[199] public  public 
Levels: public private</code></pre>
</div>
</div>
<p>Let’s sample an individual from our sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">6</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] public
Levels: public private</code></pre>
</div>
</div>
<p>That was one of the public school students from among the 200 students in our sample. Here’s another one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] private
Levels: public private</code></pre>
</div>
</div>
<p>That was one of the private school students.</p>
<p>We can do this 200 times. Now, if we sample <em>without</em> replacement, all we get back are the original students, just listed in a different order. Think about why: we’re just picking one student at a time. But since they don’t get replaced, eventually, every student will get chosen. We’re choosing 200 students, but there are only 200 students from which to choose.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sample_without_replacement1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">200</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>sample_without_replacement1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] public  public  public  public  public  public  public  public  public 
 [10] public  public  public  public  public  public  public  private public 
 [19] public  public  public  public  public  public  public  public  public 
 [28] public  public  private public  public  public  public  public  public 
 [37] public  public  public  public  public  public  public  private public 
 [46] public  public  public  public  private private private public  public 
 [55] private private public  public  public  public  public  public  private
 [64] public  public  private public  public  public  public  public  public 
 [73] public  public  public  public  public  public  public  public  public 
 [82] public  public  public  public  public  public  public  public  public 
 [91] public  public  public  public  public  public  public  public  public 
[100] public  public  private public  public  public  public  public  public 
[109] public  public  public  public  public  public  public  public  public 
[118] public  public  public  private public  public  private public  public 
[127] private private public  public  public  public  private public  private
[136] private public  public  public  public  public  public  public  public 
[145] public  public  public  public  public  public  public  public  private
[154] public  public  public  public  public  private public  private private
[163] public  public  public  public  private public  public  private public 
[172] private private public  public  public  public  public  public  public 
[181] public  private public  private public  public  public  private private
[190] public  public  public  public  public  public  public  public  private
[199] public  private
Levels: public private</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(sample_without_replacement1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sample_without_replacement1   n percent
                      public 168    0.84
                     private  32    0.16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">9</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sample_without_replacement2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">200</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sample_without_replacement2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] public  public  public  private public  private public  private public 
 [10] public  public  private private private private private public  public 
 [19] private public  public  public  public  public  public  public  public 
 [28] public  public  public  public  public  public  public  public  public 
 [37] public  public  public  public  public  public  public  private public 
 [46] public  public  public  public  private public  private public  public 
 [55] public  private public  public  public  public  public  public  public 
 [64] private public  public  public  public  public  public  public  public 
 [73] public  public  public  public  private public  public  public  public 
 [82] private private public  public  public  public  public  public  private
 [91] public  private public  public  public  private public  public  public 
[100] public  public  private private public  public  public  public  public 
[109] public  private public  public  private public  private public  public 
[118] public  public  public  public  public  private public  public  public 
[127] public  public  public  public  public  public  public  public  public 
[136] public  public  public  public  public  public  private public  public 
[145] public  private public  public  public  public  public  public  public 
[154] public  public  public  public  public  public  public  public  private
[163] private public  public  public  public  public  public  public  public 
[172] public  public  public  public  public  public  public  public  public 
[181] private public  public  public  public  public  private public  public 
[190] public  public  public  public  public  public  public  public  public 
[199] public  public 
Levels: public private</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(sample_without_replacement2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sample_without_replacement2   n percent
                      public 168    0.84
                     private  32    0.16</code></pre>
</div>
</div>
<p>The two lists above consist of the same 200 students, just drawn in a different order.</p>
<p>On the other hand, if we sample <em>with</em> replacement, then students can get chosen more than once. (Remember, we’re equating “getting chosen more than once” with “sampling from an infinite population and choosing a clone”.) Now, the number of private school students we see might not be 32.</p>
<p>Each of the following samples is called a <em>bootstrap sample</em>. Notice that we’ve added the argument <code>replace = TRUE</code> to the <code>sample</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">10</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sample_with_replacement1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">200</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>sample_with_replacement1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] private public  public  public  public  private public  public  public 
 [10] public  public  public  public  public  public  public  public  public 
 [19] private public  public  public  public  private private private public 
 [28] public  private public  public  public  private public  public  public 
 [37] public  public  public  public  public  public  private public  public 
 [46] public  public  public  public  public  public  private public  public 
 [55] public  public  public  public  public  public  public  public  public 
 [64] public  public  private public  private public  public  public  private
 [73] public  public  public  public  public  public  public  public  public 
 [82] public  public  public  public  private public  public  public  public 
 [91] public  private public  private public  private public  public  public 
[100] public  public  public  private private public  public  public  public 
[109] public  public  public  public  public  private private public  public 
[118] private public  public  private public  public  private public  public 
[127] public  public  public  private private private public  public  private
[136] public  public  public  public  public  public  public  public  public 
[145] public  public  public  public  public  public  public  public  public 
[154] public  public  public  public  public  public  public  private public 
[163] public  public  public  private private public  private private private
[172] public  public  public  public  public  public  private public  public 
[181] public  public  public  public  public  public  private public  public 
[190] public  public  public  public  public  public  public  public  public 
[199] public  public 
Levels: public private</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(sample_with_replacement1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sample_with_replacement1   n percent
                   public 164    0.82
                  private  36    0.18</code></pre>
</div>
</div>
<p>That bootstrap sample proportion is 0.18, not 0.16.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sample_with_replacement2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(hsb2<span class="sc">$</span>schtyp, <span class="at">size =</span> <span class="dv">200</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>sample_with_replacement2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] public  public  public  public  public  private public  public  private
 [10] public  public  private public  public  public  public  public  public 
 [19] public  public  public  public  public  public  public  public  public 
 [28] public  public  public  public  public  public  public  public  public 
 [37] public  public  public  public  public  public  public  public  public 
 [46] public  public  public  public  public  public  public  private public 
 [55] public  public  public  public  public  public  public  public  public 
 [64] public  public  public  public  public  public  public  public  public 
 [73] public  public  public  public  private public  public  public  public 
 [82] public  private private public  public  private public  public  public 
 [91] public  private public  public  public  public  private public  private
[100] public  public  private public  public  public  public  public  public 
[109] public  public  private public  public  private public  public  public 
[118] private private public  public  public  public  private public  private
[127] public  private public  private public  public  public  private public 
[136] private public  public  public  private private private public  private
[145] public  public  private public  public  private public  public  public 
[154] private private public  public  public  public  public  public  private
[163] private public  public  public  public  public  private public  private
[172] public  public  public  private private public  private public  public 
[181] public  public  public  public  public  public  public  public  public 
[190] public  private public  private public  public  public  private public 
[199] public  public 
Levels: public private</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(sample_with_replacement2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sample_with_replacement2   n percent
                   public 160     0.8
                  private  40     0.2</code></pre>
</div>
</div>
<p>That bootstrap sample proportion is 0.2.</p>
<p>Now we’re getting some sampling variability!</p>
<p>If we do this many, many times, we get a whole collection of sample proportions. The distribution of all those sample proportions, obtained with bootstrap samples (samples drawn with replacement), is called the <em>bootstrap sampling distribution</em>.</p>
</section>
<section id="ci-computing-boot" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="ci-computing-boot"><span class="header-section-number">12.4</span> Computing a bootstrap sampling distribution</h2>
<p>The <code>infer</code> package can compute bootstrap samples and, hence, produce a bootstrap sampling distribution. The code looks a whole like the code you already know for hypothesis testing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>private_boot <span class="ot">&lt;-</span> hsb2 <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> schtyp, <span class="at">success =</span> <span class="st">"private"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"prop"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>private_boot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: schtyp (factor)
# A tibble: 1,000 × 2
   replicate  stat
       &lt;int&gt; &lt;dbl&gt;
 1         1 0.185
 2         2 0.185
 3         3 0.15 
 4         4 0.135
 5         5 0.145
 6         6 0.175
 7         7 0.15 
 8         8 0.195
 9         9 0.18 
10        10 0.185
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>We simply changed the <code>type</code> to “bootstrap”.</p>
<p>Now we visualize like normal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>private_boot <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-confidence_intervals-web_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>(We can change the number of bins if we want, but this number looks pretty good.)</p>
</section>
<section id="ci-ci" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="ci-ci"><span class="header-section-number">12.5</span> Confidence intervals</h2>
<p>The histogram above simulates what might happen if we took many samples from our infinite “fake” population consisting of many copies of our original, actual sample data. On the lower end, we might see something like 8% private school students. On the upper end, we could see 25% or more private school students.</p>
<p>In the chapter about numerical data, we computed the IQR (interquartile range), which was the difference between the 25th percentile and the 75th percentile. The IQR was then the range of the middle 50% of the data. Let’s use <code>infer</code> tools to calculate the middle 50% of the above distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>private_50 <span class="ot">&lt;-</span> private_boot <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.5</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>private_50</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     0.14    0.175</code></pre>
</div>
</div>
<p>The middle 50% ranges from 14% up to 17.5%. We can also visualize this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>private_boot <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualise</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> private_50)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-confidence_intervals-web_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In other words, when we go out to gather a sample from our (fake infinite) population of high school seniors, about half of the time, we expect the percentage of private students to be somewhere between 14% and 17.5%. The other half of the time, we will sample a value outside that range.</p>
<p>This is a confidence interval. More specifically, this is a 50% confidence interval. This is the range of values we expect sample proportions to be in approximately half of the samples we might gather from our (fake infinite) population.</p>
<p>Now don’t forget the goal. What we are really trying to find is the value <span class="math inline">\(p\)</span>, the true population parameter. We want to know what proportion of high school seniors attend private school in the whole population of all high school seniors in the U.S.</p>
<p>For mathematical reasons that are outside the scope of this course, it turns out that the sampling variability in the bootstrap distribution around <span class="math inline">\(\hat{p}\)</span> is very similar to the sampling variability of the sample proportion <span class="math inline">\(\hat{p}\)</span> around the true value <span class="math inline">\(p\)</span>. We bootstrapped our way to the picture above using one actual sample with about 16% private school students. A different sample of high school seniors would give us different bootstrap samples, producing a slightly different bootstrap distribution from the one above. But it, too, will have a shaded region like the histogram above. Every actual sample we might obtain in the real world would give us a bootstrap distribution with a different shaded region. But the amazing fact is this: about half of those shaded regions will actually contain the true population parameter <span class="math inline">\(p\)</span>.</p>
<p>Think about the value <span class="math inline">\(p\)</span> like a fish hidden in a murky lake. The sample proportion <span class="math inline">\(\hat{p}\)</span> is our attempt at fishing. We drop a hook down at the value <span class="math inline">\(\hat{p}\)</span> and pull it right back up. It’s not very likely that we caught the fish, although we hope that we were close. Alas, the sample proportion is almost never exactly equal to the true proportion <span class="math inline">\(p\)</span>. But what if we cast a net instead? That net is the shaded range of values in our confidence interval. That range of values might catch the fish.</p>
<p>The difference between statistics and fishing is that, in the latter, when we pull up the net, we can see if we successfully caught the fish. In the former, all we can say is that there is some probability that the net caught the fish, but you’re not able to look inside the net to know for sure.</p>
<p>So the confidence interval we created above might have caught the true value <span class="math inline">\(p\)</span>. But then again, it might not have. There’s only a 50% chance we captured the true value in the range 14% to 17.5% that we computed from our specific sample with its accompanying bootstrap samples. Most researchers would be displeased with only a 50% success rate. So can we do better?</p>
<p>How much better do we want to do? This is a subjective question with no definitive answer. Many people say they want to be 95% confident that the confidence interval they build will capture the true population parameter. Let’s modify our code to do that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>private_95 <span class="ot">&lt;-</span> private_boot <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>private_95</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     0.11    0.215</code></pre>
</div>
</div>
<p>The middle 95% ranges from 11% up to 21.5%. We can also visualize this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>private_boot <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualise</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> private_95)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-confidence_intervals-web_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The interpretation is that when you go collect many samples, the confidence intervals you produce using the bootstrap procedure described above will capture the true population proportion 95% of the time.</p>
<section id="exercise-1" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h5>
<p>Why is a 95% confidence interval wider than a 50% confidence interval? In other words, why should our desire to be 95% confident in capturing the true value of <span class="math inline">\(p\)</span> result in an interval that is wider than if we only wanted to be 50% confident?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</section>
<section id="exercise-2" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h5>
<p>Being more confident seems like a good thing. In fact, we might want a 99% confidence interval. Compute and visualize a 99% confidence interval for proportion of private school students.</p>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to compute a 99% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to visualize a 99% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-3" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h5>
<p>Can you think of any downside to using higher and higher confidence levels? As a hint, think about the following completely true sentence: “I am 100% confident that the true proportion of high school seniors attending private school is somewhere between 0% and 100%.”</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>While 50% is clearly too low for a confidence level, as seen above, there is no particular reason that we need to compute a 95% confidence interval either. There is some consensus in the scientific community here: 95% has evolved to become a generally agreed-upon standard. But we could compute a 90% confidence interval or a 99% confidence interval (as you did above), or any other type of interval. Having said that, if you choose other intervals besides these three, people might wonder if you’re up to something.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
</section>
<section id="ci-conditions" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="ci-conditions"><span class="header-section-number">12.6</span> Conditions</h2>
<p>Don’t forget that there are always assumptions we make when relying on any kind of statistical inference. Before computing a confidence interval for a proportion, we must verify that certain conditions are satisfied. But these conditions are not new. We already know from hypothesis testing what is required for good inference from a sample. These are the “Random” and the “10%” conditions.</p>
<ul>
<li>Random
<ul>
<li>The sample must be random (or hopefully representative).</li>
</ul></li>
<li>10%
<ul>
<li>The sample size must be less than 10% of the size of the population.</li>
</ul></li>
</ul>
<p>Both conditions are met for the data in the High School and Beyond survey.</p>
</section>
<section id="ci-rubric" class="level2" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="ci-rubric"><span class="header-section-number">12.7</span> Rubric for confidence intervals</h2>
<p>Typically, you will be asked to report a confidence interval after performing a hypothesis test. Whereas a hypothesis test gives you a “decision criterion” (using data to make a decision to reject the null or fail to reject the null), a confidence interval gives you an estimate of the “effect size” (a range of plausible values for the population parameter).</p>
<p>As such, there is a section in the <a href="#appendix-rubric">Rubric for inference</a> that shows the steps of calculating and reporting a confidence interval. They are as follows:</p>
<ol type="1">
<li>Check the relevant conditions to ensure that model assumptions are met.</li>
<li>Calculate and graph the confidence interval.</li>
<li>State (but do not overstate) a contextually meaningful interpretation.</li>
<li>If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.</li>
<li>When comparing two groups, comment on the effect size and the practical significance of the result.</li>
</ol>
</section>
<section id="ci-ex" class="level2" data-number="12.8">
<h2 data-number="12.8" class="anchored" data-anchor-id="ci-ex"><span class="header-section-number">12.8</span> Example</h2>
<p>Here is a worked example. (Unless otherwise stated, we always use a 95% confidence level.)</p>
<p>Some of the students in the “High School and Beyond” survey attended vocational programs. This data is stored in the <code>prog</code> variable. Using a confidence interval, estimate what percentage of all high school seniors attend vocational programs.</p>
<p>We will need to do a little data cleaning before we can address this question. There are actually three types of programs: “general”, “academic”, and “vocational”. The <code>infer</code> commands will only work when a categorical variable has two levels. We are thinking of “general” and “academic” together as more like a combined “other” category. We can fix this by creating a new factor variable with <code>mutate</code>. Inside that <code>mutate</code>, we will use the <code>fct_collapse</code> function to collapse two of the levels into one as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>hsb2 <span class="ot">&lt;-</span> hsb2 <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">prog2 =</span> <span class="fu">fct_collapse</span>(prog,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">vocational =</span> <span class="st">"vocational"</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">other =</span> <span class="fu">c</span>(<span class="st">"general"</span>, <span class="st">"academic"</span>)))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(hsb2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 200
Columns: 12
$ id      &lt;int&gt; 70, 121, 86, 141, 172, 113, 50, 11, 84, 48, 75, 60, 95, 104, 3…
$ gender  &lt;chr&gt; "male", "female", "male", "male", "male", "male", "male", "mal…
$ race    &lt;chr&gt; "white", "white", "white", "white", "white", "white", "african…
$ ses     &lt;fct&gt; low, middle, high, high, middle, middle, middle, middle, middl…
$ schtyp  &lt;fct&gt; public, public, public, public, public, public, public, public…
$ prog    &lt;fct&gt; general, vocational, general, vocational, academic, academic, …
$ read    &lt;int&gt; 57, 68, 44, 63, 47, 44, 50, 34, 63, 57, 60, 57, 73, 54, 45, 42…
$ write   &lt;int&gt; 52, 59, 33, 44, 52, 52, 59, 46, 57, 55, 46, 65, 60, 63, 57, 49…
$ math    &lt;int&gt; 41, 53, 54, 47, 57, 51, 42, 45, 54, 52, 51, 51, 71, 57, 50, 43…
$ science &lt;int&gt; 47, 63, 58, 53, 53, 63, 53, 39, 58, 50, 53, 63, 61, 55, 31, 50…
$ socst   &lt;int&gt; 57, 61, 31, 56, 61, 61, 61, 36, 51, 51, 61, 61, 71, 46, 56, 56…
$ prog2   &lt;fct&gt; other, vocational, other, vocational, other, other, other, oth…</code></pre>
</div>
</div>
<p>Inspect the variables <code>prog</code> and <code>prog2</code> above to make sure that the recoding was successful. Then be sure to use <code>prog2</code> and not <code>prog</code> everywhere.</p>
<section id="ci-ex-conditions" class="level3" data-number="12.8.1">
<h3 data-number="12.8.1" class="anchored" data-anchor-id="ci-ex-conditions"><span class="header-section-number">12.8.1</span> Check the relevant conditions to ensure that model assumptions are met.</h3>
<ul>
<li>Random
<ul>
<li>The sample is a random sample of high school seniors from the U.S. as the survey was conducted by the National Center of Education Statistics, a reputable government organization.</li>
</ul></li>
<li>10%
<ul>
<li>The sample size is 200, which is much less than 10% of the population of all U.S. high school seniors.</li>
</ul></li>
</ul>
</section>
<section id="ci-ex-calcaulte" class="level3" data-number="12.8.2">
<h3 data-number="12.8.2" class="anchored" data-anchor-id="ci-ex-calcaulte"><span class="header-section-number">12.8.2</span> Calculate and graph the confidence interval.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>vocational_boot <span class="ot">&lt;-</span> hsb2 <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> prog2, <span class="at">success =</span> <span class="st">"vocational"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"prop"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>vocational_boot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: prog2 (factor)
# A tibble: 1,000 × 2
   replicate  stat
       &lt;int&gt; &lt;dbl&gt;
 1         1 0.335
 2         2 0.25 
 3         3 0.17 
 4         4 0.24 
 5         5 0.245
 6         6 0.245
 7         7 0.2  
 8         8 0.24 
 9         9 0.265
10        10 0.25 
# ℹ 990 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>vocational_ci <span class="ot">&lt;-</span> vocational_boot <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>vocational_ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     0.19     0.31</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>vocational_boot <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> vocational_ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-confidence_intervals-web_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="ci-ex-interpret" class="level3" data-number="12.8.3">
<h3 data-number="12.8.3" class="anchored" data-anchor-id="ci-ex-interpret"><span class="header-section-number">12.8.3</span> State (but do not overstate) a contextually meaningful interpretation.</h3>
<p>We are 95% confident that the true percentage of U.S. high school seniors who attend a vocational program is captured in the interval (19%, 31%).</p>
<p>Note: we use inline code to grab the values of the endpoints of the confidence interval. We also multiply by 100 to report percentages instead of proportions.</p>
</section>
<section id="ci-ex-ci-ht" class="level3" data-number="12.8.4">
<h3 data-number="12.8.4" class="anchored" data-anchor-id="ci-ex-ci-ht"><span class="header-section-number">12.8.4</span> If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.</h3>
<p>In this chapter, we haven’t run a hypothesis test, so this step is irrelevant for us here. However, in future chapters, we will incorporate this step into the rubric and see how the confidence interval relates to the conclusion of a hypothesis test.</p>
</section>
<section id="ci-ex-effect" class="level3" data-number="12.8.5">
<h3 data-number="12.8.5" class="anchored" data-anchor-id="ci-ex-effect"><span class="header-section-number">12.8.5</span> When comparing two groups, comment on the effect size and the practical significance of the result.</h3>
<p>This step will also become more clear in future chapters. It only applies to situations where you are attempting to find a difference between two groups. In this example, we’re simply using a sample statistic to estimate a single population parameter.</p>
</section>
</section>
<section id="ci-your-turn" class="level2" data-number="12.9">
<h2 data-number="12.9" class="anchored" data-anchor-id="ci-your-turn"><span class="header-section-number">12.9</span> Your turn</h2>
<p>Use the <code>smoking</code> data set from the <code>openintro</code> package. What percentage of the population of the U.K. smokes tobacco? (The information you need is in the <code>smoke</code> variable.) Use a 95% confidence interval.</p>
<section id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.">Check the relevant conditions to ensure that model assumptions are met.</h6>
<div class="answer">
<ul>
<li>Random
<ul>
<li>[Check condition here.]</li>
</ul></li>
<li>10%
<ul>
<li>[Check condition here.]</li>
</ul></li>
</ul>
</div>
</section>
<section id="calculate-and-graph-the-confidence-interval." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="calculate-and-graph-the-confidence-interval.">Calculate and graph the confidence interval.</h6>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to create the bootstrap sampling distribution.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to calculate the confidence interval.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to graph the confidence interval.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="state-but-do-not-overstate-a-contextually-meaningful-interpretation." class="level6 unnumbered">
<h6 class="unnumbered anchored" data-anchor-id="state-but-do-not-overstate-a-contextually-meaningful-interpretation.">State (but do not overstate) a contextually meaningful interpretation.</h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr>
<p>(We will ignore the last two last steps in the rubric. We haven’t run a hypothesis test and we’re not comparing smoking between two groups.)</p>
</section>
</section>
<section id="ci-interpret" class="level2" data-number="12.10">
<h2 data-number="12.10" class="anchored" data-anchor-id="ci-interpret"><span class="header-section-number">12.10</span> Interpreting confidence intervals</h2>
<p>Confidence intervals are notoriously difficult to interpret.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Here are several <em>wrong</em> interpretations of a 95% confidence interval:</p>
<ul>
<li><p>95% of the data lies in the interval.</p></li>
<li><p>There is a 95% chance that the sample proportion lies in the interval.</p></li>
<li><p>There is a 95% chance that the population parameter lies in the interval.</p></li>
</ul>
<p>We’ll take a closer look at these incorrect claims in a moment. First, let’s see how confidence intervals work using simulation.</p>
<p>In order to simulate, we’ll have to pretend temporarily that we know a true population parameter. Let’s use the example of a candidate who has the support of 64% of voters. In other words, <span class="math inline">\(p = 0.64\)</span>. We go out and get a sample of voters, let’s say 50. From that sample we construct a 95% confidence interval by bootstrapping. Most of the time, 64% (the true value!) should be in our interval. But sometimes it won’t be. We can get an unusual sample that is far away from 64%, just by pure chance alone. (Perhaps we accidentally run into a bunch of people who oppose our candidate.)</p>
<p>Okay, let’s do it again. Get a new sample and calculate a new confidence interval. This sample will likely result in a different sample proportion than the first sample. Therefore, the confidence interval will be located in a different place. Does it contain 64%? Most of the time, we expect it to. Occasionally, it will not.</p>
<p>We can do this over and over again through the magic of simulation! Here’s what this simulation looks like in R. The following code is quite technical, although you will recognize bits and pieces of it. Don’t worry about it. You won’t need to generate code like this on your own. Just look at the pretty picture in the output below below the code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11111</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The true population proportion is 0.64</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>true_val <span class="ot">&lt;-</span> <span class="fl">0.64</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The sample size is 50</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set confidence level</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>our_level <span class="ot">&lt;-</span> <span class="fl">0.95</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Set number of intervals to simulate</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>sim_num <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a random sample of size n.</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the test statistic and the bootstrap confidence interval.</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Put both into a single tibble.</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>simulate_ci <span class="ot">&lt;-</span> <span class="cf">function</span>(n, <span class="at">level =</span> <span class="fl">0.95</span>) {</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>    sample_data <span class="ot">&lt;-</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">factor</span>(<span class="fu">rbinom</span>(n , <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> true_val)) <span class="sc">%&gt;%</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">tibble</span>(<span class="at">data =</span> .)</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>    stat <span class="ot">&lt;-</span> sample_data <span class="sc">%&gt;%</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">observe</span>(<span class="at">response =</span> data, <span class="at">success =</span> <span class="st">"1"</span>, <span class="at">stat =</span> <span class="st">"prop"</span>)</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a>    ci <span class="ot">&lt;-</span> sample_data <span class="sc">%&gt;%</span></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>        <span class="fu">specify</span>(<span class="at">response =</span> data, <span class="at">success =</span> <span class="st">"1"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>        <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>        <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"prop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>        <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> our_level)</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(stat, ci) <span class="sc">%&gt;%</span></span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span>()</span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 100 random samples (each of size 50)</span></span>
<span id="cb50-31"><a href="#cb50-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign a color based on whether the intervals contain the true proportion</span></span>
<span id="cb50-32"><a href="#cb50-32" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(<span class="fu">rep</span>(sample_size, <span class="at">times =</span> sim_num), simulate_ci, <span class="at">level =</span> our_level) <span class="sc">%&gt;%</span></span>
<span id="cb50-33"><a href="#cb50-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">row_num =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb50-34"><a href="#cb50-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">color =</span> <span class="fu">ifelse</span>(lower_ci <span class="sc">&lt;=</span> true_val <span class="sc">&amp;</span> true_val <span class="sc">&lt;=</span> upper_ci,</span>
<span id="cb50-35"><a href="#cb50-35" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"black"</span>, <span class="st">"red"</span>),</span>
<span id="cb50-36"><a href="#cb50-36" aria-hidden="true" tabindex="-1"></a>           <span class="at">alpha =</span> <span class="fu">ifelse</span>(color <span class="sc">==</span> <span class="st">"black"</span>, <span class="fl">0.5</span>, <span class="dv">1</span>))</span>
<span id="cb50-37"><a href="#cb50-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-38"><a href="#cb50-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot all the simulated intervals</span></span>
<span id="cb50-39"><a href="#cb50-39" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ci, <span class="fu">aes</span>(<span class="at">x =</span> stat, <span class="at">y =</span> row_num,</span>
<span id="cb50-40"><a href="#cb50-40" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> color, <span class="at">alpha =</span> alpha)) <span class="sc">+</span></span>
<span id="cb50-41"><a href="#cb50-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb50-42"><a href="#cb50-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb50-43"><a href="#cb50-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> lower_ci, <span class="at">xend =</span> upper_ci, <span class="at">yend =</span> row_num)) <span class="sc">+</span></span>
<span id="cb50-44"><a href="#cb50-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> true_val, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb50-45"><a href="#cb50-45" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_alpha_identity</span>() <span class="sc">+</span></span>
<span id="cb50-46"><a href="#cb50-46" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Simulation"</span>, <span class="at">x =</span> <span class="st">"Estimates with confidence intervals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-confidence_intervals-web_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Each sample gives us a slightly different estimate, and therefore, a different confidence interval as well.</p>
<p>For each of the 100 simulated intervals, most of them (the black ones) do capture the true value of 0.64 (the blue vertical line). Occasionally they don’t (the red ones). We expect 5 red intervals, but since randomness is involved, it won’t necessarily be exactly 5. (Here there were only 3 bad intervals.)</p>
<p>This is the key to interpreting confidence intervals. The “95%” in a 95% confidence interval means that if we were to collect many random samples, about 95% of them would contain the true population parameter and about 5% would not.</p>
<p>So let’s revisit the erroneous statements from the beginning of this section and correct the misconceptions.</p>
<ul>
<li><del>95% of the data lies in the interval.</del>
<ul>
<li>This doesn’t even make sense. Our data is categorical. The confidence interval is a range of plausible values for the proportion of successes in the sample.</li>
</ul></li>
<li><del>There is a 95% chance that the sample proportion lies in the interval.</del>
<ul>
<li>No.&nbsp;There is essentially a 100% chance that the sample proportion lies in the interval. Most of the time, the sample proportion is very close to the center of the interval. When we bootstrap, the “infinite population” we are simulating has the same population proportion as the sample we started with. (After all, the infinite population is just many copies of the sample we started with.) Therefore, samples from that infinite population should be more or less centered around the sample proportion.</li>
</ul></li>
<li><del>There is a 95% chance that the population parameter lies in the interval.</del>
<ul>
<li>This is wrong in a more subtle way. The problem here as that it takes our interval as being fixed and special, and then tries to declare that of all possible population parameters, we have a 95% chance of the true one landing in our interval. The logic is backwards. The population parameter is the fixed truth. It doesn’t wander around and land in our interval sometimes and not at other times. It is our confidence interval that wanders; it is just one of many intervals we could have obtained from random sampling. When we say, “We are 95% confident that…,” we are just using a convenient shorthand for, “If we were to repeat the process of sampling and creating confidence intervals many times, about 95% of those times would produce an interval that happens to capture the actual population proportion.” But we’re lazy and we don’t want to say that every time.</li>
</ul></li>
</ul>
</section>
<section id="ci-conclusion" class="level2" data-number="12.11">
<h2 data-number="12.11" class="anchored" data-anchor-id="ci-conclusion"><span class="header-section-number">12.11</span> Conclusion</h2>
<p>A confidence interval is a form of statistical inference that gives us a range of numbers in which we hope to capture the true population parameter. Of course, we can’t be certain of that. If we repeatedly collect samples, the expectation is that 95% of those samples will produce confidence intervals that capture the true population parameter, but that also means that 5% will not. We’ll never know if our sample was one of the 95% that worked, or one of the 5% that did not. And even if we get one of the intervals that worked, all we have is a range of values and it’s impossible to determine which of those values is the true population parameter. Because it’s statistics, we just have to live with that uncertainty.</p>
<section id="ci-prep" class="level3" data-number="12.11.1">
<h3 data-number="12.11.1" class="anchored" data-anchor-id="ci-prep"><span class="header-section-number">12.11.1</span> Preparing and submitting your assignment</h3>
<ol type="1">
<li>From the “Run” menu, select “Restart R and Run All Chunks”.</li>
<li>Deal with any code errors that crop up. Repeat steps 1–-2 until there are no more code errors.</li>
<li>Spell check your document by clicking the icon with “ABC” and a check mark.</li>
<li>Hit the “Preview” button one last time to generate the final draft of the <code>.nb.html</code> file.</li>
<li>Proofread the HTML file carefully. If there are errors, go back and fix them, then repeat steps 1–5 again.</li>
</ol>
<p>If you have completed this chapter as part of a statistics course, follow the directions you receive from your professor to submit your assignment.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>A contrary position is proffered by Richard McElreath, an evolutionary ecologist and author of the amazing book <em>Statistical Rethinking</em>. He uses 89% and 97% intervals to highlight the absurdity of regarding 95% as a magic number that has some kind of deep, special meaning.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Several studies have given surveys to statistics students, teachers, and researchers, and find that even these people often misinterpret confidence intervals. See, for example, this paper: http://www.ejwagenmakers.com/inpress/HoekstraEtAlPBR.pdf<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-hypothesis_testing_with_randomization_2-web.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization, Part 2</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./13-normal_models-web.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Normal models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>