<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Inference for one proportion | Introduction to Statistics: an integrated textbook and workbook using R</title>
  <meta name="description" content="This is a full-semester introductory statistics course using a workbook approach that incorporates all the course material into downloadable R notebooks." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Inference for one proportion | Introduction to Statistics: an integrated textbook and workbook using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a full-semester introductory statistics course using a workbook approach that incorporates all the course material into downloadable R notebooks." />
  <meta name="github-repo" content="VectorPosse/intro_stats" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Inference for one proportion | Introduction to Statistics: an integrated textbook and workbook using R" />
  
  <meta name="twitter:description" content="This is a full-semester introductory statistics course using a workbook approach that incorporates all the course material into downloadable R notebooks." />
  

<meta name="author" content="Sean Raleigh, Westminster College (Salt Lake City, UT)" />


<meta name="date" content="2022-09-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="samp-dist-models.html"/>
<link rel="next" href="appendix-rubric.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistics: an integrated textbook and workbook using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#intro-history"><i class="fa fa-check"></i>History and goals</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#intro-philosophy"><i class="fa fa-check"></i>Philosophy and pedagogy</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#intro-structure"><i class="fa fa-check"></i>Course structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#intro-onward"><i class="fa fa-check"></i>Onward and upward</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intror.html"><a href="intror.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="" data-path="intror.html"><a href="intror.html#functions-introduced-in-this-chapter"><i class="fa fa-check"></i>Functions introduced in this chapter:</a></li>
<li class="chapter" data-level="1.1" data-path="intror.html"><a href="intror.html#intror-intro"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="intror.html"><a href="intror.html#intror-whatisr"><i class="fa fa-check"></i><b>1.2</b> What is R?</a></li>
<li class="chapter" data-level="1.3" data-path="intror.html"><a href="intror.html#intror-rstudio"><i class="fa fa-check"></i><b>1.3</b> RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="intror.html"><a href="intror.html#intror-trysomething"><i class="fa fa-check"></i><b>1.4</b> Try something!</a></li>
<li class="chapter" data-level="1.5" data-path="intror.html"><a href="intror.html#intror-loadpackages"><i class="fa fa-check"></i><b>1.5</b> Load packages</a></li>
<li class="chapter" data-level="1.6" data-path="intror.html"><a href="intror.html#intror-gettinghelp"><i class="fa fa-check"></i><b>1.6</b> Getting help</a></li>
<li class="chapter" data-level="1.7" data-path="intror.html"><a href="intror.html#intror-understandingdata"><i class="fa fa-check"></i><b>1.7</b> Understanding the data</a></li>
<li class="chapter" data-level="1.8" data-path="intror.html"><a href="intror.html#intror-understandingvariables"><i class="fa fa-check"></i><b>1.8</b> Understanding the variables</a></li>
<li class="chapter" data-level="1.9" data-path="intror.html"><a href="intror.html#intror-projects"><i class="fa fa-check"></i><b>1.9</b> Projects</a></li>
<li class="chapter" data-level="1.10" data-path="intror.html"><a href="intror.html#intror-conclusion"><i class="fa fa-check"></i><b>1.10</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rmark.html"><a href="rmark.html"><i class="fa fa-check"></i><b>2</b> Using R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="rmark.html"><a href="rmark.html#functions-introduced-in-this-chapter-1"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="2.1" data-path="rmark.html"><a href="rmark.html#rmark-intro"><i class="fa fa-check"></i><b>2.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="rmark.html"><a href="rmark.html#rmark-project"><i class="fa fa-check"></i><b>2.1.1</b> Are you in your project?</a></li>
<li class="chapter" data-level="2.1.2" data-path="rmark.html"><a href="rmark.html#rmark-install"><i class="fa fa-check"></i><b>2.1.2</b> Install new packages</a></li>
<li class="chapter" data-level="2.1.3" data-path="rmark.html"><a href="rmark.html#rmark-download"><i class="fa fa-check"></i><b>2.1.3</b> Download the R notebook file</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="rmark.html"><a href="rmark.html#rmark-whatis"><i class="fa fa-check"></i><b>2.2</b> What is R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="rmark.html"><a href="rmark.html#rmark-previewing"><i class="fa fa-check"></i><b>2.3</b> Previewing a document</a></li>
<li class="chapter" data-level="2.4" data-path="rmark.html"><a href="rmark.html#rmark-literate"><i class="fa fa-check"></i><b>2.4</b> Literate programming</a></li>
<li class="chapter" data-level="2.5" data-path="rmark.html"><a href="rmark.html#rmark-reproducible"><i class="fa fa-check"></i><b>2.5</b> Reproducible research</a></li>
<li class="chapter" data-level="2.6" data-path="rmark.html"><a href="rmark.html#rmark-structure"><i class="fa fa-check"></i><b>2.6</b> Structure of an R Notebook</a></li>
<li class="chapter" data-level="2.7" data-path="rmark.html"><a href="rmark.html#is-this-a-new-section"><i class="fa fa-check"></i><b>2.7</b> Is this a new section?</a></li>
<li class="chapter" data-level="2.8" data-path="rmark.html"><a href="rmark.html#rmark-othertricks"><i class="fa fa-check"></i><b>2.8</b> Other formatting tricks</a></li>
<li class="chapter" data-level="2.9" data-path="rmark.html"><a href="rmark.html#rmark-codechunks"><i class="fa fa-check"></i><b>2.9</b> R code chunks</a></li>
<li class="chapter" data-level="2.10" data-path="rmark.html"><a href="rmark.html#rmark-inline"><i class="fa fa-check"></i><b>2.10</b> Inline R commands</a></li>
<li class="chapter" data-level="2.11" data-path="rmark.html"><a href="rmark.html#rmark-copypaste"><i class="fa fa-check"></i><b>2.11</b> Copying and pasting</a></li>
<li class="chapter" data-level="2.12" data-path="rmark.html"><a href="rmark.html#rmark-conclusion"><i class="fa fa-check"></i><b>2.12</b> Conclusion</a>
<ul>
<li class="chapter" data-level="2.12.1" data-path="rmark.html"><a href="rmark.html#rmark-prep"><i class="fa fa-check"></i><b>2.12.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="categorical.html"><a href="categorical.html"><i class="fa fa-check"></i><b>3</b> Categorical data</a>
<ul>
<li class="chapter" data-level="" data-path="categorical.html"><a href="categorical.html#functions-introduced-in-this-chapter-2"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="3.1" data-path="categorical.html"><a href="categorical.html#categorical-intro"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="categorical.html"><a href="categorical.html#cateogorical-install"><i class="fa fa-check"></i><b>3.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="3.1.2" data-path="categorical.html"><a href="categorical.html#categorical-download"><i class="fa fa-check"></i><b>3.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="3.1.3" data-path="categorical.html"><a href="categorical.html#categorical-restart"><i class="fa fa-check"></i><b>3.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="3.1.4" data-path="categorical.html"><a href="categorical.html#categorical-load"><i class="fa fa-check"></i><b>3.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="categorical.html"><a href="categorical.html#categorical-data"><i class="fa fa-check"></i><b>3.2</b> Categorical data</a></li>
<li class="chapter" data-level="3.3" data-path="categorical.html"><a href="categorical.html#categorical-factor"><i class="fa fa-check"></i><b>3.3</b> Factor variables</a></li>
<li class="chapter" data-level="3.4" data-path="categorical.html"><a href="categorical.html#categorical-summarizing-one"><i class="fa fa-check"></i><b>3.4</b> Summarizing one categorical variable</a></li>
<li class="chapter" data-level="3.5" data-path="categorical.html"><a href="categorical.html#categorical-graphing-one"><i class="fa fa-check"></i><b>3.5</b> Graphing one categorical variable</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="categorical.html"><a href="categorical.html#categorical-ggplot"><i class="fa fa-check"></i><b>3.5.1</b> ggplot</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="categorical.html"><a href="categorical.html#categorical-summarizing-two"><i class="fa fa-check"></i><b>3.6</b> Summarizing two categorical variables</a></li>
<li class="chapter" data-level="3.7" data-path="categorical.html"><a href="categorical.html#categorical-graphing-two"><i class="fa fa-check"></i><b>3.7</b> Graphing two categorical variables</a></li>
<li class="chapter" data-level="3.8" data-path="categorical.html"><a href="categorical.html#categorical-recoding"><i class="fa fa-check"></i><b>3.8</b> Recoding factor variables</a></li>
<li class="chapter" data-level="3.9" data-path="categorical.html"><a href="categorical.html#categorical-pub"><i class="fa fa-check"></i><b>3.9</b> Publication-ready graphics</a></li>
<li class="chapter" data-level="3.10" data-path="categorical.html"><a href="categorical.html#categorical-summary"><i class="fa fa-check"></i><b>3.10</b> Plotting summary data</a></li>
<li class="chapter" data-level="3.11" data-path="categorical.html"><a href="categorical.html#categorical-conclusion"><i class="fa fa-check"></i><b>3.11</b> Conclusion</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="categorical.html"><a href="categorical.html#categorical-prep"><i class="fa fa-check"></i><b>3.11.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="numerical.html"><a href="numerical.html"><i class="fa fa-check"></i><b>4</b> Numerical data</a>
<ul>
<li class="chapter" data-level="" data-path="numerical.html"><a href="numerical.html#functions-introduced-in-this-chapter-3"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="4.1" data-path="numerical.html"><a href="numerical.html#numerical-intro"><i class="fa fa-check"></i><b>4.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="numerical.html"><a href="numerical.html#numerical-install"><i class="fa fa-check"></i><b>4.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="4.1.2" data-path="numerical.html"><a href="numerical.html#numerical-download"><i class="fa fa-check"></i><b>4.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="4.1.3" data-path="numerical.html"><a href="numerical.html#numerical-restart"><i class="fa fa-check"></i><b>4.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="4.1.4" data-path="numerical.html"><a href="numerical.html#numerical-load"><i class="fa fa-check"></i><b>4.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="numerical.html"><a href="numerical.html#numerical-notation"><i class="fa fa-check"></i><b>4.2</b> A note about mathematical notation</a></li>
<li class="chapter" data-level="4.3" data-path="numerical.html"><a href="numerical.html#numerical-statistics"><i class="fa fa-check"></i><b>4.3</b> Statistics</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="numerical.html"><a href="numerical.html#numerical-mean-sd"><i class="fa fa-check"></i><b>4.3.1</b> Mean and standard deviation</a></li>
<li class="chapter" data-level="4.3.2" data-path="numerical.html"><a href="numerical.html#numerical-median-iqr"><i class="fa fa-check"></i><b>4.3.2</b> Median and IQR</a></li>
<li class="chapter" data-level="4.3.3" data-path="numerical.html"><a href="numerical.html#numerical-robust"><i class="fa fa-check"></i><b>4.3.3</b> Robust statistics</a></li>
<li class="chapter" data-level="4.3.4" data-path="numerical.html"><a href="numerical.html#numerical-five"><i class="fa fa-check"></i><b>4.3.4</b> Five-number summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="numerical.html"><a href="numerical.html#numerical-graphing-one"><i class="fa fa-check"></i><b>4.4</b> Graphing one numerical variable</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="numerical.html"><a href="numerical.html#numerical-shape"><i class="fa fa-check"></i><b>4.4.1</b> The shape of data</a></li>
<li class="chapter" data-level="4.4.2" data-path="numerical.html"><a href="numerical.html#numerical-less-useful"><i class="fa fa-check"></i><b>4.4.2</b> Less useful plot types</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="numerical.html"><a href="numerical.html#numerical-graphing-two"><i class="fa fa-check"></i><b>4.5</b> Graphing two numerical variables</a></li>
<li class="chapter" data-level="4.6" data-path="numerical.html"><a href="numerical.html#numerical-graphing-grouped"><i class="fa fa-check"></i><b>4.6</b> Graphing grouped numerical data</a></li>
<li class="chapter" data-level="4.7" data-path="numerical.html"><a href="numerical.html#numerical-pub"><i class="fa fa-check"></i><b>4.7</b> Publication-ready graphics</a></li>
<li class="chapter" data-level="4.8" data-path="numerical.html"><a href="numerical.html#numerical-conclusion"><i class="fa fa-check"></i><b>4.8</b> Conclusion</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="numerical.html"><a href="numerical.html#numerical-prep"><i class="fa fa-check"></i><b>4.8.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulating.html"><a href="manipulating.html"><i class="fa fa-check"></i><b>5</b> Manipulating data</a>
<ul>
<li class="chapter" data-level="" data-path="manipulating.html"><a href="manipulating.html#functions-introduced-in-this-chapter-4"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="5.1" data-path="manipulating.html"><a href="manipulating.html#manipulating-intro"><i class="fa fa-check"></i><b>5.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="manipulating.html"><a href="manipulating.html#manipulating-install"><i class="fa fa-check"></i><b>5.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="manipulating.html"><a href="manipulating.html#manipulating-download"><i class="fa fa-check"></i><b>5.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="5.1.3" data-path="manipulating.html"><a href="manipulating.html#manipulating-restart"><i class="fa fa-check"></i><b>5.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="5.1.4" data-path="manipulating.html"><a href="manipulating.html#manipulating-load"><i class="fa fa-check"></i><b>5.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="manipulating.html"><a href="manipulating.html#manipulating-csv"><i class="fa fa-check"></i><b>5.2</b> Importing CSV data</a></li>
<li class="chapter" data-level="5.3" data-path="manipulating.html"><a href="manipulating.html#manipulating-dplyr"><i class="fa fa-check"></i><b>5.3</b> Introduction to <code>dplyr</code></a></li>
<li class="chapter" data-level="5.4" data-path="manipulating.html"><a href="manipulating.html#manipulating-select"><i class="fa fa-check"></i><b>5.4</b> <code>select</code></a></li>
<li class="chapter" data-level="5.5" data-path="manipulating.html"><a href="manipulating.html#manipulating-rm"><i class="fa fa-check"></i><b>5.5</b> The <code>rm</code> command</a></li>
<li class="chapter" data-level="5.6" data-path="manipulating.html"><a href="manipulating.html#manipulating-filter"><i class="fa fa-check"></i><b>5.6</b> <code>filter</code></a></li>
<li class="chapter" data-level="5.7" data-path="manipulating.html"><a href="manipulating.html#manipulating-arrange"><i class="fa fa-check"></i><b>5.7</b> <code>arrange</code></a></li>
<li class="chapter" data-level="5.8" data-path="manipulating.html"><a href="manipulating.html#manipulating-mutate"><i class="fa fa-check"></i><b>5.8</b> <code>mutate</code></a></li>
<li class="chapter" data-level="5.9" data-path="manipulating.html"><a href="manipulating.html#manipulating-summ-group"><i class="fa fa-check"></i><b>5.9</b> <code>summarise</code> (with <code>group_by</code>)</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="manipulating.html"><a href="manipulating.html#manipulating-piping"><i class="fa fa-check"></i><b>5.9.1</b> Piping</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="manipulating.html"><a href="manipulating.html#manipulating-all-together"><i class="fa fa-check"></i><b>5.10</b> Putting it all together</a></li>
<li class="chapter" data-level="5.11" data-path="manipulating.html"><a href="manipulating.html#manipulating-conclusion"><i class="fa fa-check"></i><b>5.11</b> Conclusion</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="manipulating.html"><a href="manipulating.html#manipulating-prep"><i class="fa fa-check"></i><b>5.11.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>6</b> Correlation</a>
<ul>
<li class="chapter" data-level="" data-path="correlation.html"><a href="correlation.html#functions-introduced-in-this-chapter-5"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="6.1" data-path="correlation.html"><a href="correlation.html#correlation-intro"><i class="fa fa-check"></i><b>6.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="correlation.html"><a href="correlation.html#correlation-install"><i class="fa fa-check"></i><b>6.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="6.1.2" data-path="correlation.html"><a href="correlation.html#correlation-download"><i class="fa fa-check"></i><b>6.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="6.1.3" data-path="correlation.html"><a href="correlation.html#correlation-restart"><i class="fa fa-check"></i><b>6.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="6.1.4" data-path="correlation.html"><a href="correlation.html#correlation-load"><i class="fa fa-check"></i><b>6.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="correlation.html"><a href="correlation.html#correlation-redlining"><i class="fa fa-check"></i><b>6.2</b> Redlining in Chicago</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="correlation.html"><a href="correlation.html#correlation-eda"><i class="fa fa-check"></i><b>6.2.1</b> Exploratory data analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="correlation.html"><a href="correlation.html#correlation-correlation"><i class="fa fa-check"></i><b>6.3</b> Correlation</a></li>
<li class="chapter" data-level="6.4" data-path="correlation.html"><a href="correlation.html#correlation-conditions"><i class="fa fa-check"></i><b>6.4</b> Conditions for correlation</a></li>
<li class="chapter" data-level="6.5" data-path="correlation.html"><a href="correlation.html#correlation-calculating"><i class="fa fa-check"></i><b>6.5</b> Calculating correlation</a></li>
<li class="chapter" data-level="6.6" data-path="correlation.html"><a href="correlation.html#correlation-causation"><i class="fa fa-check"></i><b>6.6</b> Correlation is not causation</a></li>
<li class="chapter" data-level="6.7" data-path="correlation.html"><a href="correlation.html#correlation-obs-exp"><i class="fa fa-check"></i><b>6.7</b> Observational studies versus experiments</a></li>
<li class="chapter" data-level="6.8" data-path="correlation.html"><a href="correlation.html#correlation-pred-exp"><i class="fa fa-check"></i><b>6.8</b> Prediction versus explanation</a></li>
<li class="chapter" data-level="6.9" data-path="correlation.html"><a href="correlation.html#correlation-conclusion"><i class="fa fa-check"></i><b>6.9</b> Conclusion</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="correlation.html"><a href="correlation.html#correlation-prep"><i class="fa fa-check"></i><b>6.9.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>7</b> Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#functions-introduced-in-this-chapter-6"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="7.1" data-path="regression.html"><a href="regression.html#regression-intro"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="regression.html"><a href="regression.html#install-new-packages"><i class="fa fa-check"></i><b>7.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="7.1.2" data-path="regression.html"><a href="regression.html#regression-download"><i class="fa fa-check"></i><b>7.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="7.1.3" data-path="regression.html"><a href="regression.html#regression-restart"><i class="fa fa-check"></i><b>7.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="7.1.4" data-path="regression.html"><a href="regression.html#regression-load"><i class="fa fa-check"></i><b>7.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regression.html"><a href="regression.html#regression-regression"><i class="fa fa-check"></i><b>7.2</b> Regression</a></li>
<li class="chapter" data-level="7.3" data-path="regression.html"><a href="regression.html#regression-models"><i class="fa fa-check"></i><b>7.3</b> Models</a></li>
<li class="chapter" data-level="7.4" data-path="regression.html"><a href="regression.html#regression-conditions"><i class="fa fa-check"></i><b>7.4</b> Checking conditions</a></li>
<li class="chapter" data-level="7.5" data-path="regression.html"><a href="regression.html#regression-calculating"><i class="fa fa-check"></i><b>7.5</b> Calculating the regression line</a></li>
<li class="chapter" data-level="7.6" data-path="regression.html"><a href="regression.html#regression-interpreting"><i class="fa fa-check"></i><b>7.6</b> Interpreting the coefficients</a></li>
<li class="chapter" data-level="7.7" data-path="regression.html"><a href="regression.html#regression-rescaling"><i class="fa fa-check"></i><b>7.7</b> Rescaling to make interpretations more meaningful</a></li>
<li class="chapter" data-level="7.8" data-path="regression.html"><a href="regression.html#regression-tidy"><i class="fa fa-check"></i><b>7.8</b> The <code>tidy</code> command</a></li>
<li class="chapter" data-level="7.9" data-path="regression.html"><a href="regression.html#regression-residuals"><i class="fa fa-check"></i><b>7.9</b> Residuals</a></li>
<li class="chapter" data-level="7.10" data-path="regression.html"><a href="regression.html#regression-r2"><i class="fa fa-check"></i><b>7.10</b> <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="7.11" data-path="regression.html"><a href="regression.html#regression-multiple"><i class="fa fa-check"></i><b>7.11</b> Multiple predictors</a></li>
<li class="chapter" data-level="7.12" data-path="regression.html"><a href="regression.html#regression-your-turn"><i class="fa fa-check"></i><b>7.12</b> Your turn</a></li>
<li class="chapter" data-level="7.13" data-path="regression.html"><a href="regression.html#regression-conclusion"><i class="fa fa-check"></i><b>7.13</b> Conclusion</a>
<ul>
<li class="chapter" data-level="7.13.1" data-path="regression.html"><a href="regression.html#regression-prep"><i class="fa fa-check"></i><b>7.13.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="randomization1.html"><a href="randomization1.html"><i class="fa fa-check"></i><b>8</b> Introduction to randomization, Part 1</a>
<ul>
<li class="chapter" data-level="" data-path="randomization1.html"><a href="randomization1.html#functions-introduced-in-this-chapter-7"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="8.1" data-path="randomization1.html"><a href="randomization1.html#randomization1-intro"><i class="fa fa-check"></i><b>8.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="randomization1.html"><a href="randomization1.html#randomization1-install"><i class="fa fa-check"></i><b>8.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="8.1.2" data-path="randomization1.html"><a href="randomization1.html#randomization1-download"><i class="fa fa-check"></i><b>8.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="8.1.3" data-path="randomization1.html"><a href="randomization1.html#randomization1-restart"><i class="fa fa-check"></i><b>8.1.3</b> Restart R and run all chunks</a></li>
<li class="chapter" data-level="8.1.4" data-path="randomization1.html"><a href="randomization1.html#randomization1-load"><i class="fa fa-check"></i><b>8.1.4</b> Load packages</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="randomization1.html"><a href="randomization1.html#randomization1-sample-pop"><i class="fa fa-check"></i><b>8.2</b> Sample and population</a></li>
<li class="chapter" data-level="8.3" data-path="randomization1.html"><a href="randomization1.html#randomization1-coin"><i class="fa fa-check"></i><b>8.3</b> Flipping a coin</a></li>
<li class="chapter" data-level="8.4" data-path="randomization1.html"><a href="randomization1.html#randomization1-multiple"><i class="fa fa-check"></i><b>8.4</b> Multiple simulations</a></li>
<li class="chapter" data-level="8.5" data-path="randomization1.html"><a href="randomization1.html#randomization1-bigger"><i class="fa fa-check"></i><b>8.5</b> Bigger and better!</a></li>
<li class="chapter" data-level="8.6" data-path="randomization1.html"><a href="randomization1.html#randomization1-more"><i class="fa fa-check"></i><b>8.6</b> More flips</a></li>
<li class="chapter" data-level="8.7" data-path="randomization1.html"><a href="randomization1.html#randomization1-who-cares"><i class="fa fa-check"></i><b>8.7</b> But who cares about coin flips?</a></li>
<li class="chapter" data-level="8.8" data-path="randomization1.html"><a href="randomization1.html#randomization1-sampling-var"><i class="fa fa-check"></i><b>8.8</b> Sampling variability</a></li>
<li class="chapter" data-level="8.9" data-path="randomization1.html"><a href="randomization1.html#randomization1-conclusion"><i class="fa fa-check"></i><b>8.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="randomization2.html"><a href="randomization2.html"><i class="fa fa-check"></i><b>9</b> Introduction to randomization, Part 2</a>
<ul>
<li class="chapter" data-level="" data-path="randomization2.html"><a href="randomization2.html#functions-introduced-in-this-chapter-8"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="9.1" data-path="randomization2.html"><a href="randomization2.html#randomization2-intro"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="randomization2.html"><a href="randomization2.html#randomization2-install"><i class="fa fa-check"></i><b>9.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="9.1.2" data-path="randomization2.html"><a href="randomization2.html#randomization2-download"><i class="fa fa-check"></i><b>9.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="9.1.3" data-path="randomization2.html"><a href="randomization2.html#randomization2-restart"><i class="fa fa-check"></i><b>9.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="randomization2.html"><a href="randomization2.html#randomization2-load"><i class="fa fa-check"></i><b>9.2</b> Load packages</a></li>
<li class="chapter" data-level="9.3" data-path="randomization2.html"><a href="randomization2.html#randomization2-question"><i class="fa fa-check"></i><b>9.3</b> Our research question</a></li>
<li class="chapter" data-level="9.4" data-path="randomization2.html"><a href="randomization2.html#randomization2-eda"><i class="fa fa-check"></i><b>9.4</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="9.5" data-path="randomization2.html"><a href="randomization2.html#randomization2-permuting"><i class="fa fa-check"></i><b>9.5</b> Permuting</a></li>
<li class="chapter" data-level="9.6" data-path="randomization2.html"><a href="randomization2.html#randomization2-randomization"><i class="fa fa-check"></i><b>9.6</b> Randomization</a></li>
<li class="chapter" data-level="9.7" data-path="randomization2.html"><a href="randomization2.html#randomization2-infer"><i class="fa fa-check"></i><b>9.7</b> The <code>infer</code> package</a></li>
<li class="chapter" data-level="9.8" data-path="randomization2.html"><a href="randomization2.html#randomization2-plot"><i class="fa fa-check"></i><b>9.8</b> Plot results</a></li>
<li class="chapter" data-level="9.9" data-path="randomization2.html"><a href="randomization2.html#randomization2-chance"><i class="fa fa-check"></i><b>9.9</b> By chance?</a></li>
<li class="chapter" data-level="9.10" data-path="randomization2.html"><a href="randomization2.html#randomization2-your-turn"><i class="fa fa-check"></i><b>9.10</b> Your turn</a></li>
<li class="chapter" data-level="9.11" data-path="randomization2.html"><a href="randomization2.html#randomization2-simpson"><i class="fa fa-check"></i><b>9.11</b> Simpson’s paradox</a></li>
<li class="chapter" data-level="9.12" data-path="randomization2.html"><a href="randomization2.html#randomization2-conclusion"><i class="fa fa-check"></i><b>9.12</b> Conclusion</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="randomization2.html"><a href="randomization2.html#randomization2-prep"><i class="fa fa-check"></i><b>9.12.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypothesis1.html"><a href="hypothesis1.html"><i class="fa fa-check"></i><b>10</b> Hypothesis testing with randomization, Part 1</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis1.html"><a href="hypothesis1.html#functions-introduced-in-this-chapter-9"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="10.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-intro"><i class="fa fa-check"></i><b>10.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-install"><i class="fa fa-check"></i><b>10.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="10.1.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-download"><i class="fa fa-check"></i><b>10.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="10.1.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-restart"><i class="fa fa-check"></i><b>10.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-load"><i class="fa fa-check"></i><b>10.2</b> Load packages</a></li>
<li class="chapter" data-level="10.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-question"><i class="fa fa-check"></i><b>10.3</b> Our research question</a></li>
<li class="chapter" data-level="10.4" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-hypothesis-testing"><i class="fa fa-check"></i><b>10.4</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-eda"><i class="fa fa-check"></i><b>10.4.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.4.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-hypotheses"><i class="fa fa-check"></i><b>10.4.2</b> Hypotheses</a></li>
<li class="chapter" data-level="10.4.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-model"><i class="fa fa-check"></i><b>10.4.3</b> Model</a></li>
<li class="chapter" data-level="10.4.4" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-mechanics"><i class="fa fa-check"></i><b>10.4.4</b> Mechanics</a></li>
<li class="chapter" data-level="10.4.5" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ht-conclusion"><i class="fa fa-check"></i><b>10.4.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-example"><i class="fa fa-check"></i><b>10.5</b> Example</a></li>
<li class="chapter" data-level="10.6" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-eda"><i class="fa fa-check"></i><b>10.6</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-documentation"><i class="fa fa-check"></i><b>10.6.1</b> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</a></li>
<li class="chapter" data-level="10.6.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-prepare"><i class="fa fa-check"></i><b>10.6.2</b> Prepare the data for analysis.</a></li>
<li class="chapter" data-level="10.6.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-plots"><i class="fa fa-check"></i><b>10.6.3</b> Make tables or plots to explore the data visually.</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-hypotheses"><i class="fa fa-check"></i><b>10.7</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-sample-pop"><i class="fa fa-check"></i><b>10.7.1</b> Identify the sample (or samples) and a reasonable population (or populations) of interest.</a></li>
<li class="chapter" data-level="10.7.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-express-words"><i class="fa fa-check"></i><b>10.7.2</b> Express the null and alternative hypotheses as contextually meaningful full sentences.</a></li>
<li class="chapter" data-level="10.7.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-express-math"><i class="fa fa-check"></i><b>10.7.3</b> Express the null and alternative hypotheses in symbols (when possible).</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-model"><i class="fa fa-check"></i><b>10.8</b> Model</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-sampling-dist-model"><i class="fa fa-check"></i><b>10.8.1</b> Identify the sampling distribution model.</a></li>
<li class="chapter" data-level="10.8.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-ht-conditions"><i class="fa fa-check"></i><b>10.8.2</b> Check the relevant conditions to ensure that model assumptions are met.</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-mechanics"><i class="fa fa-check"></i><b>10.9</b> Mechanics</a>
<ul>
<li class="chapter" data-level="10.9.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-compute-test-stat"><i class="fa fa-check"></i><b>10.9.1</b> Compute the test statistic.</a></li>
<li class="chapter" data-level="10.9.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-report-test-stat"><i class="fa fa-check"></i><b>10.9.2</b> Report the test statistic in context (when possible).</a></li>
<li class="chapter" data-level="10.9.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-plot-null"><i class="fa fa-check"></i><b>10.9.3</b> Plot the null distribution.</a></li>
<li class="chapter" data-level="10.9.4" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-calculate-p"><i class="fa fa-check"></i><b>10.9.4</b> Calculate the P-value.</a></li>
<li class="chapter" data-level="10.9.5" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-interpret-p"><i class="fa fa-check"></i><b>10.9.5</b> Interpret the P-value as a probability given the null.</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-ht-conclusion"><i class="fa fa-check"></i><b>10.10</b> Conclusion</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-stat-conclusion"><i class="fa fa-check"></i><b>10.10.1</b> State the statistical conclusion.</a></li>
<li class="chapter" data-level="10.10.2" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-context-conclusion"><i class="fa fa-check"></i><b>10.10.2</b> State (but do not overstate) a contextually meaningful conclusion.</a></li>
<li class="chapter" data-level="10.10.3" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-reservations"><i class="fa fa-check"></i><b>10.10.3</b> Express reservations or uncertainty about the generalizability of the conclusion.</a></li>
<li class="chapter" data-level="10.10.4" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-ex-errors"><i class="fa fa-check"></i><b>10.10.4</b> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-one-sided-two-sided"><i class="fa fa-check"></i><b>10.11</b> More on one-sided and two-sided tests</a></li>
<li class="chapter" data-level="10.12" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-fail-to-reject"><i class="fa fa-check"></i><b>10.12</b> A reminder about failing to reject the null</a></li>
<li class="chapter" data-level="10.13" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-your-turn"><i class="fa fa-check"></i><b>10.13</b> Your turn</a></li>
<li class="chapter" data-level="10.14" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-conclusion"><i class="fa fa-check"></i><b>10.14</b> Conclusion</a>
<ul>
<li class="chapter" data-level="10.14.1" data-path="hypothesis1.html"><a href="hypothesis1.html#hypothesis1-prep"><i class="fa fa-check"></i><b>10.14.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="hypothesis2.html"><a href="hypothesis2.html"><i class="fa fa-check"></i><b>11</b> Hypothesis testing with randomization, Part 2</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis2.html"><a href="hypothesis2.html#functions-introduced-in-this-chapter-10"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="11.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-intro"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-install"><i class="fa fa-check"></i><b>11.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="11.1.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-download"><i class="fa fa-check"></i><b>11.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="11.1.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-restart"><i class="fa fa-check"></i><b>11.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-load"><i class="fa fa-check"></i><b>11.2</b> Load packages</a></li>
<li class="chapter" data-level="11.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-question"><i class="fa fa-check"></i><b>11.3</b> Our research question</a></li>
<li class="chapter" data-level="11.4" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2ex-eda"><i class="fa fa-check"></i><b>11.4</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-documentation"><i class="fa fa-check"></i><b>11.4.1</b> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</a></li>
<li class="chapter" data-level="11.4.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-prepare"><i class="fa fa-check"></i><b>11.4.2</b> Prepare the data for analysis.</a></li>
<li class="chapter" data-level="11.4.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-plots"><i class="fa fa-check"></i><b>11.4.3</b> Make tables or plots to explore the data visually.</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-logic"><i class="fa fa-check"></i><b>11.5</b> The logic of inference and randomization</a></li>
<li class="chapter" data-level="11.6" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-hypotheses"><i class="fa fa-check"></i><b>11.6</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-sample-pop"><i class="fa fa-check"></i><b>11.6.1</b> Identify the sample (or samples) and a reasonable population (or populations) of interest.</a></li>
<li class="chapter" data-level="11.6.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-express-words"><i class="fa fa-check"></i><b>11.6.2</b> Express the null and alternative hypotheses as contextually meaningful full sentences.</a></li>
<li class="chapter" data-level="11.6.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-express-math"><i class="fa fa-check"></i><b>11.6.3</b> Express the null and alternative hypotheses in symbols (when possible).</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-model"><i class="fa fa-check"></i><b>11.7</b> Model</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-sampling-dist-model"><i class="fa fa-check"></i><b>11.7.1</b> Identify the sampling distribution model.</a></li>
<li class="chapter" data-level="11.7.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-ht-conditions"><i class="fa fa-check"></i><b>11.7.2</b> Check the relevant conditions to ensure that model assumptions are met.</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-mechanics"><i class="fa fa-check"></i><b>11.8</b> Mechanics</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-compute-test-stat"><i class="fa fa-check"></i><b>11.8.1</b> Compute the test statistic.</a></li>
<li class="chapter" data-level="11.8.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-report-test-stat"><i class="fa fa-check"></i><b>11.8.2</b> Report the test statistic in context (when possible).</a></li>
<li class="chapter" data-level="11.8.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-plot-null"><i class="fa fa-check"></i><b>11.8.3</b> Plot the null distribution.</a></li>
<li class="chapter" data-level="11.8.4" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-calculate-p"><i class="fa fa-check"></i><b>11.8.4</b> Calculate the P-value.</a></li>
<li class="chapter" data-level="11.8.5" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-interpret-p"><i class="fa fa-check"></i><b>11.8.5</b> Interpret the P-value as a probability given the null.</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-ht-conclusion"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-stat-conclusion"><i class="fa fa-check"></i><b>11.9.1</b> State the statistical conclusion.</a></li>
<li class="chapter" data-level="11.9.2" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-context-conclusion"><i class="fa fa-check"></i><b>11.9.2</b> State (but do not overstate) a contextually meaningful conclusion.</a></li>
<li class="chapter" data-level="11.9.3" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-reservations"><i class="fa fa-check"></i><b>11.9.3</b> Express reservations or uncertainty about the generalizability of the conclusion.</a></li>
<li class="chapter" data-level="11.9.4" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-ex-errors"><i class="fa fa-check"></i><b>11.9.4</b> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-your-turn"><i class="fa fa-check"></i><b>11.10</b> Your turn</a></li>
<li class="chapter" data-level="11.11" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-conclusion"><i class="fa fa-check"></i><b>11.11</b> Conclusion</a>
<ul>
<li class="chapter" data-level="11.11.1" data-path="hypothesis2.html"><a href="hypothesis2.html#hypothesis2-prep"><i class="fa fa-check"></i><b>11.11.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ci.html"><a href="ci.html"><i class="fa fa-check"></i><b>12</b> Confidence intervals</a>
<ul>
<li class="chapter" data-level="" data-path="ci.html"><a href="ci.html#functions-introduced-in-this-chapter-11"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="12.1" data-path="ci.html"><a href="ci.html#ci-intro"><i class="fa fa-check"></i><b>12.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ci.html"><a href="ci.html#ci-install"><i class="fa fa-check"></i><b>12.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="12.1.2" data-path="ci.html"><a href="ci.html#ci-download"><i class="fa fa-check"></i><b>12.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="12.1.3" data-path="ci.html"><a href="ci.html#ci-restart"><i class="fa fa-check"></i><b>12.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ci.html"><a href="ci.html#ci-load"><i class="fa fa-check"></i><b>12.2</b> Load packages</a></li>
<li class="chapter" data-level="12.3" data-path="ci.html"><a href="ci.html#ci-boot"><i class="fa fa-check"></i><b>12.3</b> Bootstrapping</a></li>
<li class="chapter" data-level="12.4" data-path="ci.html"><a href="ci.html#ci-computing-boot"><i class="fa fa-check"></i><b>12.4</b> Computing a bootstrap sampling distribution</a></li>
<li class="chapter" data-level="12.5" data-path="ci.html"><a href="ci.html#ci-ci"><i class="fa fa-check"></i><b>12.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="12.6" data-path="ci.html"><a href="ci.html#ci-conditions"><i class="fa fa-check"></i><b>12.6</b> Conditions</a></li>
<li class="chapter" data-level="12.7" data-path="ci.html"><a href="ci.html#ci-rubric"><i class="fa fa-check"></i><b>12.7</b> Rubric for confidence intervals</a></li>
<li class="chapter" data-level="12.8" data-path="ci.html"><a href="ci.html#ci-ex"><i class="fa fa-check"></i><b>12.8</b> Example</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="ci.html"><a href="ci.html#ci-ex-conditions"><i class="fa fa-check"></i><b>12.8.1</b> Check the relevant conditions to ensure that model assumptions are met.</a></li>
<li class="chapter" data-level="12.8.2" data-path="ci.html"><a href="ci.html#ci-ex-calcaulte"><i class="fa fa-check"></i><b>12.8.2</b> Calculate and graph the confidence interval.</a></li>
<li class="chapter" data-level="12.8.3" data-path="ci.html"><a href="ci.html#ci-ex-interpret"><i class="fa fa-check"></i><b>12.8.3</b> State (but do not overstate) a contextually meaningful interpretation.</a></li>
<li class="chapter" data-level="12.8.4" data-path="ci.html"><a href="ci.html#ci-ex-ci-ht"><i class="fa fa-check"></i><b>12.8.4</b> If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.</a></li>
<li class="chapter" data-level="12.8.5" data-path="ci.html"><a href="ci.html#ci-ex-effect"><i class="fa fa-check"></i><b>12.8.5</b> When comparing two groups, comment on the effect size and the practical significance of the result.</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="ci.html"><a href="ci.html#ci-your-turn"><i class="fa fa-check"></i><b>12.9</b> Your turn</a></li>
<li class="chapter" data-level="12.10" data-path="ci.html"><a href="ci.html#ci-interpret"><i class="fa fa-check"></i><b>12.10</b> Interpreting confidence intervals</a></li>
<li class="chapter" data-level="12.11" data-path="ci.html"><a href="ci.html#ci-conclusion"><i class="fa fa-check"></i><b>12.11</b> Conclusion</a>
<ul>
<li class="chapter" data-level="12.11.1" data-path="ci.html"><a href="ci.html#ci-prep"><i class="fa fa-check"></i><b>12.11.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>13</b> Normal models</a>
<ul>
<li class="chapter" data-level="" data-path="normal.html"><a href="normal.html#functions-introduced-in-this-chapter-12"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="13.1" data-path="normal.html"><a href="normal.html#normal-intro"><i class="fa fa-check"></i><b>13.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="normal.html"><a href="normal.html#normal-install"><i class="fa fa-check"></i><b>13.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="13.1.2" data-path="normal.html"><a href="normal.html#normal-download"><i class="fa fa-check"></i><b>13.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="13.1.3" data-path="normal.html"><a href="normal.html#normal-restart"><i class="fa fa-check"></i><b>13.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="normal.html"><a href="normal.html#normal-load"><i class="fa fa-check"></i><b>13.2</b> Load packages</a></li>
<li class="chapter" data-level="13.3" data-path="normal.html"><a href="normal.html#normal-clt"><i class="fa fa-check"></i><b>13.3</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="13.4" data-path="normal.html"><a href="normal.html#normal-normal"><i class="fa fa-check"></i><b>13.4</b> Normal models</a></li>
<li class="chapter" data-level="13.5" data-path="normal.html"><a href="normal.html#normal-predictions"><i class="fa fa-check"></i><b>13.5</b> Predictions using normal models</a></li>
<li class="chapter" data-level="13.6" data-path="normal.html"><a href="normal.html#normal-percentiles"><i class="fa fa-check"></i><b>13.6</b> Percentiles</a></li>
<li class="chapter" data-level="13.7" data-path="normal.html"><a href="normal.html#normal-z"><i class="fa fa-check"></i><b>13.7</b> Z scores</a></li>
<li class="chapter" data-level="13.8" data-path="normal.html"><a href="normal.html#normal-qq"><i class="fa fa-check"></i><b>13.8</b> QQ plots</a></li>
<li class="chapter" data-level="13.9" data-path="normal.html"><a href="normal.html#normal-conclusion"><i class="fa fa-check"></i><b>13.9</b> Conclusion</a>
<ul>
<li class="chapter" data-level="13.9.1" data-path="normal.html"><a href="normal.html#normal-prep"><i class="fa fa-check"></i><b>13.9.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="samp-dist-models.html"><a href="samp-dist-models.html"><i class="fa fa-check"></i><b>14</b> Sampling distribution models</a>
<ul>
<li class="chapter" data-level="" data-path="samp-dist-models.html"><a href="samp-dist-models.html#functions-introduced-in-this-chapter-13"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="14.1" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-intro"><i class="fa fa-check"></i><b>14.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-install"><i class="fa fa-check"></i><b>14.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="14.1.2" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-download"><i class="fa fa-check"></i><b>14.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="14.1.3" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-restart"><i class="fa fa-check"></i><b>14.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-load"><i class="fa fa-check"></i><b>14.2</b> Load packages</a></li>
<li class="chapter" data-level="14.3" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-sampling-variability"><i class="fa fa-check"></i><b>14.3</b> Sampling variability and sample size</a></li>
<li class="chapter" data-level="14.4" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-se"><i class="fa fa-check"></i><b>14.4</b> The sampling distribution model and the standard error</a></li>
<li class="chapter" data-level="14.5" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-conditions"><i class="fa fa-check"></i><b>14.5</b> Conditions</a></li>
<li class="chapter" data-level="14.6" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-predictions"><i class="fa fa-check"></i><b>14.6</b> Using the model to make predictions</a></li>
<li class="chapter" data-level="14.7" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-conclusion"><i class="fa fa-check"></i><b>14.7</b> Conclusion</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="samp-dist-models.html"><a href="samp-dist-models.html#samp-dist-models-prep"><i class="fa fa-check"></i><b>14.7.1</b> Preparing and submitting your assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="one-prop.html"><a href="one-prop.html"><i class="fa fa-check"></i><b>15</b> Inference for one proportion</a>
<ul>
<li class="chapter" data-level="" data-path="one-prop.html"><a href="one-prop.html#functions-introduced-in-this-chapter-14"><i class="fa fa-check"></i>Functions introduced in this chapter</a></li>
<li class="chapter" data-level="15.1" data-path="one-prop.html"><a href="one-prop.html#one-prop-intro"><i class="fa fa-check"></i><b>15.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="one-prop.html"><a href="one-prop.html#one-prop-install"><i class="fa fa-check"></i><b>15.1.1</b> Install new packages</a></li>
<li class="chapter" data-level="15.1.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-download"><i class="fa fa-check"></i><b>15.1.2</b> Download the R notebook file</a></li>
<li class="chapter" data-level="15.1.3" data-path="one-prop.html"><a href="one-prop.html#one-prop-restart"><i class="fa fa-check"></i><b>15.1.3</b> Restart R and run all chunks</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-load"><i class="fa fa-check"></i><b>15.2</b> Load packages</a></li>
<li class="chapter" data-level="15.3" data-path="one-prop.html"><a href="one-prop.html#one-prop-rubric"><i class="fa fa-check"></i><b>15.3</b> Revisiting the rubric for inference</a></li>
<li class="chapter" data-level="15.4" data-path="one-prop.html"><a href="one-prop.html#one-prop-question"><i class="fa fa-check"></i><b>15.4</b> Research question</a></li>
<li class="chapter" data-level="15.5" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-eda"><i class="fa fa-check"></i><b>15.5</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.5.1</b> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</a></li>
<li class="chapter" data-level="15.5.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-prepare"><i class="fa fa-check"></i><b>15.5.2</b> Prepare the data for analysis.</a></li>
<li class="chapter" data-level="15.5.3" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-plots"><i class="fa fa-check"></i><b>15.5.3</b> Make tables or plots to explore the data visually.</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-hypotheses"><i class="fa fa-check"></i><b>15.6</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-sample-pop"><i class="fa fa-check"></i><b>15.6.1</b> Identify the sample (or samples) and a reasonable population (or populations) of interest.</a></li>
<li class="chapter" data-level="15.6.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-express-words"><i class="fa fa-check"></i><b>15.6.2</b> Express the null and alternative hypotheses as contextually meaningful full sentences.</a></li>
<li class="chapter" data-level="15.6.3" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-express-math"><i class="fa fa-check"></i><b>15.6.3</b> Express the null and alternative hypotheses in symbols (when possible).</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-model"><i class="fa fa-check"></i><b>15.7</b> Model</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-sampling-dist-model"><i class="fa fa-check"></i><b>15.7.1</b> Identify the sampling distribution model.</a></li>
<li class="chapter" data-level="15.7.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-ht-conditions"><i class="fa fa-check"></i><b>15.7.2</b> Check the relevant conditions to ensure that model assumptions are met.</a></li>
</ul></li>
<li class="chapter" data-level="15.8" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-mechanics"><i class="fa fa-check"></i><b>15.8</b> Mechanics</a>
<ul>
<li class="chapter" data-level="15.8.1" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-compute-test-stat"><i class="fa fa-check"></i><b>15.8.1</b> Compute the test statistic.</a></li>
<li class="chapter" data-level="15.8.2" data-path="one-prop.html"><a href="one-prop.html#one-prop-ex-"><i class="fa fa-check"></i><b>15.8.2</b> Report the test statistic in context (when possible).</a></li>
<li class="chapter" data-level="15.8.3" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.8.3</b> Plot the null distribution.</a></li>
<li class="chapter" data-level="15.8.4" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.8.4</b> Calculate the P-value.</a></li>
<li class="chapter" data-level="15.8.5" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.8.5</b> Interpret the P-value as a probability given the null.</a></li>
</ul></li>
<li class="chapter" data-level="15.9" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.9</b> Conclusion</a>
<ul>
<li class="chapter" data-level="15.9.1" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.9.1</b> State the statistical conclusion.</a></li>
<li class="chapter" data-level="15.9.2" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.9.2</b> State (but do not overstate) a contextually meaningful conclusion.</a></li>
<li class="chapter" data-level="15.9.3" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.9.3</b> Express reservations or uncertainty about the generalizability of the conclusion.</a></li>
<li class="chapter" data-level="15.9.4" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.9.4</b> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</a></li>
</ul></li>
<li class="chapter" data-level="15.10" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10</b> Confidence interval</a>
<ul>
<li class="chapter" data-level="15.10.1" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10.1</b> Check the relevant conditions to ensure that model assumptions are met.</a></li>
<li class="chapter" data-level="15.10.2" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10.2</b> Calculate and graph the confidence interval.</a></li>
<li class="chapter" data-level="15.10.3" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10.3</b> State (but do not overstate) a contextually meaningful interpretation.</a></li>
<li class="chapter" data-level="15.10.4" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10.4</b> If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.</a></li>
<li class="chapter" data-level="15.10.5" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.10.5</b> When comparing two groups, comment on the effect size and the practical significance of the result.</a></li>
</ul></li>
<li class="chapter" data-level="15.11" data-path="one-prop.html"><a href="one-prop.html#one-prop"><i class="fa fa-check"></i><b>15.11</b> Your turn</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendix-rubric.html"><a href="appendix-rubric.html"><i class="fa fa-check"></i><b>A</b> Rubric for inference</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#exploratory-data-analysis-3"><i class="fa fa-check"></i>Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#use-data-documentation-help-files-code-books-google-etc.-to-determine-as-much-as-possible-about-the-data-provenance-and-structure.-3"><i class="fa fa-check"></i>Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#prepare-the-data-for-analysis.-not-always-necessary.-3"><i class="fa fa-check"></i>Prepare the data for analysis. [Not always necessary.]</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#make-tables-or-plots-to-explore-the-data-visually.-3"><i class="fa fa-check"></i>Make tables or plots to explore the data visually.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#hypotheses-3"><i class="fa fa-check"></i>Hypotheses</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#identify-the-sample-or-samples-and-a-reasonable-population-or-populations-of-interest.-3"><i class="fa fa-check"></i>Identify the sample (or samples) and a reasonable population (or populations) of interest.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#express-the-null-and-alternative-hypotheses-as-contextually-meaningful-full-sentences.-3"><i class="fa fa-check"></i>Express the null and alternative hypotheses as contextually meaningful full sentences.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#express-the-null-and-alternative-hypotheses-in-symbols-when-possible.-3"><i class="fa fa-check"></i>Express the null and alternative hypotheses in symbols (when possible).</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#model-3"><i class="fa fa-check"></i>Model</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#identify-the-sampling-distribution-model.-3"><i class="fa fa-check"></i>Identify the sampling distribution model.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-5"><i class="fa fa-check"></i>Check the relevant conditions to ensure that model assumptions are met.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#mechanics-3"><i class="fa fa-check"></i>Mechanics</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#compute-the-test-statistic.-3"><i class="fa fa-check"></i>Compute the test statistic.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#report-the-test-statistic-in-context-when-possible.-3"><i class="fa fa-check"></i>Report the test statistic in context (when possible).</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#plot-the-null-distribution.-3"><i class="fa fa-check"></i>Plot the null distribution.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#calculate-the-p-value.-3"><i class="fa fa-check"></i>Calculate the P-value.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#interpret-the-p-value-as-a-probability-given-the-null.-3"><i class="fa fa-check"></i>Interpret the P-value as a probability given the null.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#conclusion-3"><i class="fa fa-check"></i>Conclusion</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#state-the-statistical-conclusion.-3"><i class="fa fa-check"></i>State the statistical conclusion.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#state-but-do-not-overstate-a-contextually-meaningful-conclusion.-3"><i class="fa fa-check"></i>State (but do not overstate) a contextually meaningful conclusion.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#express-reservations-or-uncertainty-about-the-generalizability-of-the-conclusion.-3"><i class="fa fa-check"></i>Express reservations or uncertainty about the generalizability of the conclusion.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#identify-the-possibility-of-either-a-type-i-or-type-ii-error-and-state-what-making-such-an-error-means-in-the-context-of-the-hypotheses.-3"><i class="fa fa-check"></i>Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#confidence-interval-1"><i class="fa fa-check"></i>Confidence interval</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-6"><i class="fa fa-check"></i>Check the relevant conditions to ensure that model assumptions are met.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#calculate-and-graph-the-confidence-interval.-1"><i class="fa fa-check"></i>Calculate and graph the confidence interval.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#state-but-do-not-overstate-a-contextually-meaningful-interpretation.-2"><i class="fa fa-check"></i>State (but do not overstate) a contextually meaningful interpretation.</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#if-running-a-two-sided-test-explain-how-the-confidence-interval-reinforces-the-conclusion-of-the-hypothesis-test.-not-always-applicable.-1"><i class="fa fa-check"></i>If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test. [Not always applicable.]</a></li>
<li class="chapter" data-level="" data-path="appendix-rubric.html"><a href="appendix-rubric.html#when-comparing-two-groups-comment-on-the-effect-size-and-the-practical-significance-of-the-result.-not-always-applicable.-1"><i class="fa fa-check"></i>When comparing two groups, comment on the effect size and the practical significance of the result. [Not always applicable.]</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistics: an integrated textbook and workbook using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="one-prop" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">Chapter 15</span> Inference for one proportion<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!-- Please don't mess with the next few lines! -->
<style>h5{font-size:2em;color:#0000FF}h6{font-size:1.5em;color:#0000FF}div.answer{margin-left:5%;border:1px solid #0000FF;border-left-width:10px;padding:25px} div.summary{background-color:rgba(30,144,255,0.1);border:3px double #0000FF;padding:25px}</style>
<p style="color:#ffffff">
2.0
</p>
<!-- Please don't mess with the previous few lines! -->
<div id="functions-introduced-in-this-chapter-14" class="section level3 unnumbered hasAnchor summary">
<h3>Functions introduced in this chapter<a href="one-prop.html#functions-introduced-in-this-chapter-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>No new R functions are introduced here.</p>
</div>
<div id="one-prop-intro" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> Introduction<a href="one-prop.html#one-prop-intro" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Our earlier work with simulations showed us that when the number of successes and failures is large enough, we can use a normal model as our sampling distribution model.</p>
<p>We revisit hypothesis tests for a single proportion, but now, instead of running a simulation to compute the P-value, we take the shortcut of computing the P-value directly from a normal model.</p>
<p>There are no new concepts here. All we are doing is revisiting the rubric for inference and making the necessary changes.</p>
<div id="one-prop-install" class="section level3 hasAnchor" number="15.1.1">
<h3><span class="header-section-number">15.1.1</span> Install new packages<a href="one-prop.html#one-prop-install" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are no new packages used in this chapter.</p>
</div>
<div id="one-prop-download" class="section level3 hasAnchor" number="15.1.2">
<h3><span class="header-section-number">15.1.2</span> Download the R notebook file<a href="one-prop.html#one-prop-download" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Check the upper-right corner in RStudio to make sure you’re in your <code>intro_stats</code> project. Then click on the following link to download this chapter as an R notebook file (<code>.Rmd</code>).</p>
<p><a href = "https://vectorposse.github.io/intro_stats/chapter_downloads/15-inference_for_one_proportion.Rmd" download>https://vectorposse.github.io/intro_stats/chapter_downloads/15-inference_for_one_proportion.Rmd</a></p>
<p>Once the file is downloaded, move it to your project folder in RStudio and open it there.</p>
</div>
<div id="one-prop-restart" class="section level3 hasAnchor" number="15.1.3">
<h3><span class="header-section-number">15.1.3</span> Restart R and run all chunks<a href="one-prop.html#one-prop-restart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In RStudio, select “Restart R and Run All Chunks” from the “Run” menu.</p>
</div>
</div>
<div id="one-prop-load" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> Load packages<a href="one-prop.html#one-prop-load" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We load the standard <code>tidyverse</code>, <code>janitor</code> and <code>infer</code> packages as well as the <code>openintro</code> package to access data on heart transplant candidates. We’ll include <code>mosaic</code> for one spot below when we compare the results of <code>infer</code> to the results of graphing a normal distribution using <code>qdist</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="one-prop.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.3.6     ✔ purrr   0.3.4
## ✔ tibble  3.1.7     ✔ dplyr   1.0.9
## ✔ tidyr   1.2.0     ✔ stringr 1.4.0
## ✔ readr   2.1.2     ✔ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="one-prop.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="one-prop.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb8-2"><a href="one-prop.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span></code></pre></div>
<pre><code>## Loading required package: airports</code></pre>
<pre><code>## Loading required package: cherryblossom</code></pre>
<pre><code>## Loading required package: usdata</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="one-prop.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;mosaic&#39;:
##   method                           from   
##   fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
<pre><code>## 
## The &#39;mosaic&#39; package masks several functions from core packages in order to add 
## additional features.  The original behavior of these functions should not be affected by this.</code></pre>
<pre><code>## 
## Attaching package: &#39;mosaic&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Matrix&#39;:
## 
##     mean</code></pre>
<pre><code>## The following object is masked from &#39;package:openintro&#39;:
## 
##     dotPlot</code></pre>
<pre><code>## The following objects are masked from &#39;package:infer&#39;:
## 
##     prop_test, t_test</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     count, do, tally</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     cross</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     stat</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
##     quantile, sd, t.test, var</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div id="one-prop-rubric" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> Revisiting the rubric for inference<a href="one-prop.html#one-prop-rubric" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Instead of running a simulation, we are going to assume that the sampling distribution can be modeled with a normal model as long as the conditions for using a normal model are met.</p>
<p>Although the rubric has not changed, the use of a normal model changes quite a bit about the way we go through the other steps. For example, we won’t have simulated values to give us a histogram of the null model. Instead, we’ll go straight to graphing a normal model. We won’t compute the percent of our simulated samples that are at least as extreme as our test statistic to get the P-value. The P-value from a normal model is found directly from shading the model.</p>
<p>What follows is a fully-worked example of inference for one proportion. After the hypothesis test (sometimes called a one-proportion z-test for reasons that will become clear), we also follow up by computing a confidence interval. <strong>From now on, we will consider inference to consist of a hypothesis test and a confidence interval.</strong> Whenever you’re asked a question that requires statistical inference, you should follow both the rubric steps for a hypothesis test and for a confidence interval.</p>
<p>The example below will pause frequently for commentary on the steps, especially where their execution will be different from what you’ve seen before when you used simulation. When it’s your turn to work through another example on your own, you should follow the outline of the rubric, but you should <strong>not</strong> copy and paste the commentary that accompanies it.</p>
</div>
<div id="one-prop-question" class="section level2 hasAnchor" number="15.4">
<h2><span class="header-section-number">15.4</span> Research question<a href="one-prop.html#one-prop-question" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data from the Stanford University Heart Transplant Study is located in the <code>openintro</code> package in a data frame called <code>heart_transplant</code>. From the help file we learn, “Each patient entering the program was designated officially a heart transplant candidate, meaning that he was gravely ill and would most likely benefit from a new heart.” Survival rates are not good for this population, although they are better for those who receive a heart transplant. Do heart transplant recipients still have less than a 50% chance of survival?</p>
</div>
<div id="one-prop-ex-eda" class="section level2 hasAnchor" number="15.5">
<h2><span class="header-section-number">15.5</span> Exploratory data analysis<a href="one-prop.html#one-prop-ex-eda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop" class="section level3 hasAnchor" number="15.5.1">
<h3><span class="header-section-number">15.5.1</span> Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Start by typing <code>?heart_transplant</code> at the Console or searching for <code>heart_translplant</code> in the Help tab to read the help file.</p>
<div id="exercise-1-11" class="section level5 unnumbered hasAnchor">
<h5>Exercise 1<a href="one-prop.html#exercise-1-11" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Click on the link under “Source” in the help file. Why is this not helpful for determining the provenance of the data?</p>
<p>Now try to do an internet search to find the original research article from 1974. Why is this search process also not likely to help you determine the provenance of the data?</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
<hr />
<p>Now that we have learned everything we can reasonably learn about the data, we print it out and look at the variables.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="one-prop.html#cb24-1" aria-hidden="true" tabindex="-1"></a>heart_transplant</span></code></pre></div>
<pre><code>## # A tibble: 103 × 8
##       id acceptyear   age survived survtime prior transplant  wait
##    &lt;int&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;       &lt;int&gt; &lt;fct&gt; &lt;fct&gt;      &lt;int&gt;
##  1    15         68    53 dead            1 no    control       NA
##  2    43         70    43 dead            2 no    control       NA
##  3    61         71    52 dead            2 no    control       NA
##  4    75         72    52 dead            2 no    control       NA
##  5     6         68    54 dead            3 no    control       NA
##  6    42         70    36 dead            3 no    control       NA
##  7    54         71    47 dead            3 no    control       NA
##  8    38         70    41 dead            5 no    treatment      5
##  9    85         73    47 dead            5 no    control       NA
## 10     2         68    51 dead            6 no    control       NA
## # … with 93 more rows</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="one-prop.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(heart_transplant)</span></code></pre></div>
<pre><code>## Rows: 103
## Columns: 8
## $ id         &lt;int&gt; 15, 43, 61, 75, 6, 42, 54, 38, 85, 2, 103, 12, 48, 102, 35,…
## $ acceptyear &lt;int&gt; 68, 70, 71, 72, 68, 70, 71, 70, 73, 68, 67, 68, 71, 74, 70,…
## $ age        &lt;int&gt; 53, 43, 52, 52, 54, 36, 47, 41, 47, 51, 39, 53, 56, 40, 43,…
## $ survived   &lt;fct&gt; dead, dead, dead, dead, dead, dead, dead, dead, dead, dead,…
## $ survtime   &lt;int&gt; 1, 2, 2, 2, 3, 3, 3, 5, 5, 6, 6, 8, 9, 11, 12, 16, 16, 16, …
## $ prior      &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, no,…
## $ transplant &lt;fct&gt; control, control, control, control, control, control, contr…
## $ wait       &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, 5, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
<p>Commentary: The variable of interest is <code>survived</code>, which is coded as a factor variable with two categories, “alive” and “dead”. Keep in mind that because we are interested in survival rates, the “alive” condition will be considered the “success” condition.</p>
<p>There are 103 patients, but we are not considering all these patients. Our sample should consist of only those patients who actually received the transplant. The following table shows that only 69 patients were in the “treatment” group (meaning that they received a heart transplant).</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="one-prop.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(heart_transplant, transplant) <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="one-prop.html#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>()</span></code></pre></div>
<pre><code>##  transplant   n   percent
##     control  34 0.3300971
##   treatment  69 0.6699029
##       Total 103 1.0000000</code></pre>
</div>
</div>
<div id="one-prop-ex-prepare" class="section level3 hasAnchor" number="15.5.2">
<h3><span class="header-section-number">15.5.2</span> Prepare the data for analysis.<a href="one-prop.html#one-prop-ex-prepare" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>CAUTION: If you are copying and pasting from this example to use for another research question, the following code chunk is specific to this research question and not applicable in other contexts.</strong></p>
<p>We need to use <code>filter</code> so we get only the patients who actually received the heart transplant.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="one-prop.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Do not copy and paste this code for future work</span></span>
<span id="cb30-2"><a href="one-prop.html#cb30-2" aria-hidden="true" tabindex="-1"></a>heart_transplant2 <span class="ot">&lt;-</span> heart_transplant <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="one-prop.html#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(transplant <span class="sc">==</span> <span class="st">&quot;treatment&quot;</span>)</span>
<span id="cb30-4"><a href="one-prop.html#cb30-4" aria-hidden="true" tabindex="-1"></a>heart_transplant2</span></code></pre></div>
<pre><code>## # A tibble: 69 × 8
##       id acceptyear   age survived survtime prior transplant  wait
##    &lt;int&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;       &lt;int&gt; &lt;fct&gt; &lt;fct&gt;      &lt;int&gt;
##  1    38         70    41 dead            5 no    treatment      5
##  2    95         73    40 dead           16 no    treatment      2
##  3     3         68    54 dead           16 no    treatment      1
##  4    74         72    29 dead           17 no    treatment      5
##  5    20         69    55 dead           28 no    treatment      1
##  6    70         72    52 dead           30 no    treatment      5
##  7     4         68    40 dead           39 no    treatment     36
##  8   100         74    35 alive          39 yes   treatment     38
##  9    16         68    56 dead           43 no    treatment     20
## 10    45         71    36 dead           45 no    treatment      1
## # … with 59 more rows</code></pre>
<p>Commentary: don’t forget the double equal sign (<code>==</code>) that checks whether the <code>treatment</code> variable is equal to the value “treatment”. (See the Chapter 5 if you’ve forgotten how to use <code>filter</code>.)</p>
<p>Again, this step isn’t something you need to do for other research questions. This question is peculiar because it asks only about patients who received a heart transplant, and that only involves a subset of the data we have in the <code>heart_transplant</code> data frame.</p>
</div>
<div id="one-prop-ex-plots" class="section level3 hasAnchor" number="15.5.3">
<h3><span class="header-section-number">15.5.3</span> Make tables or plots to explore the data visually.<a href="one-prop.html#one-prop-ex-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Making sure that we refer from now on to the <code>heart_transplant2</code> data frame and not the original <code>heart_transplant</code> data frame:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="one-prop.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(heart_transplant2, survived) <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="one-prop.html#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>()</span></code></pre></div>
<pre><code>##  survived  n   percent
##     alive 24 0.3478261
##      dead 45 0.6521739
##     Total 69 1.0000000</code></pre>
</div>
</div>
<div id="one-prop-ex-hypotheses" class="section level2 hasAnchor" number="15.6">
<h2><span class="header-section-number">15.6</span> Hypotheses<a href="one-prop.html#one-prop-ex-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop-ex-sample-pop" class="section level3 hasAnchor" number="15.6.1">
<h3><span class="header-section-number">15.6.1</span> Identify the sample (or samples) and a reasonable population (or populations) of interest.<a href="one-prop.html#one-prop-ex-sample-pop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The sample consists of 69 heart transplant recipients in a study at Stanford University. The population of interest is presumably all heart transplants recipients.</p>
</div>
<div id="one-prop-ex-express-words" class="section level3 hasAnchor" number="15.6.2">
<h3><span class="header-section-number">15.6.2</span> Express the null and alternative hypotheses as contextually meaningful full sentences.<a href="one-prop.html#one-prop-ex-express-words" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(H_{0}:\)</span> Heart transplant recipients have a 50% chance of survival.</p>
<p><span class="math inline">\(H_{A}:\)</span> Heart transplant recipients have less than a 50% chance of survival.</p>
<p>Commentary: It is slightly unusual that we are conducting a one-sided test. The standard default is typically a two-sided test. However, it is not for us to choose: the proposed research question is unequivocal in hypothesizing “less than 50%” survival.</p>
</div>
<div id="one-prop-ex-express-math" class="section level3 hasAnchor" number="15.6.3">
<h3><span class="header-section-number">15.6.3</span> Express the null and alternative hypotheses in symbols (when possible).<a href="one-prop.html#one-prop-ex-express-math" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(H_{0}: p_{alive} = 0.5\)</span></p>
<p><span class="math inline">\(H_{A}: p_{alive} &lt; 0.5\)</span></p>
</div>
</div>
<div id="one-prop-ex-model" class="section level2 hasAnchor" number="15.7">
<h2><span class="header-section-number">15.7</span> Model<a href="one-prop.html#one-prop-ex-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop-ex-sampling-dist-model" class="section level3 hasAnchor" number="15.7.1">
<h3><span class="header-section-number">15.7.1</span> Identify the sampling distribution model.<a href="one-prop.html#one-prop-ex-sampling-dist-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will use a normal model.</p>
<p>Commentary: In past chapters, we have simulated the sampling distribution or applied some kind of randomization to simulate the effect of the null hypothesis. The point of this chapter is that we can—when the conditions are met—substitute a normal model to replace the unimodal and symmetric histogram that resulted from randomization and simulation.</p>
</div>
<div id="one-prop-ex-ht-conditions" class="section level3 hasAnchor" number="15.7.2">
<h3><span class="header-section-number">15.7.2</span> Check the relevant conditions to ensure that model assumptions are met.<a href="one-prop.html#one-prop-ex-ht-conditions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Random
<ul>
<li>Since the 69 patients are from a study at Stanford, we do not have a random sample of all heart transplant recipients. We hope that the patients recruited to this study were physiologically similar to other heart patients so that they are a representative sample. Without more information, we have no real way of knowing.</li>
</ul></li>
<li>10%
<ul>
<li>69 patients are definitely less than 10% of all heart transplant recipients.</li>
</ul></li>
<li>Success/failure</li>
</ul>
<p><span class="math display">\[
np_{alive} = 69(0.5) = 34.5 \geq 10
\]</span></p>
<p><span class="math display">\[
n(1 - p_{alive}) = 69(0.5) = 34.5 \geq 10
\]</span></p>
<p>Commentary: Notice something interesting here. Why did we not use the 24 patients who survived and the 45 who died as the successes and failures? In other words, why did we use <span class="math inline">\(np_{alive}\)</span> and <span class="math inline">\(n(1 - p_{alive})\)</span> instead of <span class="math inline">\(n \hat{p}_{alive}\)</span> and <span class="math inline">\(n(1 - \hat{p}_{alive})\)</span>?</p>
<p>Remember the logic of inference and the philosophy of the null hypothesis. To convince the skeptics, we must assume the null hypothesis throughout the process. It’s only after we present sufficient evidence that can we reject the null and fall back on the alternative hypothesis that encapsulates our research question.</p>
<p>Therefore, under the assumption of the null, the sampling distribution is the <em>null distribution</em>, meaning that it’s centered at 0.5. All work we do with the normal model, including checking conditions, must use the null model with <span class="math inline">\(p_{alive}= 0.5\)</span>.</p>
<p>That’s also why the numbers don’t have to be whole numbers. If the null states that of the 69 patients, 50% are expected to survive, then we expect 50% of 69, or 34.5, to survive. Of course, you can’t have half of a survivor. But these are not <em>actual</em> survivors. Rather, they are the expected number of survivors in a group of 69 patients <em>on average</em> under the assumption of the null.</p>
</div>
</div>
<div id="one-prop-ex-mechanics" class="section level2 hasAnchor" number="15.8">
<h2><span class="header-section-number">15.8</span> Mechanics<a href="one-prop.html#one-prop-ex-mechanics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop-ex-compute-test-stat" class="section level3 hasAnchor" number="15.8.1">
<h3><span class="header-section-number">15.8.1</span> Compute the test statistic.<a href="one-prop.html#one-prop-ex-compute-test-stat" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="one-prop.html#cb34-1" aria-hidden="true" tabindex="-1"></a>alive_prop <span class="ot">&lt;-</span> heart_transplant2 <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="one-prop.html#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> survived, <span class="at">succes =</span> <span class="st">&quot;alive&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="one-prop.html#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">&quot;prop&quot;</span>)</span>
<span id="cb34-4"><a href="one-prop.html#cb34-4" aria-hidden="true" tabindex="-1"></a>alive_prop</span></code></pre></div>
<pre><code>## Response: survived (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1 0.348</code></pre>
<p>We’ll also compute the corresponding z score.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="one-prop.html#cb36-1" aria-hidden="true" tabindex="-1"></a>alive_z <span class="ot">&lt;-</span> heart_transplant2 <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="one-prop.html#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> survived, <span class="at">succes =</span> <span class="st">&quot;alive&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="one-prop.html#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">&quot;point&quot;</span>, <span class="at">p =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="one-prop.html#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">&quot;z&quot;</span>)</span>
<span id="cb36-5"><a href="one-prop.html#cb36-5" aria-hidden="true" tabindex="-1"></a>alive_z</span></code></pre></div>
<pre><code>## Response: survived (factor)
## Null Hypothesis: point
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1 -2.53</code></pre>
<p>Commentary: The sample proportion code is straightforward and we’ve seen it before. To get the z score, we also have to tell <code>infer</code> what the null hypothesis is so that it knows where the center of our normal distribution will be. In the <code>hypothesize</code> function, we tell <code>infer</code> to use a “point” null hypothesis with <code>p = 0.5</code>. All this means is that the null is a specific point: 0.5. (Contrast this to hypothesis tests with two variables when we had <code>null = "independence"</code>.)</p>
<p>We can confirm the calculation of the z score manually. It’s easiest to compute the standard error first. Recall that the standard error is</p>
<p><span class="math display">\[
SE = \sqrt{\frac{p_{alive}(1 - p_{alive})}{n}} = \sqrt{\frac{0.5(1 - 0.5)}{69}}
\]</span></p>
<p><strong>Remember that are working under the assumption of the null hypothesis.</strong> This means that we use <span class="math inline">\(p_{alive} = 0.5\)</span> everywhere in the formula for the standard error.</p>
<p>We can do the math in R and store our result as <code>SE</code>.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="one-prop.html#cb38-1" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.5</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">/</span><span class="dv">69</span>)</span>
<span id="cb38-2"><a href="one-prop.html#cb38-2" aria-hidden="true" tabindex="-1"></a>SE</span></code></pre></div>
<pre><code>## [1] 0.06019293</code></pre>
<p>Then our z score is</p>
<p><span class="math display">\[
z = \frac{(\hat{p}_{alive} - p_{alive})}{SE} =  \frac{(\hat{p}_{alive} - p_{alive})}{\sqrt{\frac{p_{alive} (1 - p_{alive})}{n}}} = \frac{(0.348 - 0.5)}{\sqrt{\frac{0.5 (1 - 0.5)}{69}}} =  -2.53.
\]</span></p>
<p>Using the values of <code>alive_prop</code> and <code>SE</code>:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="one-prop.html#cb40-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (alive_prop <span class="sc">-</span> <span class="fl">0.5</span>)<span class="sc">/</span>SE</span>
<span id="cb40-2"><a href="one-prop.html#cb40-2" aria-hidden="true" tabindex="-1"></a>z</span></code></pre></div>
<pre><code>##        stat
## 1 -2.528103</code></pre>
<p>Both the sample proportion <span class="math inline">\(\hat{p}_{alive}\)</span> (stored above as <code>alive_prop</code>) and the corresponding z-score can be considered the “test statistic”. If we use <span class="math inline">\(\hat{p}_{alive}\)</span> as the test statistic, then we’re considering the null model to be</p>
<p><span class="math display">\[
N\left(0.5, \sqrt{\frac{0.5 (1 - 0.5)}{69}}\right).
\]</span></p>
<p>If we use z as the test statistic, then we’re considering the null model to be the <em>standard normal model</em>:</p>
<p><span class="math display">\[
N(0, 1).
\]</span></p>
<p>The standard normal model is more intuitive and easier to work with, both conceptually and in R. Generally, then, we will consider z as the test statistic so that we can consider our null model to be the standard normal model. For example, knowing that our test statistic is two and a half standard deviations to the left of the null value already tells us a lot. We can anticipate a small P-value leading to rejection of the null. Nevertheless, for this type of hypothesis test, we’ll compute both in this section of the rubric.</p>
</div>
<div id="one-prop-ex-" class="section level3 hasAnchor" number="15.8.2">
<h3><span class="header-section-number">15.8.2</span> Report the test statistic in context (when possible).<a href="one-prop.html#one-prop-ex-" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The test statistic is 0.3478261. In other words, 34.7826087% of heart transplant recipients were alive at the end of the study.</p>
<p>The z score is -2.5281029. The proportion of survivors is about 2.5 standard errors below the null value.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.8.3">
<h3><span class="header-section-number">15.8.3</span> Plot the null distribution.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="one-prop.html#cb42-1" aria-hidden="true" tabindex="-1"></a>alive_test <span class="ot">&lt;-</span> heart_transplant2 <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="one-prop.html#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> survived, <span class="at">success =</span> <span class="st">&quot;alive&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="one-prop.html#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">&quot;point&quot;</span>, <span class="at">p =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="one-prop.html#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">assume</span>(<span class="at">distribution =</span> <span class="st">&quot;z&quot;</span>)</span>
<span id="cb42-5"><a href="one-prop.html#cb42-5" aria-hidden="true" tabindex="-1"></a>alive_test</span></code></pre></div>
<pre><code>## A Z distribution.</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="one-prop.html#cb44-1" aria-hidden="true" tabindex="-1"></a>alive_test <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="one-prop.html#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb44-3"><a href="one-prop.html#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> alive_z, <span class="at">direction =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<p><img src="intro_stats_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Commentary: In past chapters, we have used the <code>generate</code> verb to get many repetitions (usually 1000) of some kind of random process to simulate the sampling distribution model. In this chapter, we have used the verb <code>assume</code> instead to assume that the sampling distribution is a normal model. As long as the conditions hold, this is a reasonable assumption. This also means that we don’t have to use <code>set.seed</code> as there is no random process to reproduce.</p>
<p>Compare the graph above to what we would see if we simulated the sampling distribution. (Now we do need <code>set.seed</code>!)</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="one-prop.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">6789</span>)</span>
<span id="cb45-2"><a href="one-prop.html#cb45-2" aria-hidden="true" tabindex="-1"></a>alive_test_draw <span class="ot">&lt;-</span> heart_transplant2 <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="one-prop.html#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">specify</span>(<span class="at">response =</span> survived, <span class="at">success =</span> <span class="st">&quot;alive&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="one-prop.html#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">&quot;point&quot;</span>, <span class="at">p =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="one-prop.html#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">&quot;draw&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="one-prop.html#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">&quot;prop&quot;</span>)</span>
<span id="cb45-7"><a href="one-prop.html#cb45-7" aria-hidden="true" tabindex="-1"></a>alive_test_draw</span></code></pre></div>
<pre><code>## Response: survived (factor)
## Null Hypothesis: point
## # A tibble: 1,000 × 2
##    replicate  stat
##    &lt;fct&gt;     &lt;dbl&gt;
##  1 1         0.493
##  2 2         0.406
##  3 3         0.435
##  4 4         0.580
##  5 5         0.522
##  6 6         0.507
##  7 7         0.580
##  8 8         0.435
##  9 9         0.551
## 10 10        0.435
## # … with 990 more rows</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="one-prop.html#cb47-1" aria-hidden="true" tabindex="-1"></a>alive_test_draw <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="one-prop.html#cb47-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb47-3"><a href="one-prop.html#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> alive_prop, <span class="at">direction =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<p><img src="intro_stats_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>This is essentially the same picture, although the model above is centered on the null value 0.5 instead of the z score of 0. This also means that the <code>obs_stat</code> had to be the sample proportion <code>alive_prop</code> and not the z score <code>alive_z</code>.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.8.4">
<h3><span class="header-section-number">15.8.4</span> Calculate the P-value.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="one-prop.html#cb48-1" aria-hidden="true" tabindex="-1"></a>alive_test_p <span class="ot">&lt;-</span> alive_test <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="one-prop.html#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> alive_z, <span class="at">direction =</span> <span class="st">&quot;less&quot;</span>)</span>
<span id="cb48-3"><a href="one-prop.html#cb48-3" aria-hidden="true" tabindex="-1"></a>alive_test_p</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1 0.00573</code></pre>
<p>Commentary: compare this to the P-value we get from simulating random draws:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="one-prop.html#cb50-1" aria-hidden="true" tabindex="-1"></a>alive_test_draw <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="one-prop.html#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> alive_prop, <span class="at">direction =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1   0.007</code></pre>
<p>The values are not exactly the same. And a new simulation with a different seed would likely give another slightly different P-value. The takeaway here is that the P-value itself has some uncertainty, so you should never take the value too seriously.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.8.5">
<h3><span class="header-section-number">15.8.5</span> Interpret the P-value as a probability given the null.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The P-value is 0.005734. If there were truly a 50% chance of survival among heart transplant patients, there would only be a 0.5734037% chance of seeing data at least as extreme as we saw.</p>
</div>
</div>
<div id="one-prop" class="section level2 hasAnchor" number="15.9">
<h2><span class="header-section-number">15.9</span> Conclusion<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop" class="section level3 hasAnchor" number="15.9.1">
<h3><span class="header-section-number">15.9.1</span> State the statistical conclusion.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We reject the null hypothesis.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.9.2">
<h3><span class="header-section-number">15.9.2</span> State (but do not overstate) a contextually meaningful conclusion.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have sufficient evidence that heart transplant recipients have less than a 50% chance of survival.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.9.3">
<h3><span class="header-section-number">15.9.3</span> Express reservations or uncertainty about the generalizability of the conclusion.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because we know nearly nothing about the provenance of the data, it’s hard to generalize the conclusion. We know the data is from 1974, so it’s also very likely that survival rates for heart transplant patients then are not the same as they are today. The most we could hope for is that the Stanford data was representative for heart transplant patients in 1974. Our sample size (69) is also quite small.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.9.4">
<h3><span class="header-section-number">15.9.4</span> Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As we rejected the null, we run the risk of making a Type I error. It is possible that the null is true and that there is a 50% chance of survival for these patients, but we got an unusual sample that appears to have a much smaller chance of survival.</p>
</div>
</div>
<div id="one-prop" class="section level2 hasAnchor" number="15.10">
<h2><span class="header-section-number">15.10</span> Confidence interval<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="one-prop" class="section level3 hasAnchor" number="15.10.1">
<h3><span class="header-section-number">15.10.1</span> Check the relevant conditions to ensure that model assumptions are met.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Random
<ul>
<li>Same as above.</li>
</ul></li>
<li>10%
<ul>
<li>Same as above.</li>
</ul></li>
<li>Success/failure
<ul>
<li>There were 24 patients who survived and 45 who died in our sample. Both are larger than 10.</li>
</ul></li>
</ul>
<p>Commentary: In the “Confidence interval” section of the rubric, there is no need to recheck conditions that have already been checked. The sample has not changed; if it met the “Random” and “10%” conditions before, it will meet them now.</p>
<p>So why recheck the success/failure condition?</p>
<p>Keep in mind that in a hypothesis test, we temporarily assume the null is true. The null states that <span class="math inline">\(p = 0.5\)</span> and the resulting null distribution is, therefore, centered at <span class="math inline">\(p = 0.5\)</span>. The success/failure condition is a condition that applies to the normal model we’re using, and for a hypothesis test, that’s the null model.</p>
<p>By contrast, a confidence interval is making no assumption about the “true” value of <span class="math inline">\(p\)</span>. The inferential goal of a confidence interval is to try to capture the true value of <span class="math inline">\(p\)</span>, so we certainly cannot make any assumptions about it. Therefore, we go back to the original way we learned about the success/failure condition. That is, we check the actual number of successes and failures.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.10.2">
<h3><span class="header-section-number">15.10.2</span> Calculate and graph the confidence interval.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="one-prop.html#cb52-1" aria-hidden="true" tabindex="-1"></a>alive_ci <span class="ot">&lt;-</span> alive_test <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="one-prop.html#cb52-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">get_confidence_interval</span>(<span class="at">point_estimate =</span> alive_prop, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb52-3"><a href="one-prop.html#cb52-3" aria-hidden="true" tabindex="-1"></a>alive_ci</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.235    0.460</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="one-prop.html#cb54-1" aria-hidden="true" tabindex="-1"></a>alive_test <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="one-prop.html#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">visualize</span>() <span class="sc">+</span></span>
<span id="cb54-3"><a href="one-prop.html#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> alive_ci)</span></code></pre></div>
<p><img src="intro_stats_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Commentary: when we use a theoretical normal distribution, we have to compute the confidence interval a different way.</p>
<p>When we bootstrapped, we had many repetitions of a process that resulted in a sampling distribution. From all those, we could find the 2.5th percentile and the 97.5th percentile. Although we let the computer do it for us, the process is straightforward enough that we could do it by hand if we needed to. Just put all 1000 bootstrapped values in order, then go to the 25th and 975th position in the list.</p>
<p>We don’t have a list of 1000 values when we use an abstract curve to represent our sampling distribution. Nevertheless, we can find the 2.5th percentile and the 97.5th percentile using the area under the normal curve as we saw in the last two chapters. We can do this “manually” with the <code>qdist</code> command, but we need the standard error first.</p>
<p>Didn’t we calculate this earlier?</p>
<p><span class="math display">\[
SE = \sqrt{\frac{p_{alive}(1 - p_{alive})}{n}} = \sqrt{\frac{0.5(1 - 0.5)}{69}}
\]</span></p>
<p>Well…sort of. The value of <span class="math inline">\(p_{alive}\)</span> here is the value of the null hypothesis from the hypothesis test above. <em>However</em>, the hypothesis test is done. For a confidence interval, we have no information about any “null” value. There is no null anymore. It’s irrelevant.</p>
<p>So what is the standard error for a confidence interval? Since we don’t have <span class="math inline">\(p_{alive}\)</span>, the best we can do is replace it with <span class="math inline">\(\hat{p}_{alive}\)</span>:</p>
<p><span class="math display">\[
SE = \sqrt{\frac{\hat{p}_{alive} (1 - \hat{p}_{alive})}{n}} = \sqrt{\frac{0.3478261 (1 - 0.3478261 )}{69}}.
\]</span></p>
<p>We can let R do the heavy lifting here:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="one-prop.html#cb55-1" aria-hidden="true" tabindex="-1"></a>SE2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(alive_prop <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> alive_prop) <span class="sc">/</span> <span class="dv">69</span>)</span>
<span id="cb55-2"><a href="one-prop.html#cb55-2" aria-hidden="true" tabindex="-1"></a>SE2</span></code></pre></div>
<pre><code>##         stat
## 1 0.05733743</code></pre>
<p>And now this number can go into <code>qdist</code> as our standard deviation:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="one-prop.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qdist</span>(<span class="st">&quot;norm&quot;</span>, <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">mean =</span> <span class="fl">0.3478261</span>, <span class="at">sd =</span> <span class="fl">0.05733743</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.2354468 0.4602054</code></pre>
<p>The numbers above are identical to the ones computed by the <code>infer</code> commands.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.10.3">
<h3><span class="header-section-number">15.10.3</span> State (but do not overstate) a contextually meaningful interpretation.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are 95% confident that the true percentage of heart transplant recipients who survive is captured in the interval (23.5446784%, 46.020539%).</p>
<p>Commentary: Note that when we state our contextually meaningful conclusion, we also convert the decimal proportions to percentages. Humans like percentages a lot better.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.10.4">
<h3><span class="header-section-number">15.10.4</span> If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are not running a two-sided test, so this step is not applicable.</p>
</div>
<div id="one-prop" class="section level3 hasAnchor" number="15.10.5">
<h3><span class="header-section-number">15.10.5</span> When comparing two groups, comment on the effect size and the practical significance of the result.<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is not applicable here because we are not comparing two groups. We are looking at the survival percentage in only one group of patients, those who had a heart transplant.</p>
</div>
</div>
<div id="one-prop" class="section level2 hasAnchor" number="15.11">
<h2><span class="header-section-number">15.11</span> Your turn<a href="one-prop.html#one-prop" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Follow the rubric to answer the following research question:</p>
<p>Some heart transplant candidates have already had a prior surgery. Use the variable <code>prior</code> in the <code>heart_transplant</code> data set to determine if fewer than 50% of patients have had a prior surgery. (To be clear, you are being asked to perform a one-sided test again.) <strong>Be sure to use the full <code>heart_transplant</code> data, not the modified <code>heart_transplant2</code> from the previous example.</strong></p>
<p>The rubric outline is reproduced below. You may refer to the worked example above and modify it accordingly. Remember to strip out all the commentary. That is just exposition for your benefit in understanding the steps, but is not meant to form part of the formal inference process.</p>
<p>Another word of warning: the copy/paste process is not a substitute for your brain. You will often need to modify more than just the names of the tibbles and variables to adapt the worked examples to your own work. For example, if you run a two-sided test instead of a one-sided test, there are a few places that have to be adjusted accordingly. Understanding the sampling distribution model and the computation of the P-value goes a long way toward understanding the changes that must be made. Do not blindly copy and paste code without understanding what it does. And you should <strong>never</strong> copy and paste text. All the sentences and paragraphs you write are expressions of your own analysis. They must reflect your own understanding of the inferential process.</p>
<p><strong>Also, so that your answers here don’t mess up the code chunks above, use new variable names everywhere. In particular, you should use <code>prior_test</code>(instead of <code>alive_test</code>) to store the results of your hypothesis test. Make other corresponding changes as necessary, like <code>prior_test_p</code> instead of <code>alive_test_p</code>, for example.</strong></p>
<div id="exploratory-data-analysis-2" class="section level5 unnumbered hasAnchor">
<h5>Exploratory data analysis<a href="one-prop.html#exploratory-data-analysis-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="use-data-documentation-help-files-code-books-google-etc.-to-determine-as-much-as-possible-about-the-data-provenance-and-structure.-2" class="section level6 unnumbered hasAnchor">
<h6>Use data documentation (help files, code books, Google, etc.) to determine as much as possible about the data provenance and structure.<a href="one-prop.html#use-data-documentation-help-files-code-books-google-etc.-to-determine-as-much-as-possible-about-the-data-provenance-and-structure.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="one-prop.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to print the data</span></span></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="one-prop.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to glimpse the variables</span></span></code></pre></div>
</div>
</div>
<div id="prepare-the-data-for-analysis.-not-always-necessary.-2" class="section level6 unnumbered hasAnchor">
<h6>Prepare the data for analysis. [Not always necessary.]<a href="one-prop.html#prepare-the-data-for-analysis.-not-always-necessary.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="one-prop.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to prepare the data for analysis.</span></span></code></pre></div>
</div>
</div>
<div id="make-tables-or-plots-to-explore-the-data-visually.-2" class="section level6 unnumbered hasAnchor">
<h6>Make tables or plots to explore the data visually.<a href="one-prop.html#make-tables-or-plots-to-explore-the-data-visually.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="one-prop.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to make tables or plots.</span></span></code></pre></div>
</div>
</div>
</div>
<div id="hypotheses-2" class="section level5 unnumbered hasAnchor">
<h5>Hypotheses<a href="one-prop.html#hypotheses-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="identify-the-sample-or-samples-and-a-reasonable-population-or-populations-of-interest.-2" class="section level6 unnumbered hasAnchor">
<h6>Identify the sample (or samples) and a reasonable population (or populations) of interest.<a href="one-prop.html#identify-the-sample-or-samples-and-a-reasonable-population-or-populations-of-interest.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<p>[Remember that you are using the full <code>heart_transplant</code> data, so your sample size should be larger here than in the example above.]</p>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="express-the-null-and-alternative-hypotheses-as-contextually-meaningful-full-sentences.-2" class="section level6 unnumbered hasAnchor">
<h6>Express the null and alternative hypotheses as contextually meaningful full sentences.<a href="one-prop.html#express-the-null-and-alternative-hypotheses-as-contextually-meaningful-full-sentences.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p><span class="math inline">\(H_{0}:\)</span> Null hypothesis goes here.</p>
<p><span class="math inline">\(H_{A}:\)</span> Alternative hypothesis goes here.</p>
</div>
</div>
<div id="express-the-null-and-alternative-hypotheses-in-symbols-when-possible.-2" class="section level6 unnumbered hasAnchor">
<h6>Express the null and alternative hypotheses in symbols (when possible).<a href="one-prop.html#express-the-null-and-alternative-hypotheses-in-symbols-when-possible.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p><span class="math inline">\(H_{0}: math\)</span></p>
<p><span class="math inline">\(H_{A}: math\)</span></p>
</div>
</div>
</div>
<div id="model-2" class="section level5 unnumbered hasAnchor">
<h5>Model<a href="one-prop.html#model-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="identify-the-sampling-distribution-model.-2" class="section level6 unnumbered hasAnchor">
<h6>Identify the sampling distribution model.<a href="one-prop.html#identify-the-sampling-distribution-model.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-3" class="section level6 unnumbered hasAnchor">
<h6>Check the relevant conditions to ensure that model assumptions are met.<a href="one-prop.html#check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-3" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<p>[Remember that you are using the full <code>heart_transplant</code> data, so the number of successes and failures will be different here than in the example above.]</p>
<div class="answer">
<p>Please write up your answer here. (Some conditions may require R code as well.)</p>
</div>
</div>
</div>
<div id="mechanics-2" class="section level5 unnumbered hasAnchor">
<h5>Mechanics<a href="one-prop.html#mechanics-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>[Be sure to use <code>heart_transplant</code> everywhere and not <code>heart_transplant2</code>!]</p>
<div id="compute-the-test-statistic.-2" class="section level6 unnumbered hasAnchor">
<h6>Compute the test statistic.<a href="one-prop.html#compute-the-test-statistic.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="one-prop.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to compute the test statistic.</span></span></code></pre></div>
</div>
</div>
<div id="report-the-test-statistic-in-context-when-possible.-2" class="section level6 unnumbered hasAnchor">
<h6>Report the test statistic in context (when possible).<a href="one-prop.html#report-the-test-statistic-in-context-when-possible.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="plot-the-null-distribution.-2" class="section level6 unnumbered hasAnchor">
<h6>Plot the null distribution.<a href="one-prop.html#plot-the-null-distribution.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="one-prop.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to plot the null distribution.</span></span></code></pre></div>
</div>
</div>
<div id="calculate-the-p-value.-2" class="section level6 unnumbered hasAnchor">
<h6>Calculate the P-value.<a href="one-prop.html#calculate-the-p-value.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="one-prop.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to calculate the P-value.</span></span></code></pre></div>
</div>
</div>
<div id="interpret-the-p-value-as-a-probability-given-the-null.-2" class="section level6 unnumbered hasAnchor">
<h6>Interpret the P-value as a probability given the null.<a href="one-prop.html#interpret-the-p-value-as-a-probability-given-the-null.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
</div>
<div id="conclusion-2" class="section level5 unnumbered hasAnchor">
<h5>Conclusion<a href="one-prop.html#conclusion-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="state-the-statistical-conclusion.-2" class="section level6 unnumbered hasAnchor">
<h6>State the statistical conclusion.<a href="one-prop.html#state-the-statistical-conclusion.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="state-but-do-not-overstate-a-contextually-meaningful-conclusion.-2" class="section level6 unnumbered hasAnchor">
<h6>State (but do not overstate) a contextually meaningful conclusion.<a href="one-prop.html#state-but-do-not-overstate-a-contextually-meaningful-conclusion.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="express-reservations-or-uncertainty-about-the-generalizability-of-the-conclusion.-2" class="section level6 unnumbered hasAnchor">
<h6>Express reservations or uncertainty about the generalizability of the conclusion.<a href="one-prop.html#express-reservations-or-uncertainty-about-the-generalizability-of-the-conclusion.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="identify-the-possibility-of-either-a-type-i-or-type-ii-error-and-state-what-making-such-an-error-means-in-the-context-of-the-hypotheses.-2" class="section level6 unnumbered hasAnchor">
<h6>Identify the possibility of either a Type I or Type II error and state what making such an error means in the context of the hypotheses.<a href="one-prop.html#identify-the-possibility-of-either-a-type-i-or-type-ii-error-and-state-what-making-such-an-error-means-in-the-context-of-the-hypotheses.-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
</div>
<div id="confidence-interval" class="section level5 unnumbered hasAnchor">
<h5>Confidence interval<a href="one-prop.html#confidence-interval" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-4" class="section level6 unnumbered hasAnchor">
<h6>Check the relevant conditions to ensure that model assumptions are met.<a href="one-prop.html#check-the-relevant-conditions-to-ensure-that-model-assumptions-are-met.-4" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here. (Some conditions may require R code as well.)</p>
</div>
</div>
<div id="calculate-the-confidence-interval." class="section level6 unnumbered hasAnchor">
<h6>Calculate the confidence interval.<a href="one-prop.html#calculate-the-confidence-interval." class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="one-prop.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add code here to calculate the confidence interval.</span></span></code></pre></div>
</div>
</div>
<div id="state-but-do-not-overstate-a-contextually-meaningful-interpretation.-1" class="section level6 unnumbered hasAnchor">
<h6>State (but do not overstate) a contextually meaningful interpretation.<a href="one-prop.html#state-but-do-not-overstate-a-contextually-meaningful-interpretation.-1" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="if-running-a-two-sided-test-explain-how-the-confidence-interval-reinforces-the-conclusion-of-the-hypothesis-test.-not-always-applicable." class="section level6 unnumbered hasAnchor">
<h6>If running a two-sided test, explain how the confidence interval reinforces the conclusion of the hypothesis test. [Not always applicable.]<a href="one-prop.html#if-running-a-two-sided-test-explain-how-the-confidence-interval-reinforces-the-conclusion-of-the-hypothesis-test.-not-always-applicable." class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>
</div>
<div id="when-comparing-two-groups-comment-on-the-effect-size-and-the-practical-significance-of-the-result.-not-always-applicable." class="section level6 unnumbered hasAnchor">
<h6>When comparing two groups, comment on the effect size and the practical significance of the result. [Not always applicable.]<a href="one-prop.html#when-comparing-two-groups-comment-on-the-effect-size-and-the-practical-significance-of-the-result.-not-always-applicable." class="anchor-section" aria-label="Anchor link to header"></a></h6>
<div class="answer">
<p>Please write up your answer here.</p>
</div>

</div>
</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="samp-dist-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-rubric.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["intro_stats.pdf", "intro_stats.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
